- .github/workflows/main_windows.yml
- internal/kclvm_py/compiler/extension/plugin/plugin.py
- kclvm/runner/src/command.rs
- scripts/build-windows/Makefile
- scripts/build-windows/install-rust-std.go
- scripts/build-windows/readme.md
- scripts/build-windows/requirements.release.txt
build kclvm-windows.zip in github action
> feat: add kclvm-windows.zip build to windows github action

- internal/kclvm_py/scripts/requirements.txt
- scripts/build-windows/requirements.release.txt
Note:
1. Upgrade dependencies (PyYAML).
What:
1. Upgrade dependencies (PyYAML) in internal/kclvm_py/scripts/requirements.txt
and scripts/build-windows/requirements.release.txt.
How:
1. PyYAML 5.3 -> PyYAML 5.4 in internal/kclvm_py/scripts/requirements.txt
and scripts/build-windows/requirements.release.txt.
Why:
1. Upgrade PyYAML dependencies.
- With pull requests:
- Open your pull request against `main`
- Your pull request should have no more than two commits, if not you should squash them.
- It should pass all tests in the available continuous integration systems such as GitHub Actions.
- You should add/modify tests to cover your proposed code changes.
- If your pull request contains a new feature, please document it on the README.
> refactor: Upgrade PyYAML dependencies.

- .gitattributes
Purpose:
1. Remove statistics for some code types including h5 and python
> Remove statistics for some code types

- .github/workflows/github-actions.yaml
Purpose:
1. add rust unit test in the github aciion.
> feat: add rust test to github action.

- kclvm/runner/src/command.rs
find `${KCLVM_CLANG}` at first, find `{root}/tools/clang/bin/clang` second, find system `$PATH` at last.
> fix clang path

- kclvm/runner/src/command.rs
> fix: main so not found on ubuntu issue.

- kclvm/docs/m1-mac-setup.md
Add description of how to install llvm@12 via homebrew for m1 mac user
> doc: Update setup document for m1 mac:  install llvm@12 via homebrew

- kclvm/runner/src/command.rs
- kclvm/src/lib.rs
> refactor: use temp main codegen output and more documents on dylib cache read/write.

- internal/MANIFEST.in
- internal/__init__.py
- internal/kclvm_py/api/__init__.py
- internal/kclvm_py/scripts/requirements.txt
- internal/setup.py
- scripts/build-windows/requirements.release.txt
#46 add set_up.py to build KCLVM python package,  and upload it to PyPI.
PyPI project: https://pypi.org/project/kclvm/
> Enhancement: KCLVM python package for PyPI

- docs/dev_guide/1.about_this_guide.md
- docs/dev_guide/2.quick_start.md
In #61, the directory of KCL developing guide is discussed and designed, this PR is to fill in the content of the first two chapters (About the guide & Quick Start), and other content is written in another PR.
/docs/dev_guide/1.about_this_guide.md
/docs/dev_guide/2.quick_start.md
Documentation improvements.
```release-note
None
```
> feat: add dev guide about and quick start sections.

- internal/kclvm_py/scripts/release.sh
> fix: script remove extended attributes

- kclvm/sema/src/resolver/global.rs
- kclvm/sema/src/resolver/import.rs
- kclvm/sema/src/resolver/test_fail_data/cycle_reference/file1.k
- kclvm/sema/src/resolver/test_fail_data/cycle_reference/file2.k
- kclvm/sema/src/resolver/tests.rs
- kclvm/sema/src/ty/context.rs
re #101 
* kclvm/sema/src/resolver/global.rs
* kclvm/sema/src/resolver/import.rs
The test case `test_resolve_program_cycle_reference_fail` in kclvm/sema/src/resolver/tests.rs
```release-note
None
```
> refactor: refine cycle reference error messages and add unit test cases.

- .github/workflows/github-actions.yaml
Rust unstable nightly version causes github action to fail. Fixed it to a stable version.
.github/workflows/github-action.yaml
Rust unstable nightly version causes github action to fail. Fixed it to a stable version.
```release-note
None
```
> Fix(github action): modify rust toolchain version.

- kclvm/runner/src/runner.rs
- kclvm/sema/src/resolver/tests.rs
- kclvm/src/main.rs
src/main.rs
fix cli args
```
cd $workspace
kclvm_cli run -Y "ci-test/settings" "kcl.yaml"
```
```release-note
None
```
> Fix kclvm cli args parse for `-Y` 

- .github/workflows/macos_test.yaml
- .github/workflows/ubuntu_test.yaml
re: #129 
```release-note
None
```
> chore: add rust code format check in github actions.

- kclvm/sema/src/pre_process/config.rs
- kclvm/sema/src/pre_process/test_data/config_merge/config1.k
- kclvm/sema/src/pre_process/test_data/config_merge/config2.k
- kclvm/sema/src/pre_process/test_data/config_merge/def.k
- kclvm/sema/src/pre_process/tests.rs
re: #153 
* kclvm/sema/src/pre_process/config.rs
`test_config_merge` at `kclvm/sema/src/pre_process/tests.rs`
```release-note
None
```
> re: config merge when input same files on `load_program`.

- kclvm/Cargo.toml
- kclvm/runtime/src/value/val_plan.rs
- kclvm/src/main.rs
[kclvm/runtime/src/value/val_plan.rs](https://github.com/KusionStack/KCLVM/compare/main...NeverRaR:kclvm-capi-call?expand=1#diff-ec835b43002448358b3609f9ab3254dd4e6c2300551b0750254bcd2c8d739572)
[kclvm/src/main.rs](https://github.com/KusionStack/KCLVM/compare/main...NeverRaR:kclvm-capi-call?expand=1#diff-601fdbfda12fb5fb5f81aa354bad685eeaf36add4163e0b87e12c9d154586b72)
use YAML plan with delimiter in KCLVM Rust ver
```release-note
None
```
> refactor: use YAML plan with delimiter in KCLVM Rust ver

- kclvm/runtime/src/api/kclvm.rs
- kclvm/runtime/src/value/api.rs
[kclvm/runtime/src/api/kclvm.rs](https://github.com/KusionStack/KCLVM/compare/main...NeverRaR:KCLVM:kclvm-capi#diff-af622bbbd88b5bc7d70d8f6217dcc04820d00bf4d93b3cc1110f13b14a1702e7)
[kclvm/runtime/src/value/api.rs](https://github.com/KusionStack/KCLVM/compare/main...NeverRaR:KCLVM:kclvm-capi#diff-25902536876e95e5afdc489ad26130292cfda3c8e7ce159b7ea7a3b532a814f9)
fix : memory leak caused by closure
```release-note
None
```
> fix : memory leak caused by closure

- kclvm/tools/src/lint/mod.rs
tools/lint
```release-note
None
```
> Fix: lint docs error

- compiler_base/error/src/diagnostic/components.rs
- compiler_base/error/src/diagnostic/diagnostic_handler.rs
- compiler_base/error/src/diagnostic/diagnostic_message.rs
- compiler_base/error/src/diagnostic/mod.rs
- compiler_base/error/src/diagnostic/tests.rs
- compiler_base/error/src/emitter.rs
- compiler_base/error/src/tests.rs
issue #115
compiler_base
fix warnings by 'cargo clippy'
```release-note
None
```
> refactor(compiler_base): fix warnings by 'cargo clippy' for Compiler_Base.

- README-zh.md
- README.md
refactor: refine links in README due to an update to the KusionStack web page content.
```release-note
None
```
> refactor: refine links in readme.

- compiler_base/Cargo.toml
- compiler_base/session/Cargo.toml
- compiler_base/session/src/lib.rs
- compiler_base/session/src/test_datas/code_snippet
- compiler_base/session/src/test_datas/locales/en-US/default.ftl
- compiler_base/session/src/test_datas/locales/en-US/test/default1.ftl
issue #115
compiler_base_session
add struct `Session` and trait `SessionDiagnostic` in compiler_base_session.
```release-note
None
```
> Feat(compiler_base): add compiler_base_session

- compiler_base/session/src/lib.rs
issue #115
compiler_base_session
make fields in struct `Session` from 'private' to 'public'.
```release-note
None
```
> Refactor(compiler_base): refactor struct `Session`.

- internal/kclvm_py/scripts/requirements.txt
- scripts/build-windows/requirements.release.txt
fix: https://github.com/KusionStack/KCLVM/security/dependabot/42
```release-note
None
```
> chore: bump protobuf deps to 3.19.5

- CODE_OF_CONDUCT.md
Create CODE_OF_CONDUCT.md using the default template.
* CODE_OF_CONDUCT.md
```release-note
None
```
> Create CODE_OF_CONDUCT.md using the default template.

- kclvm/sema/benches/my_benchmark.rs
issue #191.
kclvm-sema
Update outdated bench tests.
```release-note
None
```
> Feat(kclvm-sema): Update outdated bench tests.

- kclvm/compiler/src/codegen/llvm/module.rs
- test/grammar/schema/back_ref/back_ref_1.k
- test/grammar/schema/back_ref/stdout.golden
issue #231
kclvm-codegen
fix schema back reference exception.
```release-note
None
```
> Fix(kclvm-codegen): fix schema back ref.

- .github/workflows/kcl.yml
- .github/workflows/macos_test.yaml
- kclvm/runner/src/command.rs
issue #225
kclvm-runner
add "-Wl, -w" to clang arguments.
```release-note
None
```
> Fix(kclvm-runner): fix linker bug.

- kclvm/version/src/lib.rs
kclvm-version
change check sum from "e07ed7af0d9bd1e86a3131714e4bd20c" to "c5bd1f3a5d6db8c676bafddb6e643660".
```release-note
None
```
> Feat(kclvm-version): change new checksum for new version.

- compiler_base/error/src/diagnostic/diagnostic_handler.rs
- compiler_base/error/src/diagnostic/tests.rs
issue #115
compiler-base-error
make method 'add_err_diagnostic','add_warn_diagnostic','emit_error_diagnostic', 'emit_warn_diagnostic','emit_stashed_diagnostics' and 'abort_if_errors' return `&self`.
```release-note
None
```
> Refactor(compiler-base): refactor method in DiagnosticHandler.

- compiler_base/session/src/lib.rs
- compiler_base/session/src/tests.rs
issue #115
compiler_base_session
add new constructor `new_with_file_and_code` for `Session`.
```release-note
None
```
> Feat(compiler_base_session): add a new contructor to `Session`.

- compiler_base/error/Cargo.toml
- compiler_base/session/Cargo.toml
issue #115
compiler_base
```release-note
None
```
> Update compiler base version

- compiler_base/3rdparty/rustc_errors/Cargo.toml
- compiler_base/3rdparty/rustc_errors/src/styled_buffer.rs
- compiler_base/error/Cargo.toml
- compiler_base/error/src/diagnostic/mod.rs
- compiler_base/error/src/lib.rs
issue #115
compiler-base-error
make StyledBuffer, StyledString pub in compiler-base-error.
```release-note
None
```
> Feat(compiler-base-error): make StyledBuffer, StyledString pub in compiler-base-error.

- compiler_base/error/src/diagnostic/components.rs
- compiler_base/error/src/diagnostic/mod.rs
- compiler_base/error/src/diagnostic/tests.rs
- compiler_base/error/src/emitter.rs
issue #115
compiler-base-error
Implement trait Debug and PartialEq for Diagnostic.
```release-note
None
```
>  Feat(compiler-base-error): Implement trait Debug and PartialEq for Diagnostic.

- kclvm/Cargo.lock
- kclvm/tools/Cargo.toml
- kclvm/tools/src/langserver/find_refs.rs
- kclvm/tools/src/langserver/go_to_def.rs
- kclvm/tools/src/langserver/mod.rs
- kclvm/tools/src/langserver/test_data/inherit.k
- kclvm/tools/src/langserver/test_data/inherit_pkg.k
- kclvm/tools/src/langserver/test_data/test_word_workspace/inherit.k
- kclvm/tools/src/langserver/test_data/test_word_workspace/inherit_pkg.k
- kclvm/tools/src/langserver/test_data/test_word_workspace_map/inherit.k
- kclvm/tools/src/langserver/test_data/test_word_workspace_map/inherit_pkg.k
- kclvm/tools/src/langserver/tests.rs
- kclvm/tools/src/langserver/word_map.rs
- kclvm/tools/src/lib.rs
re #212 
kusionstack/KCLVM/kclvm/tools/src/langserver
see more in [issue212](https://github.com/KusionStack/KCLVM/issues/212)
```release-note
None
```
>  Enhancement(langserver): Add find references api

- kclvm/runtime/src/api/kclvm.rs
- kclvm/runtime/src/api/utils.rs
- kclvm/runtime/src/context/mod.rs
- kclvm/runtime/src/lib.rs
- kclvm/runtime/src/manifests/mod.rs
- kclvm/runtime/src/manifests/tests.rs
- kclvm/runtime/src/manifests/yaml.rs
- kclvm/runtime/src/value/val_yaml.rs
feat: #94 
* Add the runtime function to implement the customized output of YAML stream format manifests. 
* TODO: The corresponding implementation of the KCL UI layer includes function call and runtime impl integration and more UI test suites. @zong-zhe 
* TODO: More yaml encode options to impl. @Peefy 
* unit test suites: kclvm/runtime/src/manifests/yaml.rs
```release-note
None
```
> feat: add manifests.yaml_stream impl at kclvm runtime.

- kclvm/compiler/src/codegen/llvm/node.rs
- kclvm/runner/src/exec_data/lambda_return_undefined.k
fix #280 
kclvm/compiler/src/codegen/llvm/node.rs
[fix : use hoisting to avoid refer to uninitialized variable](https://github.com/KusionStack/KCLVM/commit/7bef9eedece3cc9c3d837c71ea03e3d80666ba02)
```release-note
None
```
> fix : use hoisting to avoid refer to uninitialized variable

- internal/kclvm_py/api/object/decorator.py
- internal/kclvm_py/kcl/types/scope.py
- internal/kclvm_py/vm/code/code.py
- internal/kclvm_py/vm/runtime/evaluator/lazy.py
fix: #296 
All unit and grammar test suites will be executed at `test` folder.
```release-note
None
```
> refactor: use default_factory field in dataclass because it will raise an error on python3.10+

- kclvm/tools/src/format/tests.rs
- kclvm/tools/src/langserver/go_to_def.rs
- kclvm/tools/src/langserver/mod.rs
- kclvm/tools/src/langserver/tests.rs
- kclvm/tools/src/langserver/word_map.rs
- kclvm/tools/src/lint/mod.rs
- kclvm/tools/src/lint/tests.rs
- kclvm/tools/src/util/loader.rs
- kclvm/tools/src/util/tests.rs
- kclvm/tools/src/vet/expr_builder.rs
- kclvm/tools/src/vet/tests.rs
- kclvm/tools/src/vet/validator.rs
re: #191 
All unit tests at kclvm_tools crate.
```release-note
None
```
> refactor: run cargo clippy --fix at the kclvm_tools crate.

- kclvm/sema/src/resolver/arg.rs
- kclvm/sema/src/resolver/node.rs
- kclvm/sema/src/resolver/schema.rs
- kclvm/sema/src/resolver/test_fail_data/unmatched_args.k
- kclvm/sema/src/resolver/tests.rs
re #282 
/kclvm/sema
refactor: add  index check error message in args check
```release-note
None
```
> refactor: add  index check error message in args check

- internal/kclvm_py/scripts/requirements.txt
- internal/kclvm_py/scripts/test_grammar.sh
- scripts/build-windows/requirements.release.txt
> chore: clean kclvm_py pip requirements.

- .github/workflows/macos_test.yaml
- .github/workflows/ubuntu_test.yaml
- internal/scripts/build-kclvm.sh
- internal/scripts/build.sh
- internal/scripts/cli/kcl
- internal/scripts/cli/kcl-doc
- internal/scripts/cli/kcl-fmt
- internal/scripts/cli/kcl-lint
- internal/scripts/cli/kcl-plugin
- internal/scripts/cli/kcl-test
- internal/scripts/cli/kcl-vet
- internal/scripts/cli/kclvm
- internal/scripts/kcllib-install.sh
- internal/scripts/release.sh
- internal/scripts/test.sh
- internal/scripts/test_grammar.sh
- internal/scripts/update-kclvm.sh
- internal/spec/gpyrpc/gpyrpc.proto
- kclvm/capi/build.rs
- kclvm/capi/src/model/gpyrpc.rs
- kclvm/capi/src/service/api.rs
- kclvm/plugin/kclvm_runtime.py
- kclvm/runner/src/command.rs
- run.sh
- scripts/build-windows/Makefile
refactor: polish all scripts to use external kclvm_py through pip in scripts. In addition, kclvm_py will be deleted in other PRs.
```release-note
None
```
> refactor: use external kclvm_py through pip in scripts

- kclvm/runtime/src/value/val_json.rs
- kclvm/runtime/src/value/val_yaml.rs
/kclvm/runtime
fix : encode yaml with opts
The test cases in kclvm/runtime/src/value/val_yaml.rs: test_value_to_yaml_string_with_opts() is used to test encode ValueRef to yaml with opts
```release-note
None
```
> fix : encode yaml with opts

- internal/scripts/update-kclvm.sh
- kclvm/runner/src/command.rs
refactor: remove rust std lib deps in libkclvm release
```release-note
None
```
> refactor: remove rust std lib deps in libkclvm release

- README-zh.md
docs: update README-zh header.
```release-note
None
```
> docs: update README-zh header.

- kclvm/runner/src/exec_err_data/attr_not_found.k
- kclvm/runner/src/exec_err_data/attr_not_found.stderr.json
- kclvm/runner/src/tests.rs
- kclvm/runtime/src/value/api.rs
fix #316 
refactor: enhance panic info in schema
* kclvm/runner/src/exec_err_data/attr_not_found.k
```release-note
None
```
> refactor: enhance panic info in schema

- kclvm/runtime/src/value/val_union.rs
re #193 
kclvm/runtime/src/value/val_union.rs
enhance: config unification conflict value error message. 
When a union conflict occurs, the following error message will be generated:
```
conflicting values on the attribute 'app' between :
1
and
{...}
with union path :
labels.app
try operator '=' to override the attribute, like:
{...} | {
...
app = {...}
...
}
```
test_dict_union_conflict_attr() is used to test error message when the union conflicts.
```release-note
None
```
> enhance: config unification conflict value error message

- kclvm/config/src/cache.rs
- kclvm/runner/build.rs
- kclvm/runner/src/assembler.rs
re #315 
kclvm/config/src/cache.rs
kclvm/runner/build.rs
kclvm/runner/src/assembler.rs
refactor: add build target to cache path
```release-note
None
```
> refactor: add build target to cache path

- README-zh.md
- README.md
- samples/kubernetes.k
…usion stack website and update KCL kubernetes examples.
refactor: update readme content with the kcl website instead of the kusion stack website.
```release-note
None
```
> refactor: update readme content with the kcl website instead of the kusion stack website

- README-zh.md
- README.md
docs: use kcl-lang.io domain and bump kcl-lang.github.io to kcl-lang.io in readme
```release-note
None
```
> docs: bump kcl-lang.github.io to kcl-lang.io

- scripts/build-windows/build.bat
issue #357  
Added the missing kclvm-python in build.bat.
```release-note
None
```
> Fix(kclvm-win): Added the missing kclvm-python in build.bat.

- scripts/docker/kclvm/Dockerfile
fix: https://github.com/KusionStack/kusion/issues/213
```release-note
None
```
> refactor: upgrade kclvm dockerfile ubuntu version

- README.md
- docs/dev_guide/1.about_this_guide.md
chore: bump kcl website links in docs.
```release-note
None
```
> chore: bump kcl website links in docs.

- internal/scripts/update-kclvm.sh
- kclvm/runtime/Cargo.toml
chore: remove unused code in building scripts. There are many useless parts in KCLVM build scripts, which increases the release size. Delete them to reduce the release size.
```release-note
None
```
> chore: remove un-used code in building scripts

- .github/workflows/cla.yml
- .github/workflows/kcl.yml
- .github/workflows/macos_test.yaml
- .github/workflows/release.yaml
- .github/workflows/test_compiler_base.yaml
- .github/workflows/windows_test.yaml
feat: add docker image CD in github actions and format all action YAML files.
```release-note
None
```
> feat: add docker image CD in github actions and format all action YAML files.

- .github/workflows/release.yaml
- README-zh.md
- README.md
feat: image release with release badge.
```release-note
None
```
> feat: image release with release badge.

- scripts/build-windows/kcl-doc.go
- scripts/build-windows/kcl-fmt.go
- scripts/build-windows/kcl-lint.go
- scripts/build-windows/kcl-plugin.go
- scripts/build-windows/kcl-vet.go
- scripts/build-windows/kcl.go
issue #357 
kclvm windows.
Before calling the python version of kclvm in kcl.go check if kclvm is installed. If it is not installed, call pip to install it.
```release-note
None
```
> Feat(kclvm-win): Before calling the python version of kclvm in kcl.go check if kclvm is installed.

- .github/workflows/release.yaml
- kclvm/runner/build.rs
refactor: release github action and fix docker login in the release CI.
```release-note
None
```
> refactor: release github action.

- scripts/docker/kclvm/Dockerfile
fix: kcl docker image release in action. Action Ref: https://github.com/KusionStack/KCLVM/actions/runs/3883287070/jobs/6624417496
```release-note
None
```
> fix: kcl docker image release in action

- docs/dev_guide/2.quick_start.md
- internal/scripts/build-kclvm.sh
- kclvm/README.md
docs: update developing guide about windows and building scripts.
```release-note
None
```
> docs: update developing guide about windows and building scripts.

- kclvm/sema/src/resolver/node.rs
- kclvm/sema/src/resolver/test_fail_data/module_optional_select.k
- kclvm/sema/src/resolver/tests.rs
fix: #337 fix: module type optional chain error message.
```release-note
None
```
> fix: module type optional chain error message.

- kclvm/Cargo.lock
- kclvm/Cargo.toml
- kclvm/ast/Cargo.toml
- kclvm/ast_pretty/Cargo.toml
- kclvm/capi/Cargo.toml
- kclvm/compiler/Cargo.toml
- kclvm/config/Cargo.toml
- kclvm/error/Cargo.toml
- kclvm/lexer/Cargo.toml
- kclvm/macros/Cargo.toml
- kclvm/parser/Cargo.toml
- kclvm/query/Cargo.toml
- kclvm/runner/Cargo.toml
- kclvm/runtime/Cargo.toml
- kclvm/runtime/internal_macros/Cargo.toml
- kclvm/sema/Cargo.toml
- kclvm/span/Cargo.toml
- kclvm/tests/Cargo.toml
- kclvm/tests/fuzz/Cargo.toml
- kclvm/tools/Cargo.toml
- kclvm/version/Cargo.toml
chore: bump all kclvm crate versions to v0.4.5
```release-note
None
```
> chore: bump all kclvm crate versions to v0.4.5

- kclvm/Cargo.lock
- kclvm/capi/Cargo.toml
- kclvm/capi/src/service/api.rs
- kclvm/cmd/src/run.rs
- kclvm/compiler/Cargo.toml
- kclvm/error/src/diagnostic.rs
- kclvm/error/src/lib.rs
- kclvm/parser/src/bin/load_program.rs
- kclvm/parser/src/bin/parse_file.rs
- kclvm/parser/src/bin/parse_module.rs
- kclvm/parser/src/lib.rs
- kclvm/parser/src/parser/stmt.rs
- kclvm/parser/src/parser/tests.rs
- kclvm/parser/src/session/mod.rs
- kclvm/parser/src/tests.rs
- kclvm/runner/src/lib.rs
- kclvm/runtime/src/context/mod.rs
- kclvm/src/lib.rs
- kclvm/tools/src/lint/mod.rs
+ re #57. Reconstruct Parser and error module, and optimize KCL user interface error message of CLI and API.
+ fix #117
+ The parser crate
+ The error crate.
+ kclvm/parser/src/parser/tests.rs
```release-note
None
```
> refactor: kclvm_cli parser error show and panic info.

- kclvm/Cargo.lock
- kclvm/Cargo.toml
- kclvm/config/Cargo.toml
- kclvm/config/src/modfile.rs
- kclvm/parser/Cargo.toml
- kclvm/parser/src/lib.rs
- kclvm/runner/Cargo.toml
- kclvm/runner/src/command.rs
- kclvm/runner/src/lib.rs
- kclvm/utils/Cargo.toml
- kclvm/utils/src/lib.rs
- kclvm/utils/src/path.rs
issue #379 
kclvm-windows.
Provide kclvm-utils to rm the prefix '\\?\' on windows.
```release-note
None
```
> Fix(kclvm-windows): rm all the '\\?\' path prefix in windows.

- .github/workflows/windows_test.yaml
- .gitmodules
- build_and_test_win.bat
- kclvm/runner/src/tests.rs
- test/integration/test_konfig.bat
- test/integration/test_konfig_kcl.py
issue #379  
Add Konfig test for windows.
Konfig - https://github.com/KusionStack/konfig
```release-note
None
```
> Feat(kclvm-windows): Add konfig test for windows.

- .github/workflows/macos_test.yaml
- .github/workflows/ubuntu_test.yaml
- internal/scripts/test.sh
- internal/scripts/test_konfig.sh
- kclvm/makefile
- kclvm/tests/integration/konfig/test_konfig_kcl.py
issue #379 
kclvm-test
add konfig test for kclvm on unix.
```release-note
None
```
> Feat(kclvm-test): add konfig test for kclvm on unix. 

- internal/scripts/update-kclvm.sh
- kclvm/Cargo.lock
- kclvm/Cargo.toml
- kclvm/tools/Cargo.toml
- kclvm/tools/src/LSP/Cargo.toml
- kclvm/tools/src/LSP/src/main.rs
- kclvm/tools/src/util/lsp.rs
- kclvm/tools/src/util/mod.rs
- scripts/build-windows/build.bat
- scripts/build-windows/build_kcl_lsp_server.bat
KCL LSP Server
Build a binary file `kcl-language-server` communicate with the IDE client. And realized the error-check(diagnostics) in LSP server.
- [] Other
1. update kclvm
2. get the ide client: https://github.com/He1pa/vscode-kcl/tree/lsp-rust
3. Run and Debug -> Run Extension
```release-note
None
```
> Feat(LSP): KCL LSP server with error-checking(diagnostics) (#297)

- samples/hello_plugin.k
- scripts/build-windows/build.bat
- scripts/build-windows/build_kclvm_plugin_py.bat
- scripts/build-windows/copy-dir.go
#379 
kclvm-windows
```release-note
None
```
> Fix(kclvm-win): install plugins for win.

- kclvm/cmd/src/lib.rs
- kclvm/cmd/src/lint.rs
- kclvm/cmd/src/run.rs
- kclvm/cmd/src/settings.rs
- kclvm/cmd/src/test_data/settings/kcl.yaml
- kclvm/cmd/src/tests.rs
- kclvm/config/src/settings.rs
- kclvm/makefile
- kclvm/runner/src/lib.rs
- kclvm/runner/src/runner.rs
re #427
refactor: kcl cli work directory setting and add more CLI tests.
```release-note
None
```
> refactor: kcl cli work directory setting and add more CLI tests

- kclvm/plugin/kclvm_runtime.py
- kclvm/runner/src/command.rs
- kclvm/tools/src/LSP/Cargo.toml
re #425 support linker in lib folder and lib path environment set.
+ kclvm/runner/src/tests.rs
```release-note
None
```
> feat: support linker in lib folder

- kclvm/Cargo.lock
- kclvm/cmd/src/run.rs
- kclvm/error/src/lib.rs
- kclvm/parser/Cargo.toml
- kclvm/parser/src/lexer/mod.rs
- kclvm/parser/src/parser/expr.rs
- kclvm/parser/src/parser/mod.rs
- kclvm/parser/src/parser/stmt.rs
- kclvm/parser/src/parser/tests.rs
- kclvm/parser/src/session/mod.rs
- kclvm/parser/src/tests.rs
- kclvm/parser/src/tests/error_recovery.rs
- kclvm/parser/src/tests/snapshots/Makefile
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__config_recovery_0.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__config_recovery_1.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__config_recovery_2.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__config_recovery_3.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__config_recovery_4.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__config_recovery_5.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__list_recovery_0.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__list_recovery_1.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__list_recovery_2.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__list_recovery_3.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__list_recovery_4.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__list_recovery_5.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__paren_recovery_0.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__paren_recovery_1.snap
- kclvm/parser/src/tests/snapshots/mv_new_snapshot.py
re #420.
feat: mismatch delimiter error recovery in parser
+ kclvm/error/src/lib.rs
+ The `kclvm_parser` crate.
+ kclvm/parser/src/tests.rs
```release-note
None
```
> feat: mismatch delimiter error recovery in parser

- kclvm/ast/src/ast.rs
- kclvm/ast/src/token.rs
- kclvm/ast/src/walker.rs
- kclvm/config/src/vfs.rs
- kclvm/runner/build.rs
- kclvm/runtime/internal_macros/src/lib.rs
- kclvm/runtime/src/context/mod.rs
- kclvm/span/src/symbol.rs
- kclvm/tools/src/LSP/Cargo.toml
- kclvm/tools/src/LSP/src/analysis.rs
- kclvm/tools/src/LSP/src/main.rs
- kclvm/tools/src/LSP/src/notification.rs
- kclvm/tools/src/LSP/src/state.rs
- kclvm/tools/src/LSP/src/util.rs
Just fix some clippy warnings
```release-note
None
```
> Style: fix some clippy warnings

- compiler_base/error/Cargo.toml
- compiler_base/error/src/diagnostic/diagnostic_handler.rs
compiler-base-error
```release-note
None
```
> Fix(compiler-base-error): fix method arg type "&mut self" -> "&self".

- compiler_base/error/Cargo.toml
- compiler_base/error/src/diagnostic/diagnostic_handler.rs
- compiler_base/session/Cargo.toml
- compiler_base/session/src/lib.rs
- kclvm/Cargo.lock
- kclvm/Cargo.toml
- kclvm/ast_pretty/Cargo.toml
- kclvm/capi/Cargo.toml
- kclvm/cmd/Cargo.toml
- kclvm/error/Cargo.toml
- kclvm/parser/Cargo.toml
- kclvm/query/Cargo.toml
- kclvm/runner/Cargo.toml
- kclvm/sema/Cargo.toml
- kclvm/tools/Cargo.toml
compiler-base-session
```release-note
None
```
> Feat(compiler-base-session): Add methods to `Session` that emits `Diagnostic` as string.

- kclvm/Cargo.lock
- kclvm/Cargo.toml
- kclvm/cmd/src/lib.rs
- kclvm/cmd/src/settings.rs
- kclvm/config/src/settings.rs
- kclvm/driver/Cargo.toml
- kclvm/driver/src/lib.rs
- kclvm/parser/src/lib.rs
- kclvm/runner/Cargo.toml
- kclvm/runner/src/lib.rs
- kclvm/tools/Cargo.toml
- kclvm/tools/src/LSP/Cargo.toml
- kclvm/tools/src/LSP/src/state.rs
- kclvm/tools/src/util/mod.rs
LSP
Get compile unit. 
Try to get `kcl.yaml` and `settings.yaml`  in `konfig` repo and transfer them into compile files and config when coding in IDE , like python script in konfig .
If got nothing, compile the current coding file
```release-note
None
```
> Feat(LSP): compile uint.

- kclvm/tools/src/LSP/src/capabilities.rs
LSP
Close unimplemented interface to avoid error in IDE
```release-note
None
```
> Feat(LSP): Close unimplemented interface

- kclvm/Cargo.lock
- kclvm/driver/src/lib.rs
- kclvm/parser/src/lib.rs
- kclvm/sema/src/resolver/scope.rs
- kclvm/tools/src/LSP/Cargo.toml
- kclvm/tools/src/LSP/src/db.rs
- kclvm/tools/src/LSP/src/from_lsp.rs
- kclvm/tools/src/LSP/src/notification.rs
- kclvm/tools/src/LSP/src/request.rs
- kclvm/tools/src/LSP/src/state.rs
- kclvm/tools/src/LSP/src/tests.rs
- kclvm/tools/src/LSP/src/util.rs
Update text by range in vfs and compile with source code instead of file path.
LSP
Update text by `DidChangeTextDocumentParams` in LSP vfs, and compile with source code instead of file path in LSP
```release-note
None
```
> Feat(LSP): Support vfs. 

- kclvm/Cargo.lock
- kclvm/runner/src/tests.rs
- kclvm/span/Cargo.toml
- kclvm/span/src/session_globals.rs
feat: add lock in the global session interner for parallel parser.
+ kclvm/runner/src/tests.rs
```release-note
None
```
> feat: add lock in the global session interner for parallel parser.

- internal/scripts/update-kclvm.sh
- kclvm/Cargo.lock
- kclvm/Cargo.toml
- kclvm/cmd/src/lib.rs
- kclvm/src/lib.rs
- kclvm/src/main.rs
- kclvm_cli/Cargo.toml
- kclvm_cli/build.rs
- kclvm_cli/src/main.rs
- scripts/build-windows/build.bat
- scripts/build-windows/build_kclvm_cli.bat
- scripts/build-windows/build_kclvm_dll.bat
Using dynamic linking to generate kclvm_cli in order to reduce binary size
```release-note
None
```
> refactor: using dynamic linking to generate kclvm_cli

- internal/spec/gpyrpc/gpyrpc.proto
- kclvm/Cargo.lock
- kclvm/capi/Cargo.toml
- kclvm/capi/src/api_test.rs
- kclvm/capi/src/model/gpyrpc.rs
- kclvm/capi/src/service/api.rs
- kclvm/capi/src/service/into.rs
- kclvm/capi/src/service/mod.rs
- kclvm/capi/src/service/service.rs
- kclvm/capi/src/service/ty.rs
- kclvm/capi/src/service/util.rs
- kclvm/capi/src/testdata/format-code.json
- kclvm/capi/src/testdata/format-code.response.json
- kclvm/capi/src/testdata/format-path.json
- kclvm/capi/src/testdata/format-path.response.json
- kclvm/capi/src/testdata/get-schema-type-mapping.json
- kclvm/capi/src/testdata/get-schema-type-mapping.response.json
- kclvm/capi/src/testdata/lint-path.json
- kclvm/capi/src/testdata/lint-path.response.json
- kclvm/capi/src/testdata/load-settings-files.json
- kclvm/capi/src/testdata/load-settings-files.response.json
- kclvm/capi/src/testdata/settings/kcl.yaml
- kclvm/capi/src/testdata/test-lint.k
- kclvm/capi/src/testdata/validate-code.json
- kclvm/capi/src/testdata/validate-code.response.json
- kclvm/parser/Cargo.toml
- kclvm/runner/src/lib.rs
- kclvm/runner/src/runner.rs
- kclvm/tools/src/format/mod.rs
- kclvm/tools/src/vet/validator.rs
Closes #387
feat: add more kclvm capis and tests
+ internal/spec/gpyrpc/gpyrpc.proto
+ the `kclvm_capi` crate.
+ kclvm/capi/src/api_test.rs
```release-note
None
```
> feat: add more kclvm capis and tests

- kclvm/Cargo.lock
- kclvm/driver/Cargo.toml
- kclvm/driver/src/lib.rs
- kclvm/tools/src/LSP/src/test_data/diagnostics.k
- kclvm/tools/src/LSP/src/test_data/load_pkg_test.k
- kclvm/tools/src/LSP/src/util.rs
LSP
If the input file of lsp is not in a stack environment, load all kcl files in the dir where the file is located as input
```release-note
None
```
> Feat(LSP):  Load pkg files in LSP

- kclvm/Cargo.lock
- kclvm/api/src/service/service_impl.rs
- kclvm/ast/src/ast.rs
- kclvm/cmd/Cargo.toml
- kclvm/cmd/src/lib.rs
- kclvm/cmd/src/lint.rs
- kclvm/cmd/src/run.rs
- kclvm/cmd/src/settings.rs
- kclvm/cmd/src/tests.rs
- kclvm/config/src/settings.rs
- kclvm/driver/Cargo.toml
- kclvm/driver/src/arguments.rs
- kclvm/driver/src/lib.rs
- kclvm/driver/src/tests.rs
- kclvm/query/src/override.rs
- kclvm/runner/src/lib.rs
- kclvm/runner/src/runner.rs
- kclvm/runner/src/tests.rs
- kclvm/runtime/src/value/val_plan.rs
- kclvm/sema/src/resolver/node.rs
- kclvm/src/lib.rs
feat: impl complete kclvm cli
+ kclvm_cmd crate
+ kclvm_driver crate
+ kclvm_config crate
+ kclvm/driver/src/tests.rs
+ kclvm/runtime/src/value/val_plan.rs
```release-note
None
```
> feat: impl complete kclvm cli

- kclvm/cmd/src/fmt.rs
- kclvm/cmd/src/lib.rs
- kclvm/cmd/src/lint.rs
- kclvm/cmd/src/run.rs
- kclvm/cmd/src/settings.rs
- kclvm/cmd/src/test_data/fmt/test.k
- kclvm/cmd/src/test_data/vet/data.json
- kclvm/cmd/src/test_data/vet/test.k
- kclvm/cmd/src/tests.rs
- kclvm/cmd/src/util.rs
- kclvm/cmd/src/vet.rs
re #365
feat: impl vet and fmt kclvm cli sub commands.
+ The kclvm-cmd crate.
```release-note
None
```
> feat: impl vet and fmt kclvm cli sub commands.

- kclvm/api/src/service/mod.rs
- kclvm/ast/src/ast.rs
- kclvm/cmd/src/lib.rs
- kclvm/parser/src/lib.rs
- kclvm/parser/src/parser/expr.rs
- kclvm/parser/src/parser/stmt.rs
- kclvm/parser/src/tests.rs
- kclvm/runner/src/assembler.rs
- kclvm/runner/src/command.rs
- kclvm/runner/src/lib.rs
- kclvm/runner/src/tests.rs
- kclvm/span/src/session_globals.rs
- kclvm/tools/src/vet/tests.rs
+ refactor: kclvm parser, runner and global session panic catch because the parser error recovery
+ cargo clippy on the kclvm_parser and kclvm_runner crate.
+ All unit test and grammar test cases.
```release-note
None
```
> refactor: kclvm parser, runner and global session panic catch because the parser error recovery

- kclvm/tools/src/LSP/src/capabilities.rs
- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/goto_def.rs
- kclvm/tools/src/LSP/src/hover.rs
- kclvm/tools/src/LSP/src/lib.rs
- kclvm/tools/src/LSP/src/main.rs
- kclvm/tools/src/LSP/src/request.rs
- kclvm/tools/src/LSP/src/test_data/goto_def_test/pkg/schema_def.k
- kclvm/tools/src/LSP/src/tests.rs
LSP
Feat(LSP): Hover. Display a short text(schema doc) describing element(schema) at position
```release-note
None
```
> Feat(LSP): Hover. Display a short text(schema doc) describing element(schema) at position

- .github/workflows/windows_test.yaml
- kclvm/src/lib.rs
- kclvm_cli/src/main.rs
fix : set exitcode in kclvm_cli
```release-note
None
```
> fix : set exitcode in kclvm_cli

- kclvm/driver/src/lib.rs
- kclvm/tools/src/LSP/src/util.rs
- [] N
kclvm/driver
Update the function `lookup_compile_unit_path`. This function takes a file path as input and searches for the nearest "kcl.yaml" file or the nearest "project.yaml" file. If a "kcl.yaml" file is found, it returns the path of the directory containing the file. If a "project.yaml" file is found, it returns the path of the first directory containing a "kcl.yaml" file in that project. If neither of these files are found, it returns an error indicating that the files were not found.
```release-note
None
```
> Fix: fix cannot find metadata in konfig base file. 

- kclvm/cmd/src/settings.rs
- kclvm/cmd/src/util.rs
- kclvm/config/src/vfs.rs
- kclvm/query/src/query.rs
- kclvm/sema/src/ty/mod.rs
re #471
refactor: unify number multiplier type str using the member function.
+ kclvm/query/src/query.rs
```release-note
None
```
> refactor: unify number multiplier type str using the member function.

- kclvm/tools/src/lint/tests.rs
Test. fix lint ut on windows for lint tools
fix ut
```release-note
None
```
> fix lint ut on windows for lint tools

- internal/spec/gpyrpc/gpyrpc.proto
- kclvm/Cargo.lock
- kclvm/Cargo.toml
- kclvm/api/Cargo.toml
- kclvm/api/src/service/capi.rs
- kclvm/api/src/service/jsonrpc.rs
- kclvm/api/src/service/service_impl.rs
- kclvm/api/src/service/util.rs
- kclvm/ast/src/ast.rs
- kclvm/runner/src/lib.rs
- kclvm/runtime/src/value/val_plan.rs
- kclvm/tools/src/format/mod.rs
fix some bug for rpc api
```release-note
None
```
> fix: rpc api

- kclvm/api/src/service/service_impl.rs
- kclvm/cmd/src/run.rs
- kclvm/driver/src/lib.rs
- kclvm/driver/src/tests.rs
- kclvm/error/src/lib.rs
- kclvm/parser/src/lib.rs
- kclvm/parser/src/tests.rs
- kclvm/runner/src/lib.rs
- kclvm/runner/src/tests.rs
- kclvm/sema/src/resolver/scope.rs
- kclvm/tools/src/vet/tests.rs
refactor: refine parse and resolve function error returned and add test cases
+ kclvm_runner crate
+ kclvm_api crate
+ kclvm_driver crate
+ kclvm/driver/src/tests.rs
```release-note
None
```
> refactor: refine parse and resolve function error returned and add test cases

- kclvm/runner/src/command.rs
kclvm/runner/src/command.rs
```release-note
None
```
> fix: find exec and canonicalize to resolve symbolic link

- kclvm/parser/src/parser/stmt.rs
- kclvm/parser/src/tests/error_recovery.rs
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__schema_stmt_recovery_27.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__schema_stmt_recovery_28.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__schema_stmt_recovery_29.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__schema_stmt_recovery_30.snap
feat: add droper/marker for schema stmt for error recovery.
feat: add droper/marker for schema stmt for error recovery.
```release-note
None
```
> feat: add droper/marker for schema stmt for error recovery.

- kclvm/config/src/lib.rs
- kclvm/config/src/modfile.rs
- kclvm/config/src/tests.rs
- kclvm/parser/src/tests.rs
kclvm/config/src/modfile.rs
set "$HOME/.kpm" to the default env KCLVM_VENDOR_HOME.
```release-note
None
```
> feat: set "$HOME/kcl/.kpm" to the default KCLVM_PKG_PATH.

- kclvm/cmd/src/lib.rs
- kclvm/cmd/src/run.rs
- kclvm/cmd/src/tests.rs
- kclvm/error/src/lib.rs
- kclvm/tools/src/vet/tests.rs
feat: add more info for cli
```release-note
None
```
> feat: add more info for cli

- kclvm/tools/src/LSP/src/document_symbol.rs
- kclvm/tools/src/LSP/src/tests.rs
LSP
Present variables and schema attr type in outline
```release-note
None
```
> Feat(LSP): add more detail in outline

- kclvm/Cargo.lock
- kclvm/sema/Cargo.toml
- kclvm/sema/src/resolver/config.rs
- kclvm/sema/src/resolver/doc.rs
- kclvm/sema/src/resolver/global.rs
- kclvm/sema/src/resolver/import.rs
- kclvm/sema/src/resolver/mod.rs
- kclvm/sema/src/resolver/node.rs
- kclvm/sema/src/resolver/schema.rs
- kclvm/sema/src/resolver/scope.rs
- kclvm/sema/src/resolver/test_data/doc.k
- kclvm/sema/src/resolver/test_data/doc.txt
- kclvm/sema/src/resolver/tests.rs
- kclvm/sema/src/resolver/var.rs
- kclvm/sema/src/ty/mod.rs
- kclvm/tools/src/LSP/src/tests.rs
the predecessor work of #458 
- the doc parser: kclvm/sema/src/resolver/doc.rs
- testdata:
- kclvm/sema/src/resolver/test_data/doc.k
- kclvm/sema/src/resolver/test_data/doc.txt
- add `doc` field to the type `kclvm/sema/src/resolver/scope.rs` and `mod.SchemaAttr`:
- kclvm/sema/src/resolver/scope.rs
- kclvm/sema/src/ty/mod.rs
- kclvm/sema/src/resolver/config.rs
- kclvm/sema/src/resolver/global.rs
- kclvm/sema/src/resolver/import.rs
- kclvm/sema/src/resolver/mod.rs
- kclvm/sema/src/resolver/node.rs
- kclvm/sema/src/resolver/schema.rs
- kclvm/sema/src/resolver/scope.rs
- kclvm/sema/src/resolver/var.rs
- kclvm/tools/src/LSP/src/tests.rs
- add doc parser; 
- save the parsed schema summary and attribute description to the scopeObject.doc
Please refer to [Release Notes Language Style …
> add doc parser; parse schema summary and attribute doc to scope object

- kclvm/cmd/src/tests.rs
- kclvm/parser/src/lib.rs
unit test.
```release-note
None
```
> fix: adjust test cases that need to run command to serial execution.

- kclvm/ast_pretty/src/node.rs
- kclvm/query/src/tests.rs
feat: enhance override spec for string ident e.g., `x-y-z`
+ kclvm/query/src/tests.rs
```release-note
None
```
> feat: enhance override spec for string ident e.g., `x-y-z`

- kclvm/lexer/src/lib.rs
- kclvm/lexer/src/tests.rs
- kclvm/parser/src/lexer/tests.rs
fix: <<= token parse.
+ kclvm/lexer/src/lib.rs
+ kclvm/lexer/src/tests.rs
+ kclvm/parser/src/lexer/tests.rs
```release-note
None
```
> fix: <<= token parse.

- kclvm/tools/src/LSP/src/test_data/goto_import_def_test/kcl.mod.lock
- kclvm/tools/src/LSP/src/tests.rs
test
An update to the kpm version caused the kcl.mod.lock file in the test case to be outdated and an error occurred when parsing kcl.mod.lock.
```release-note
None
```
> fix: fix failed test cases and remove useless variable.

- internal/scripts/build.sh
- internal/scripts/python-plugin/build-cpython.sh
- internal/scripts/python-plugin/build-kcl.sh
- internal/scripts/python-plugin/cli/kcl
- internal/scripts/python-plugin/cli/kcl-doc
- internal/scripts/python-plugin/cli/kcl-fmt
- internal/scripts/python-plugin/cli/kcl-lint
- internal/scripts/python-plugin/cli/kcl-plugin
- internal/scripts/python-plugin/cli/kcl-test
- internal/scripts/python-plugin/cli/kcl-vet
- internal/scripts/python-plugin/release.sh
refactor: kcl scripts and bump kclvm to kcl
```release-note
None
```
> refactor: kcl scripts and bump kclvm to kcl

- kclvm/cmd/src/tests.rs
test case
```release-note
None
```
> fix: fix ci, adjust the execution method of the test case to serial execution.

- kclvm/version/src/lib.rs
chore: bump kcl version to 0.5.0-alpha.4.
+ kclvm/version/src/lib.rs
```release-note
None
```
> chore: bump kcl version to 0.5.0-alpha.4.

- README-zh.md
- README.md
docs: move github codespace links to the contributing section.
+ README-zh.md
+ README.md
```release-note
None
```
> docs: move github codespace links to the contributing section.

- .github/workflows/cla.yml
- .github/workflows/macos_test.yaml
> chore: bump cla kcl bot

- .github/workflows/macos_test.yaml
- .github/workflows/ubuntu_test.yaml
- .github/workflows/windows_test.yaml
> feat: update github workflow

- MAINTAINERS
chore: add the maintainer file
+ MAINTAINERS
> chore: add the maintainer file

- ADOPTERS.md
- MAINTAINERS
chore: update maintainers and adopters.
+ ADOPTERS.md
+ MAINTAINERS
> chore: update maintainers and adopters.

- .github/workflows/backport.yaml
ci: add backport action
+ .github/workflows/backport.yaml
> ci: add backport action

- MAINTAINERS
> chore: add more maintainers

- kclvm/parser/src/parser/stmt.rs
- kclvm/parser/src/tests/error_recovery.rs
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__if_stmt_recovery_7.snap
parser
fix endless loop in if stmt error recovery
> bugfix: endless loop in if stmt error recovery

- README-zh.md
- README.md
+ chore: add github download badge
+ README-zh.md
+ README.md
> chore: add github download badge

- kclvm/tools/src/LSP/src/tests.rs
- kclvm/tools/src/LSP/src/to_lsp.rs
> feat: add LSP diagnostic code

- kclvm/runtime/src/value/api.rs
fix: schema check failed error message.
+ All grammar and konfig test cases
> fix: schema check failed error message.

- kclvm/tools/src/LSP/src/capabilities.rs
- kclvm/tools/src/LSP/src/lib.rs
- kclvm/tools/src/LSP/src/main.rs
- kclvm/tools/src/LSP/src/quick_fix.rs
- kclvm/tools/src/LSP/src/request.rs
- kclvm/tools/src/LSP/src/test_data/diagnostics.k
- kclvm/tools/src/LSP/src/test_data/hover_test/hover.k
- kclvm/tools/src/LSP/src/test_data/quick_fix.k
- kclvm/tools/src/LSP/src/tests.rs
> feat: lsp quick fix

- kclvm/parser/src/parser/expr.rs
- kclvm/parser/src/parser/stmt.rs
- kclvm/parser/src/tests/error_recovery.rs
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__lambda_recovery_0.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__lambda_recovery_1.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__lambda_recovery_2.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__lambda_recovery_3.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__lambda_recovery_4.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__lambda_recovery_5.snap
+ feat: add lambda expression and parameter error recovery
+ kclvm/parser/src/parser/expr.rs
+ kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__lambda_recovery_0.snap
+ kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__lambda_recovery_1.snap
+ kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__lambda_recovery_2.snap
+ kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__lambda_recovery_3.snap
+ kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__lambda_recovery_4.snap
+ kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__lambda_recovery_5.snap
> feat: add lambda expression and parameter error recovery

- kclvm/error/src/error.rs
- kclvm/error/src/error_codes/E1001.md
- kclvm/error/src/error_codes/E1002.md
- kclvm/error/src/error_codes/E1003.md
- kclvm/error/src/error_codes/E1I37.md
- kclvm/error/src/error_codes/E2A31.md
- kclvm/error/src/error_codes/E2D34.md
- kclvm/error/src/error_codes/E2F04.md
- kclvm/error/src/error_codes/E2G22.md
- kclvm/error/src/error_codes/E2H13.md
- kclvm/error/src/error_codes/E2L28.md
refactor: sync error with spec. https://kcl-lang.io/docs/reference/lang/error/exception
+ kclvm/error/src/error.rs
> refactor: sync error with spec.

- kclvm/sema/src/builtin/mod.rs
re #694
fix: builtin function `bool` and `str` signatures.
+ kclvm/sema/src/builtin/mod.rs
> fix: builtin function `bool` and `str` signatures.

- kclvm/parser/src/parser/stmt.rs
- kclvm/parser/src/tests/error_recovery.rs
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__joined_string_recovery_7.snap
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__joined_string_recovery_8.snap
fix: joined string format spec parse
> fix: joined string format spec parse

- kclvm/sema/src/lint/LICENSE
- kclvm/sema/src/lint/mod.rs
> chore: add ref and license for lint

- kclvm/sema/src/resolver/global.rs
sema
Remove incorrect semantic checks
> feat: remove unique check in unification stmt

- GOVERNANCE.md
docs: add GOVERNANCE.md to kcl project. Due to the CNCF maintainer governance document: https://contribute.cncf.io/maintainers/governance/
+ GOVERNANCE.md
> docs: add GOVERNANCE.md to kcl project

- README-zh.md
- README.md
> feat: add openssf best practice badge

- MAINTAINERS
chore: update maintainer infoformation
MAINTAINERS
> chore: update maintainer infoformation

- kclvm/runner/src/lib.rs
> fix: rm temp file generated during compilation

- compiler_base/error/src/diagnostic/diagnostic_handler.rs
- kclvm/compiler/src/codegen/llvm/node.rs
- kclvm/runtime/src/value/val_schema.rs
- kclvm/sema/src/resolver/global.rs
- kclvm/tools/src/LSP/src/capabilities.rs
- test/grammar/schema/assign_stmt/assign_stmt_0/main.k
- test/grammar/schema/assign_stmt/assign_stmt_0/stdout.golden
- test/grammar/schema/assign_stmt/assign_stmt_1/main.k
- test/grammar/schema/assign_stmt/assign_stmt_1/stdout.golden
- test/grammar/schema/assign_stmt/assign_stmt_2/main.k
- test/grammar/schema/assign_stmt/assign_stmt_2/stdout.golden
- test/grammar/schema/assign_stmt/assign_stmt_3/main.k
- test/grammar/schema/assign_stmt/assign_stmt_3/stdout.golden
- test/grammar/schema/assign_stmt/assign_stmt_4/main.k
- test/grammar/schema/assign_stmt/assign_stmt_4/stdout.golden
- test/grammar/schema/assign_stmt/assign_stmt_5/main.k
- test/grammar/schema/assign_stmt/assign_stmt_5/stdout.golden
- test/grammar/schema/assign_stmt/assign_stmt_6/main.k
- test/grammar/schema/assign_stmt/assign_stmt_6/stdout.golden
- test/grammar/schema/init/init_nested_schema_1/stdout.golden
- test/grammar/schema/optional_attr/inherit_2/main.k
- test/grammar/schema/optional_attr/inherit_2/stdout.golden
- test/grammar/schema/optional_attr/inherit_3/main.k
- test/grammar/schema/optional_attr/inherit_3/stdout.golden
fix #785 
+ kclvm/runtime/src/value/val_schema.rs
+ test/grammar/schema/assign_stmt/assign_stmt_0/main.k
+ test/grammar/schema/assign_stmt/assign_stmt_1/main.k
+ test/grammar/schema/assign_stmt/assign_stmt_2/main.k
+ test/grammar/schema/assign_stmt/assign_stmt_3/main.k
+ test/grammar/schema/assign_stmt/assign_stmt_4/main.k
+ test/grammar/schema/assign_stmt/assign_stmt_5/main.k
+ test/grammar/schema/assign_stmt/assign_stmt_6/main.k
+ test/grammar/schema/optional_attr/inherit_2/main.k
+ test/grammar/schema/optional_attr/inherit_3/main.k
+ test/grammar/schema/init/init_nested_schema_1/main.k
> fix: assign stmt in schema codegen and runtime value merge.

- kclvm/tools/src/LSP/src/goto_def.rs
- kclvm/tools/src/LSP/src/request.rs
chore: fix wrong comment and naming typo
> chore: fix wrong comment and naming typo

- kclvm/tools/src/LSP/src/completion.rs
lsp completion
Add parentheses when complete function call. e.g.,
```
math.  -> math.exp
```
enhance to
```
math.  -> math.exp()
```
> enhance: enhance lsp completion for function. 

- kclvm/sema/src/ty/mod.rs
- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/tests.rs
Add completion kind(icon in vscode), detail and doc in completion item. Enhance completion label for function
lsp completion
Add completion kind(icon in vscode), detail and doc in completion item. Enhance completion label for function
> feat: enhance lsp completion detail

- kclvm/sema/src/resolver/node.rs
- kclvm/sema/src/resolver/test_data/annotation_check_assignment.k
- kclvm/sema/src/resolver/tests.rs
kclvm/sema/src/resolver/node.rs
> fix: fix type error in assignment with type annotation

- kclvm/sema/src/ty/mod.rs
- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/hover.rs
- kclvm/tools/src/LSP/src/test_data/completion_test/schema/schema.k
- kclvm/tools/src/LSP/src/tests.rs
lsp completion hover
lsp completion for schema param list
> feat: lsp completion for schema param list

- kclvm/tools/src/LSP/src/capabilities.rs
- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/notification.rs
- kclvm/tools/src/LSP/src/test_data/completion_test/assign/completion.k
- kclvm/tools/src/LSP/src/test_data/completion_test/newline/newline.k
lsp completion
completion of trigger newline after brace
> feat: lsp completion of trigger newline after brace

- kclvm/tools/src/LSP/src/completion.rs
fix typo
s/get_doc_completion/get_dot_completion
> chore: fix typo

- kclvm/sema/src/resolver/test_data/attr_ty_check.k
- kclvm/sema/src/resolver/tests.rs
- kclvm/sema/src/resolver/ty.rs
Fixed #135 
kclvm/sema/src/resolver/ty.rs
> Fix: fix type checkout missing when assigning a dict to a schema

- kclvm/cmd/src/tests.rs
- kclvm/config/src/modfile.rs
- kclvm/parser/src/entry.rs
Fixed bug mentioned in #804 
kclvm/config/src/modfile.rs
> fix: rm the error 'conflict kcl.mod file path'

- kclvm/sema/src/builtin/decorator.rs
- kclvm/sema/src/builtin/mod.rs
- kclvm/sema/src/builtin/string.rs
- kclvm/sema/src/builtin/system_module.rs
- kclvm/sema/src/resolver/attr.rs
- kclvm/sema/src/resolver/calculation.rs
- kclvm/sema/src/resolver/config.rs
- kclvm/sema/src/resolver/global.rs
- kclvm/sema/src/resolver/import.rs
- kclvm/sema/src/resolver/mod.rs
- kclvm/sema/src/resolver/node.rs
- kclvm/sema/src/resolver/scope.rs
- kclvm/sema/src/resolver/tests.rs
- kclvm/sema/src/resolver/ty.rs
- kclvm/sema/src/ty/constants.rs
- kclvm/sema/src/ty/constructor.rs
- kclvm/sema/src/ty/context.rs
- kclvm/sema/src/ty/into.rs
- kclvm/sema/src/ty/mod.rs
- kclvm/sema/src/ty/parser.rs
- kclvm/sema/src/ty/tests.rs
- kclvm/sema/src/ty/unify.rs
- kclvm/sema/src/ty/walker.rs
- kclvm/tools/src/LSP/src/goto_def.rs
sema
modify `TypeRef` from Rc<Type> to Arc<Type>
> feat: modify `TypeRef` from Rc<Type> to Arc<Type>

- kclvm/tools/src/LSP/src/find_refs.rs
- kclvm/tools/src/LSP/src/notification.rs
- kclvm/tools/src/LSP/src/state.rs
lsp
use Arc<RwLock<HashMap>> replace hashmap clone for word_index_map to solve lsp performance regression
> fix: use Arc<RwLock<HashMap>> replace hashmap clone for word_index_map

- .github/workflows/macos_test.yaml
- .github/workflows/windows_test.yaml
fix: ci grammar tests using lower python3 versions
+ .github/workflows/macos_test.yaml
> fix: ci grammar tests using lower python3 versions on macos

- kclvm/error/src/lib.rs
- kclvm/parser/src/tests/error_recovery.rs
- kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__config_recovery_15.snap
+ fix: use char index in the compiler error message
+ kclvm/error/src/lib.rs
> fix: use char index in the compiler error message

- kclvm/cmd/src/test_data/cache_test/kcl.mod
- kclvm/cmd/src/test_data/cache_test/main.k
- kclvm/config/src/cache.rs
- kclvm/config/src/testdata/test_cache/kcl.mod
- kclvm/config/src/testdata/test_cache/main.k
- kclvm/config/src/testdata/test_vendor/kcl.mod
- kclvm/config/src/testdata/test_vendor/main.k
- kclvm/config/src/tests.rs
- kclvm/runner/src/assembler.rs
> fix: fix cache invalidation

- kclvm/sema/src/core/symbol.rs
/kclvm/sema/core/symbol.rs
add symbol semantic information api to trait Symbol
> feat: add symbol sema info api

- kclvm/tools/src/LSP/src/tests.rs
use thread sleep to aysnc build word index map
tools/lsp/tests.rs
use thread sleep to aysnc build word index map
> test: fix lsp unit test of find ref.

- kclvm/sema/src/advanced_resolver/mod.rs
- kclvm/sema/src/advanced_resolver/node.rs
- kclvm/sema/src/core/symbol.rs
re #850
feat: impl symbol semantic information injection
> feat: impl symbol semantic information injection

- kclvm/sema/src/advanced_resolver/mod.rs
- kclvm/sema/src/core/global_state.rs
- kclvm/sema/src/core/scope.rs
- kclvm/sema/src/core/semantic_information.rs
re #850
/kclvm/sema/core
feat: support look up cloest symbol
> feat: support look up cloest symbol

- kclvm/parser/src/lexer/tests.rs
> fix: fix failed win test case

- kclvm/Cargo.lock
- kclvm/error/src/diagnostic.rs
- kclvm/error/src/lib.rs
- kclvm/parser/src/entry.rs
- kclvm/parser/src/lib.rs
- kclvm/parser/src/testdata/pkg_not_found/suggestions.k
- kclvm/parser/src/tests.rs
- kclvm/sema/Cargo.toml
- kclvm/sema/src/resolver/import.rs
- kclvm/sema/src/resolver/scope.rs
- kclvm/sema/src/resolver/test_data/pkg_not_found_suggestion.k
- kclvm/sema/src/resolver/tests.rs
- kclvm/tools/src/LSP/src/quick_fix.rs
- kclvm/tools/src/LSP/src/to_lsp.rs
- kclvm/tools/src/lint/tests.rs
kclvm_parser/sema
When KCL fails to find the package during compilation, it outputs some suggestion messages directing to `kpm add` and search on AH.
> feat: add suggestion when package not found

- kclvm/tools/src/LSP/src/notification.rs
- kclvm/tools/src/LSP/src/tests.rs
lsp/notification.rs
lsp/tests.rs
handle cancel request
> feat: Lsp handle cancel req

- kclvm/sema/src/resolver/mod.rs
- kclvm/sema/src/ty/unify.rs
kclvm/sema/
resolver performance improvement
> resolver performance improvement

- .github/workflows/cla.yml
chore: bump cla token to DEPLOY_ACCESS_TOKEN.
+ .github/workflows/cla.yml
> chore: bump cla token to DEPLOY_ACCESS_TOKEN.

- kclvm/sema/src/resolver/node.rs
- kclvm/sema/src/resolver/test_data/undef_lambda_param.k
- kclvm/sema/src/resolver/tests.rs
> bugfix: fix postion of undefined lambda param

- kclvm/sema/src/resolver/config.rs
- kclvm/sema/src/ty/context.rs
re #866 
/kclvm/sema
infer dict attr ty in config entries to imporve the performance of resolver
> perf: infer dict attr ty in config entries

- kclvm/sema/src/advanced_resolver/mod.rs
- kclvm/sema/src/advanced_resolver/node.rs
- kclvm/sema/src/core/global_state.rs
- kclvm/sema/src/core/package.rs
- kclvm/sema/src/core/symbol.rs
- kclvm/sema/src/namer/mod.rs
- kclvm/sema/src/resolver/loop.rs
- kclvm/sema/src/resolver/node.rs
- kclvm/sema/src/resolver/scope.rs
- kclvm/sema/src/resolver/ty.rs
- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/goto_def.rs
- kclvm/tools/src/LSP/src/request.rs
- kclvm/tools/src/LSP/src/tests.rs
lsp/complete.rs
sema/advance_resolver
sema/resolver
> arch: migrate lsp dot_complete to new sema model

- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/tests.rs
tools/lsp/completion.rs
migrate lsp assign(`:` and `=`) value completion to new sema model
> arch: migrate lsp assign(`:` and `=`) value completion to new sema model

- kclvm/sema/src/advanced_resolver/node.rs
- kclvm/sema/src/resolver/loop.rs
- kclvm/sema/src/resolver/node.rs
- kclvm/sema/src/resolver/ty.rs
- kclvm/tools/src/LSP/src/hover.rs
- kclvm/tools/src/LSP/src/request.rs
- kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/tests.rs
> arch: migrate lsp hover to new sema model

- kclvm/sema/src/advanced_resolver/mod.rs
- kclvm/sema/src/core/global_state.rs
- kclvm/sema/src/core/package.rs
- kclvm/sema/src/core/scope.rs
- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/goto_def.rs
kclvm/sema/src/core/global_state.rs
kclvm/sema/src/core/package.rs
kclvm/sema/src/core/scope.rs
kclvm/tools/src/LSP/src/completion.rs
migrate lsp variable and schema attr completion to new sema model
> arch: migrate lsp variable and schema attr completion to new sema model

- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/request.rs
- kclvm/tools/src/LSP/src/test_data/completion_test/newline/docstring_newline.k
- kclvm/tools/src/LSP/src/test_data/completion_test/newline/newline.k
migrate lsp newline complete to new sema model
> arch: migrate lsp newline complete to new sema model

- .gitignore
- kclvm/driver/src/kpm_metadata.rs
- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/request.rs
- kclvm/tools/src/LSP/src/state.rs
- kclvm/tools/src/LSP/src/tests.rs
- kclvm/tools/src/LSP/src/util.rs
feat: add kcl mod metadata fetch for the driver crate
+ kclvm/driver/src/mod_metadata.rs
TODO: `fetch_kpm_metadata` function will be removed at kcl v0.8.0 for the command migration
/// `kpm -> kcl mod`.
> feat: add kcl mod metadata fetch for the driver crate

- kclvm/src/lib.rs
chore: bump error message to stderr
+ kclvm/src/lib.rs
> chore: bump error message to stderr

- kclvm/sema/src/advanced_resolver/node.rs
- kclvm/sema/src/resolver/node.rs
+ fix: add correct ty to quant symbol and argument symbol
> fix: add correct ty to quant symbol and argument symbol

- kclvm/sema/src/resolver/mod.rs
- kclvm/sema/src/resolver/tests.rs
kclvm/sema/src/resolver/mod.rs
feat: use Arc<RefCell<..> to support internal modifications to Cached…
> feat: use Arc<Mutex<..> to support internal modifications to CachedScope

- kclvm/sema/src/advanced_resolver/mod.rs
- kclvm/sema/src/core/scope.rs
fix: use kfile_paths to determine if root scope contains the pos
> fix: use kfile_paths to determine if root scope contains the pos

- kclvm/parser/src/lib.rs
- kclvm/tools/src/LSP/src/find_refs.rs
- kclvm/tools/src/LSP/src/quick_fix.rs
- kclvm/tools/src/LSP/src/rename.rs
- kclvm/tools/src/LSP/src/request.rs
- kclvm/tools/src/LSP/src/state.rs
- kclvm/tools/src/LSP/src/tests.rs
- kclvm/tools/src/LSP/src/util.rs
Add parse cache in lsp state and increment parse in lsp.
> feat: increment parse in lsp

- kclvm/Cargo.lock
- kclvm/api/src/capi_test.rs
- kclvm/api/src/service/capi.rs
- kclvm/api/src/service/jsonrpc.rs
- kclvm/api/src/service/service_impl.rs
- kclvm/api/src/testdata/get-full-schema-type.json
- kclvm/api/src/testdata/get-full-schema-type.response.json
- kclvm/api/src/testdata/get_schema_ty/aaa/kcl.mod
- kclvm/api/src/testdata/get_schema_ty/aaa/main.k
- kclvm/api/src/testdata/get_schema_ty/bbb/kcl.mod
- kclvm/api/src/testdata/get_schema_ty/bbb/main.k
- kclvm/query/Cargo.toml
- kclvm/query/src/query.rs
- kclvm/query/src/test_data/get_schema_ty/aaa/kcl.mod
- kclvm/query/src/test_data/get_schema_ty/aaa/main.k
- kclvm/query/src/test_data/get_schema_ty/bbb/kcl.mod
- kclvm/query/src/test_data/get_schema_ty/bbb/main.k
- kclvm/spec/gpyrpc/gpyrpc.proto
Part of #891 
kclvm/api/src/service/capi.rs
> feat: add api 'get_full_schema_type' to return the schema ty with third party

- kclvm/driver/src/lib.rs
> fix: fix func `get_kcl_files`

- kclvm/compiler/src/codegen/llvm/node.rs
- kclvm/sema/src/resolver/global.rs
- test/grammar/schema/rule/rule_with_index_signature/main.k
- test/grammar/schema/rule/rule_with_index_signature/stdout.golden
feat: support rule statement with index signature
+ kclvm/sema/src/resolver/global.rs
+ test/grammar/schema/rule/rule_with_index_signature/main.k
> feat: support rule statement with index signature

- kclvm/tools/src/LSP/src/completion.rs
> fix: fix lsp completion ut

- kclvm/sema/src/core/symbol.rs
- kclvm/tools/src/LSP/src/find_refs.rs
- kclvm/tools/src/LSP/src/goto_def.rs
- kclvm/tools/src/LSP/src/notification.rs
- kclvm/tools/src/LSP/src/state.rs
- kclvm/tools/src/LSP/src/tests.rs
fix: document url and file path conversation in the language server
fix: attribute typo
+ kclvm/sema/src/core/symbol.rs
+ kclvm/tools/src/LSP/src/find_refs.rs
+ kclvm/tools/src/LSP/src/goto_def.rs
+ kclvm/tools/src/LSP/src/notification.rs
+ kclvm/tools/src/LSP/src/tests.rs
> fix: document url and file path conversation in the language server

- kclvm/driver/src/kpm_metadata.rs
- kclvm/tools/src/LSP/src/completion.rs
+ chore: enhance metadata fetch perf
+ kclvm/driver/src/kpm_metadata.rs
+ kclvm/tools/src/LSP/src/completion.rs
> chore: enhance metadata fetch perf

- kclvm/sema/src/resolver/import.rs
- kclvm/sema/src/resolver/test_data/pkg_asname/pkg/main.k
- kclvm/sema/src/resolver/test_data/pkg_asname/pkg/sub_pkg/main.k
- kclvm/sema/src/resolver/test_data/pkg_asname/pkg_asname.k
- kclvm/sema/src/resolver/tests.rs
fix bug about import pkg with as_name
```
import a as b
a.xxx
```
It should be emit err in resolver, then this error can be checked in lint and IDE.
sema/resolver
> fix: fix import pkg asname check in resolver

- kclvm/sema/src/core/package.rs
- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/test_data/completion_test/assign/completion.k
complete pkg alias name if not none instead of pkg name
> fix: fix completion for pkg alias name

- kclvm/sema/src/advanced_resolver/node.rs
- kclvm/sema/src/core/scope.rs
- kclvm/sema/src/resolver/schema.rs
- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/document_symbol.rs
- kclvm/tools/src/LSP/src/test_data/completion_test/schema/schema_pos/schema_pos.k
fix resolver schema_stmt pos and lsp complete at the end of schema_stmt
fix #824
sema/resolver
sema/advanced_resolver
> fix: fix resolver schema_stmt pos and lsp complete of schema

- kclvm/sema/src/advanced_resolver/node.rs
- kclvm/sema/src/core/symbol.rs
/kcl/sema
fix: add module ty and typealias to symbol
> fix: add module ty and typealias to symbol

- kclvm/ast_pretty/src/node.rs
- kclvm/ast_pretty/src/test_data/lambda.output
- kclvm/tools/src/format/test_data/format_data/lambda.golden
> fix: rm the last newline for the fmt action of lambda expr

- kclvm/config/src/cache.rs
- kclvm/runner/src/assembler.rs
Close #835 
+ kclvm/config/src/cache.rs
+ kclvm/runner/src/assembler.rs
> feat: impl configurable cache path

- kclvm/driver/src/test_data/kpm_metadata_with_line/dep-with-line/kcl.mod
- kclvm/driver/src/test_data/kpm_metadata_with_line/dep-with-line/main.k
- kclvm/driver/src/test_data/kpm_metadata_with_line/main_pkg/kcl.mod
- kclvm/driver/src/test_data/kpm_metadata_with_line/main_pkg/kcl.mod.lock
- kclvm/driver/src/test_data/kpm_metadata_with_line/main_pkg/main.k
- kclvm/driver/src/tests.rs
- kclvm/tools/src/LSP/src/goto_def.rs
- kclvm/tools/src/LSP/src/test_data/goto_def_with_line_test/dep-with-line/kcl.mod
- kclvm/tools/src/LSP/src/test_data/goto_def_with_line_test/dep-with-line/main.k
- kclvm/tools/src/LSP/src/test_data/goto_def_with_line_test/main_pkg/kcl.mod
- kclvm/tools/src/LSP/src/test_data/goto_def_with_line_test/main_pkg/kcl.mod.lock
- kclvm/tools/src/LSP/src/test_data/goto_def_with_line_test/main_pkg/main.k
> feat: add more test cases for goto def with dependencies whose names contain underline

- kclvm/parser/src/lib.rs
- kclvm/tools/src/LSP/src/rename.rs
- kclvm/tools/src/LSP/src/util.rs
> fix: remove useless import

- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/document_symbol.rs
- kclvm/tools/src/LSP/src/find_refs.rs
- kclvm/tools/src/LSP/src/rename.rs
- kclvm/tools/src/LSP/src/request.rs
- kclvm/tools/src/LSP/src/semantic_token.rs
- kclvm/tools/src/LSP/src/util.rs
+ chore: run cargo clippy to fix warnings
> chore: run cargo clippy to fix warnings

- kclvm/sema/src/advanced_resolver/mod.rs
- kclvm/sema/src/advanced_resolver/node.rs
- kclvm/sema/src/core/global_state.rs
- kclvm/sema/src/core/scope.rs
- kclvm/tools/src/LSP/src/completion.rs
Add kind to local scope and use to distinguish different scope types. It is also used to distinguish l/r values in schema expr to provide more accurate completion in lsp.
kclvm/sema/src/advanced_resolver/mod.rs
Add kind to local scope and use to distinguish different scope types. It is also used to distinguish l/r values in schema expr to provide more accurate completion in lsp.
> feat: add kind to local scope

- kclvm/sema/src/advanced_resolver/mod.rs
- kclvm/sema/src/advanced_resolver/node.rs
- kclvm/sema/src/core/symbol.rs
- kclvm/sema/src/namer/mod.rs
- kclvm/sema/src/namer/node.rs
- kclvm/sema/src/resolver/arg.rs
- kclvm/sema/src/resolver/mod.rs
- kclvm/sema/src/resolver/node.rs
- kclvm/sema/src/resolver/schema.rs
- kclvm/sema/src/resolver/scope.rs
- kclvm/sema/src/resolver/ty.rs
/kclvm/sema
Using pkgpath to distinguish the same ast node cached in different packages
> fix: cached ast node key

- kclvm/tools/src/LSP/src/hover.rs
- kclvm/tools/src/LSP/src/test_data/hover_test/import_pkg.k
- kclvm/tools/src/LSP/src/tests.rs
lsp/test.rs
lsp/hover.rs
add some test case
> test: fix lsp test and add import_pkg hover test case

- kclvm/runtime/src/api/utils.rs
- kclvm/runtime/src/context/api.rs
- kclvm/runtime/src/stdlib/plugin.rs
- kclvm/runtime/src/value/api.rs
re #982 
fix: build errors on linux arm64
+ kclvm/runtime/src/api/utils.rs
+ kclvm/runtime/src/stdlib/plugin.rs
> fix: build errors on linux arm64

- kclvm/ast_pretty/src/node.rs
- kclvm/query/src/test_data/import_paths.k
- kclvm/query/src/tests.rs
fix: override str key test cases
+ kclvm/query/src/tests.rs
> fix: override str key test cases

- kclvm/api/src/service/capi.rs
- kclvm/runner/src/runner.rs
- kclvm/runtime/src/_kcl_run.rs
- kclvm/runtime/src/context/api.rs
- kclvm/runtime/src/stdlib/builtin_api.rs
- kclvm/runtime/src/stdlib/plugin.rs
- kclvm/runtime/src/value/api.rs
- kclvm/src/lib.rs
- scripts/docker/kcl-builder-arm64/Dockerfile
fix #982 
fix #985 
+ scripts/docker/kcl-builder-arm64/Dockerfile
+ kclvm/runner/src/runner.rs
+ kclvm/runtime/**
> feat: build kcl linux arm64 with arm64 ubuntu docker image

- kclvm/Cargo.lock
- kclvm/Cargo.toml
- kclvm/api/Cargo.toml
- kclvm/api/src/service/capi.rs
- kclvm/api/src/service/into.rs
- kclvm/api/src/service/jsonrpc.rs
- kclvm/api/src/service/service_impl.rs
- kclvm/ast/src/ast.rs
- kclvm/loader/Cargo.toml
- kclvm/loader/src/lib.rs
- kclvm/parser/src/lib.rs
- kclvm/parser/src/session/mod.rs
- kclvm/runner/src/lib.rs
- kclvm/sema/Cargo.toml
- kclvm/sema/src/core/global_state.rs
- kclvm/sema/src/core/scope.rs
- kclvm/sema/src/core/semantic_information.rs
- kclvm/sema/src/core/symbol.rs
- kclvm/sema/src/namer/mod.rs
- kclvm/sema/src/resolver/scope.rs
- kclvm/spec/gpyrpc/gpyrpc.proto
- kclvm/tools/src/LSP/src/rename.rs
- kclvm/tools/src/LSP/src/util.rs
re #979
+ feat: semantic API for multiple language SDKs
+ kclvm/api/src/service/into.rs
+ kclvm/ast/src/ast.rs
+ kclvm/loader/src/lib.rs
> feat: semantic API for multiple language SDKs

- kclvm/tools/src/LSP/src/tests.rs
+ fix: lsp kcl mod test cases
+ kclvm/tools/src/LSP/src/tests.rs
> fix: lsp kcl mod test cases

- kclvm/lexer/src/number.rs
- kclvm/lexer/src/tests.rs
issue #191 
KCLVM/lexer
Before:
After:
> refactor(lexer): fix warnings by 'cargo clippy' for lexer

- kclvm/error/src/lib.rs
> refactor(error): fix warnings by 'cargo clippy' for error

- kclvm/api/src/service/capi.rs
- kclvm/api/src/service/jsonrpc.rs
- kclvm/api/src/service/service_impl.rs
- kclvm/api/src/service/util.rs
- kclvm/runner/src/lib.rs
- kclvm/runner/src/linker.rs
- kclvm/runner/src/runner.rs
- kclvm/spec/gpyrpc/gpyrpc.proto
feat: impl build_program and exec_artifact APIs
+ kclvm/api/src/service/jsonrpc.rs
+ kclvm/api/src/service/util.rs
+ kclvm/runner/src/lib.rs
+ kclvm/runner/src/linker.rs
+ kclvm/api/src/service/util.rs
+ kclvm/spec/gpyrpc/gpyrpc.proto
> feat: impl build_program and exec_artifact APIs

- kclvm/sema/src/advanced_resolver/node.rs
- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/test_data/completion_test/dot/missing_expr/missing_expr.k
> fix: remove missing expr symbol

- kclvm/ast_pretty/src/test_data/orelse.input
- kclvm/ast_pretty/src/test_data/orelse.output
- kclvm/ast_pretty/src/tests.rs
re #1039 
+ kclvm/ast_pretty/src/tests.rs
+ kclvm/ast_pretty/src/test_data/orelse.input
+ kclvm/ast_pretty/src/test_data/orelse.output
+ kclvm/ast_pretty/src/tests.rs
> test: add orelse AST printer test cases

- kclvm/sema/src/pre_process/identifier.rs
- kclvm/sema/src/pre_process/test_data/raw_identifier.k
- kclvm/sema/src/pre_process/tests.rs
+ fix: raw identifier in the schema string attribute
+ kclvm/sema/src/pre_process/identifier.rs
+ kclvm/sema/src/pre_process/test_data/raw_identifier.k
+ kclvm/sema/src/pre_process/tests.rs
> fix: raw identifier in the schema string attribute

- README-zh.md
- README.md
docs: polish readme documents
+ README-zh.md
+ README.md
> docs: polish readme documents

- .github/workflows/build-test-linux-arm64.yml
- .github/workflows/build-test-macos-arm64.yml
- .github/workflows/daily-release.yaml
- .github/workflows/macos_test.yaml
- .github/workflows/test_compiler_base.yaml
- .github/workflows/ubuntu_test.yaml
- kclvm/api/src/capi_test.rs
- kclvm/makefile
+ chore: bump rust-toolchain to 1.75 in CI
> chore: bump rust-toolchain to 1.75 in CI

- kclvm/lexer/src/kcl_cursor.rs
- kclvm/lexer/src/lib.rs
- kclvm/parser/src/lexer/mod.rs
+ fix: typo in lexer and add error message for the semi token
+ kclvm/lexer/src/kcl_cursor.rs
+ kclvm/parser/src/lexer/mod.rs
+ kclvm/lexer/src/lib.rs
> fix: typo in lexer and add error message for the semi token

- kclvm/api/src/capi_test.rs
- kclvm/api/src/service/service_impl.rs
- kclvm/api/src/testdata/test-validate.json
- kclvm/api/src/testdata/validate-code-file.json
- kclvm/api/src/testdata/validate-code-file.response.json
- kclvm/spec/gpyrpc/gpyrpc.proto
re  https://github.com/kcl-lang/cli/issues/49
add an api `validate_file` to validate the json and yaml file
> feat: add datafile parameter for the  `validate_code` api

- kclvm/sema/src/resolver/node.rs
- test/grammar/types/loop/loop_0/main.k
- test/grammar/types/loop/loop_0/stdout.golden
- test/grammar/types/loop/loop_1/main.k
- test/grammar/types/loop/loop_1/stdout.golden
enhancement: expr context type store in lopp
+ test/grammar/types/loop/loop_0/main.k
+ test/grammar/types/loop/loop_1/main.k
> enhancement: expr context type store in loop expr

- kclvm/sema/src/advanced_resolver/node.rs
- kclvm/sema/src/resolver/config.rs
- kclvm/tools/src/LSP/src/completion.rs
- kclvm/tools/src/LSP/src/test_data/completion_test/schema/schema.k
re #1097 
+ + kclvm/sema/src/advanced_resolver/node.rs
> fix: fix advanced resolver current schema symbol

- kclvm/sema/src/resolver/scope.rs
- kclvm/tools/src/LSP/src/find_refs.rs
- kclvm/tools/src/LSP/src/quick_fix.rs
- kclvm/tools/src/LSP/src/request.rs
- kclvm/tools/src/LSP/src/state.rs
- kclvm/tools/src/LSP/src/tests.rs
- kclvm/tools/src/LSP/src/util.rs
> feat: incremental resolver in lsp

- kclvm/sema/src/resolver/scope.rs
> fix: resolve cache

- kclvm/tools/src/LSP/src/request.rs
> fix resolve cache err in concurreny error in lsp and enhance log message

- .github/workflows/cla.yml
Partof https://github.com/kcl-lang/community/issues/18
> Disable auto block pr option of contributor-assistant/github-action.

- kclvm/tools/src/LSP/src/request.rs
- kclvm/tools/src/LSP/src/state.rs
- kclvm/tools/src/LSP/src/tests.rs
Correct the timing of db locking, remove extra function calls, and avoid repeated compilation to improve efficiency.
kclvm/tools/src/LSP/src/state.rs
> fix: fix lsp db lock

- scripts/docker/kcl/Dockerfile
fix #1155
scripts/docker
add git to the kcl docker image
No test case is needed for this change.
> add git in kcl docker image

- kclvm/tools/src/LSP/src/request.rs
- kclvm/tools/src/LSP/src/state.rs
kclvm/tools/src/LSP/src/state.rs
dead lock cause by
```
process_vfs_changes() -> db.write() (lock) -> compile -> vfs.read() (block)
handle_x_request ()-> vfs.read() (lock)get_db()(block)
```
> fix lsp vfs and db dead lock.

- kclvm/sema/src/advanced_resolver/node.rs
ref https://github.com/kcl-lang/kcl/pull/1175
> fix: advance resolver walk dict comp

- kclvm/tools/src/LSP/src/db.rs
- kclvm/tools/src/LSP/src/error.rs
- kclvm/tools/src/LSP/src/notification.rs
- kclvm/tools/src/LSP/src/request.rs
- kclvm/tools/src/LSP/src/state.rs
If the document is updated during compilation, the current request result will not be response.
kclvm/tools/src/LSP/src/*
> feat: verify request and compile version. 

- .github/workflows/build-test-macos-arm64.yml
+ ci: add setup python scripts in the macos arm CI
+ .github/workflows/build-test-macos-arm64.yml
> ci: add setup python scripts in the macos arm CI

- docs/dev_guide/2.quick_start.md
- docs/dev_guide/3.coding_conventions.md
- docs/dev_guide/4.architecture.md
- docs/dev_guide/5.source_code.md
re #61
+ docs/dev_guide/2.quick_start.md
+ docs/dev_guide/3.coding_conventions.md
+ docs/dev_guide/4.architecture.md
+ docs/dev_guide/5.source_code.md
> docs: add coding covention, arch and source code in the developing guide docs

- kclvm/evaluator/src/context.rs
- kclvm/evaluator/src/lazy.rs
- kclvm/evaluator/src/lib.rs
- kclvm/evaluator/src/node.rs
- kclvm/evaluator/src/schema.rs
- kclvm/evaluator/src/scope.rs
+ feat: add error meta track for the evaluator
+ kclvm/evaluator/src/context.rs
+ kclvm/evaluator/src/lazy.rs
+ kclvm/evaluator/src/lib.rs
> feat: add error meta track for the evaluator

- .github/workflows/windows_test.yaml
- build.ps1
- kclvm/Cargo.toml
- kclvm/compiler/Cargo.toml
- kclvm/compiler/src/codegen/error.rs
- kclvm/compiler/src/codegen/llvm/context.rs
- kclvm/compiler/src/codegen/llvm/emit.rs
- kclvm/compiler/src/codegen/llvm/mod.rs
- kclvm/compiler/src/codegen/mod.rs
- kclvm/makefile
- kclvm/runner/src/assembler.rs
- kclvm/runner/src/tests.rs
- scripts/build-windows/build.ps1
- scripts/build.sh
re #1193 
+ kclvm/Cargo.toml
+ kclvm/compiler/Cargo.toml
+ kclvm/compiler/src/codegen/error.rs
+ kclvm/compiler/src/codegen/llvm/context.rs
+ kclvm/compiler/src/codegen/mod.rs
+ kclvm/runner/src/assembler.rs
+ scripts/build.sh
> feat: add optional llvm feature

- compiler_base/3rdparty/rustc_data_structures/Cargo.toml
- compiler_base/3rdparty/rustc_errors/Cargo.toml
- compiler_base/3rdparty/rustc_errors/src/lib.rs
- compiler_base/3rdparty/rustc_span/Cargo.toml
- compiler_base/Cargo.toml
- compiler_base/error/Cargo.toml
- compiler_base/macros/Cargo.toml
- compiler_base/parallel/Cargo.toml
- compiler_base/session/Cargo.toml
- compiler_base/span/Cargo.toml
- kclvm/Cargo.lock
- kclvm/Cargo.toml
- kclvm/ast/Cargo.toml
- kclvm/ast_pretty/Cargo.toml
- kclvm/cmd/Cargo.toml
- kclvm/error/Cargo.toml
- kclvm/parser/Cargo.toml
- kclvm/parser/src/parser/expr.rs
- kclvm/query/Cargo.toml
- kclvm/runner/Cargo.toml
- kclvm/sema/Cargo.toml
- kclvm/span/Cargo.toml
- kclvm/tools/Cargo.toml
- kclvm/tools/src/LSP/Cargo.toml
> chore: bump compiler_base version

- kclvm/config/src/cache.rs
- kclvm/runner/src/lib.rs
- kclvm/third-party/prost-wkt/wkt-types/src/pbtime.rs
+ chore: deprecated timestamp related code
+ kclvm/config/src/cache.rs
+ kclvm/runner/src/lib.rs
+ kclvm/third-party/prost-wkt/wkt-types/src/pbtime.rs
> chore: deprecated timestamp related code

- kclvm/evaluator/src/schema.rs
- kclvm/runtime/src/api/kclvm.rs
- kclvm/runtime/src/value/api.rs
- kclvm/sema/src/resolver/attr.rs
- test/grammar/schema/instances/complex/complex_5/main.k
- test/grammar/schema/instances/complex/complex_5/pkg/pkg.k
- test/grammar/schema/instances/complex/complex_5/stdout.golden
Close #1177
+ kclvm/evaluator/src/schema.rs
+ kclvm/runtime/src/api/kclvm.rs
+ kclvm/sema/src/resolver/attr.rs
+ test/grammar/schema/instances/complex/complex_5/main.k
> feat: impl schema instances in all package path

- kclvm/Cargo.toml
- kclvm/runner/Cargo.toml
+ feat: add llvm-feature-for-runner
+ kclvm/Cargo.toml
+ kclvm/runner/Cargo.toml
> feat: add llvm-feature-for-runner

- kclvm/Cargo.lock
- kclvm/runtime/Cargo.toml
> chore: bump serde_json version

- kclvm/Cargo.lock
- kclvm/config/Cargo.toml
- kclvm/config/src/path.rs
+ chore: remove pcre2 deps
+ kclvm/config/Cargo.toml
+ kclvm/config/src/path.rs
> chore: remove pcre2 deps

- kclvm/parser/src/parser/expr.rs
- kclvm/parser/src/parser/stmt.rs
+ refactor: enhance stmt parse errors
+ kclvm/parser/src/parser/expr.rs
> refactor: enhance stmt parse errors

- compiler_base/3rdparty/rustc_data_structures/Cargo.toml
- compiler_base/3rdparty/rustc_span/Cargo.toml
- compiler_base/error/Cargo.toml
- compiler_base/session/Cargo.toml
- compiler_base/span/Cargo.toml
- kclvm/Cargo.lock
- kclvm/Cargo.toml
- kclvm/ast/Cargo.toml
- kclvm/ast_pretty/Cargo.toml
- kclvm/cmd/Cargo.toml
- kclvm/error/Cargo.toml
- kclvm/parser/Cargo.toml
- kclvm/query/Cargo.toml
- kclvm/runner/Cargo.toml
- kclvm/sema/Cargo.toml
- kclvm/span/Cargo.toml
- kclvm/tools/Cargo.toml
- kclvm/tools/src/LSP/Cargo.toml
> chore: bump cb version

- kclvm/sema/src/resolver/node.rs
- test/grammar/schema/union/list/schema_2/main.k
- test/grammar/schema/union/list/schema_2/stdout.golden
- test/grammar/schema/union/list/schema_2/temp/temp.k
fix #1229 
fix: schema union in list comprehension
+ test/grammar/schema/union/list/schema_2/main.k
> fix: schema union in list comprehension

- scripts/docker/kcl-builder/Dockerfile
fix #1234
Docker image based on ubuntu for build kcl locally inside docker environment 
Bump ubuntu image from 20.04 to 22.04
> Bump ubuntu base image to 22.04 version

- scripts/docker/kcl-builder-fedora39/Dockerfile
- scripts/docker/kcl-builder-fedora39/Makefile
fix #1240 
kcl-lang/kcl/scripts/docker
Added Dockerfile and Makefile for fedora:39
> [Enhancement] Release fedora:39 linux image

- scripts/docker/kcl-builder-alpine/Dockerfile
- scripts/docker/kcl-builder-alpine/Makefile
fix #1240 
kcl-lang/kcl/scripts/docker
Added Dockerfile and Makefile for alpine linux
> [Enhancement] Release for Alpine linux

- compiler_base/3rdparty/rustc_data_structures/Cargo.toml
- compiler_base/3rdparty/rustc_data_structures/src/lib.rs
- compiler_base/3rdparty/rustc_data_structures/src/temp_dir.rs
- compiler_base/3rdparty/rustc_span/Cargo.toml
- compiler_base/error/Cargo.toml
- compiler_base/session/Cargo.toml
- compiler_base/span/Cargo.toml
- kclvm/Cargo.lock
- kclvm/Cargo.toml
- kclvm/ast_pretty/Cargo.toml
- kclvm/cmd/Cargo.toml
- kclvm/error/Cargo.toml
- kclvm/parser/Cargo.toml
- kclvm/query/Cargo.toml
- kclvm/runner/Cargo.toml
- kclvm/sema/Cargo.toml
- kclvm/tools/Cargo.toml
- kclvm/tools/src/LSP/Cargo.toml
> fix: fix compile fail on windows for rustc_data_structure and bump version

- kclvm/config/src/cache.rs
- kclvm/runner/src/lib.rs
+ fix: build lock using global temp lock
+ kclvm/config/src/cache.rs
+ kclvm/runner/src/lib.rs
> fix: build lock using global temp lock

- kclvm/driver/src/lib.rs
lookup `kcl.yaml` only in current dir.
kclvm/driver/src/lib.rs
> fix: fix lookup_compile_unit_path

- kclvm/query/src/override.rs
- kclvm/query/src/test_data/test_override_file/expect.k
- kclvm/query/src/tests.rs
> feat: supports override identifier for OverrideFile api

- kclvm/query/src/override.rs
- kclvm/query/src/test_data/test_override_file/expect.k
- kclvm/query/src/tests.rs
> fix: trim() the spec for overrideFile()

- kclvm/tools/src/LSP/src/tests.rs
Add a 50ms delay to ensure write locking during compilation
kclvm/tools/src/LSP/src/tests.rs
fix test
> fix: fix lsp e2e test occasionally failed in CI.

- kclvm/compiler/src/codegen/llvm/emit.rs
fix #283 
kcl-lang/kcl/kclvm/compiler/src/codegen/llvm/emit.rs
added `wasm32` llvm target to `emit.rs`.
> feat: add wasm32 llvm target

- kclvm/api/src/service/service_impl.rs
- kclvm/query/src/selector.rs
- kclvm/query/src/test_data/test_list_variables/supported.k
- kclvm/query/src/tests.rs
- kclvm/spec/gpyrpc/gpyrpc.proto
> feat: add type name for schema_expr in list_variables

- kclvm/tools/src/LSP/src/rename.rs
- kclvm/tools/src/LSP/src/test_data/rename_test/rename_on_file/base/person.k
- kclvm/tools/src/LSP/src/test_data/rename_test/rename_on_file/config.k
- kclvm/tools/src/LSP/src/test_data/rename_test/rename_on_file/main.k
- kclvm/tools/src/LSP/src/test_data/rename_test/rename_on_file/pkg/vars.k
- kclvm/tools/src/LSP/src/test_data/rename_test/rename_on_file/server.k
When executing tests concurrently, test_rename_symbol_on_file() will modify the test file, which will affect the results of test_rename() and cause occasionally failures.
kclvm/tools/src/LSP/src/rename.rs
> fix: fix ut test_rename()

- kclvm/query/src/lib.rs
- kclvm/query/src/test_data/test_override_file/expect.k
- kclvm/query/src/tests.rs
> fix: fix format error in OverrideFile

- cli/Cargo.toml
- kclvm/Cargo.lock
- kclvm/Cargo.toml
- kclvm/api/Cargo.toml
- kclvm/api/src/service/service_impl.rs
- kclvm/ast/Cargo.toml
- kclvm/ast_pretty/Cargo.toml
- kclvm/cmd/Cargo.toml
- kclvm/compiler/Cargo.toml
- kclvm/config/Cargo.toml
- kclvm/driver/Cargo.toml
- kclvm/error/Cargo.toml
- kclvm/evaluator/Cargo.toml
- kclvm/lexer/Cargo.toml
- kclvm/loader/Cargo.toml
- kclvm/macros/Cargo.toml
- kclvm/parser/Cargo.toml
- kclvm/query/Cargo.toml
- kclvm/query/src/selector.rs
- kclvm/query/src/tests.rs
- kclvm/runner/Cargo.toml
- kclvm/runtime/Cargo.toml
- kclvm/sema/Cargo.toml
- kclvm/span/Cargo.toml
- kclvm/spec/gpyrpc/gpyrpc.proto
- kclvm/tools/Cargo.toml
- kclvm/tools/src/LSP/Cargo.toml
- kclvm/tools/src/LSP/src/hover.rs
- kclvm/utils/Cargo.toml
- kclvm/version/Cargo.toml
+ chore: bump kcl version to v0.9.0-alpha.2
> chore: bump kcl version to v0.9.0-alpha.2

- kclvm/api/src/service/capi.rs
- kclvm/api/src/service/jsonrpc.rs
- kclvm/api/src/service/service_impl.rs
- kclvm/api/src/testdata/get_schema_ty_under_path/aaa/kcl.mod
- kclvm/api/src/testdata/get_schema_ty_under_path/aaa/main.k
- kclvm/api/src/testdata/get_schema_ty_under_path/aaa/sub/sub.k
- kclvm/api/src/testdata/get_schema_ty_under_path/bbb/kcl.mod
- kclvm/api/src/testdata/get_schema_ty_under_path/bbb/main.k
- kclvm/api/src/testdata/get_schema_ty_under_path/helloworld_0.0.1/README.md
- kclvm/api/src/testdata/get_schema_ty_under_path/helloworld_0.0.1/kcl.mod
- kclvm/api/src/testdata/get_schema_ty_under_path/helloworld_0.0.1/main.k
- kclvm/spec/gpyrpc/gpyrpc.proto
> feat: add service api GetSchemaTypeMappingUnderPath

- .github/workflows/macos_test.yaml
> fix: rm macos-12 env in release github action

- .github/workflows/macos_test.yaml
- .github/workflows/ubuntu_test.yaml
- .github/workflows/windows_test.yaml
- kclvm/Cargo.lock
- kclvm/config/Cargo.toml
- kclvm/config/src/modfile.rs
- kclvm/driver/src/client/mod.rs
- kclvm/driver/src/test_data/kpm_metadata/kcl.mod
- kclvm/driver/src/test_data/kpm_metadata/kcl.mod.lock
- kclvm/driver/src/test_data/kpm_metadata_with_line/main_pkg/kcl.mod.lock
- kclvm/driver/src/tests.rs
- kclvm/driver/src/toolchain.rs
- kclvm/tools/src/LSP/src/state.rs
- kclvm/tools/src/LSP/src/test_data/completion_test/import/external/external_1/kcl.mod
- kclvm/tools/src/LSP/src/tests.rs
chore: bump kcl version in github action
remove the lsp watcher feature
fix ut
> fix: fix lsp watcher

- compiler_base/makefile
- kclvm/makefile
> CI: lock cargo_llvm_cov version

- kclvm/tools/src/LSP/src/state.rs
> fix: handle error when lsp watch init failed

- kclvm/runtime/src/net/mod.rs
fix #1899
kclvm/runtime/src/net
If `None`passed in arguments, returns `None`.
Fixes the handling of IPv6 address literals.
Adds more input validation.
...Modulo bug-dependency.
> Fix net spit and join functions

- kclvm/Cargo.lock
- kclvm/driver/Cargo.toml
- kclvm/driver/src/client/mod.rs
- kclvm/driver/src/client/oci.rs
`oras-project/rust-oci-client` is the new home of `krustlet/oci-distribution`,  the new crate name is `oci-client`, this PR just change the name and it's 1:1 replacement for the current version.
detail:
- https://github.com/oras-project/rust-oci-client/issues/142
> chore: change oci-distribution to new crate name:oci-client

- README-zh.md
- README.md
> feat: add a deepwiki doc reference

- .github/workflows/wasm_test.yaml
- docs/dev_guide/2.quick_start.md
- kclvm/makefile
> chore: bump wasm32-wasi to wasm32-wasip1
