kcl-lang/kcl

.github/workflows/github-actions.yaml
.gitignore
internal/kclvm_py/__main__.py
internal/kclvm_py/api/version/__main__.py
internal/kclvm_py/internal/kclx/__main__.py
internal/kclvm_py/program/rpc-server/__main__.py
internal/kclvm_py/tools/docs/__main__.py
internal/kclvm_py/tools/format/__main__.py
internal/kclvm_py/tools/lint/lint/__main__.py
internal/kclvm_py/tools/plugin/__main__.py
internal/kclvm_py/tools/validation/__main__.py

Purpose:
1. add kcl plugin submodule

feat: add plugins submodule.

---

kclvm/sema/src/ty/mod.rs

Purpose:
1. refactor some documents on the schema type in the sema crate.

refactor: refine some code and comments in the sema crate.

---

kclvm/Cargo.lock
kclvm/Cargo.toml
kclvm/config/Cargo.lock
kclvm/error/src/lib.rs
kclvm/parser/Cargo.lock
kclvm/runner/Cargo.lock
kclvm/sema/Cargo.lock
kclvm/sema/src/resolver/mod.rs
kclvm/sema/src/resolver/scope.rs
kclvm/src/lib.rs
kclvm/src/main.rs

Note:
1. This is just a temporary adjustment when the kclvm exception
throwing mechanism is not completed, and there will be a new
solution to replace it soon.
What:
1. Change the process of kclvm resolver "finding errors and kill the kclvm
process in kclvm resolver" to "finding and collecting errors in kclvm
resolver, and return the errors to the main method for warning".
Do not kill the kclvm process.
How:
1. Removed the call to method 'handler.abort_if_any_errors()' in method
'kclvm_sema.resolver.resolve_program'.
2. Add 'diagnostics: IndexSet<Diagnostic>' to 'struct ProgramScope' and
set the value for 'diagnostics' in method 'kclvm_sema.resolver.resolve_program'.
3. Add method 'check_scope_diagnostics' and call it in method 'main'.
Why:
1. The development of kcl-vet relies on the …

refactor: a temporary adjustment for aborting after error in kclvm-sema.

---

kclvm/ast/src/ast.rs
kclvm/ast/src/lib.rs
kclvm/ast/src/tests.rs
kclvm/config/Cargo.lock
kclvm/parser/Cargo.lock
kclvm/parser/src/parser/expr.rs
kclvm/parser/src/parser/mod.rs
kclvm/parser/src/parser/stmt.rs
kclvm/parser/src/parser/ty.rs
kclvm/runner/Cargo.lock
kclvm/runtime/Cargo.lock
kclvm/sema/Cargo.lock
kclvm/src/lib.rs

refactor: adjusted some macros in kclvm-parser and add some methods in kclvm-ast
Note:
1. Adjusted the position of some macros in kclvm-parser.
What:
1. Move some util macros for ast from kclvm-parser to kclvm-ast,
and add some new util methods in kclvm-ast.
How:
1. Move macros "node_ref", "expr_as" and "stmt_as" form from
kclvm-parser/mod.rs to kclvm-ast/lib.rs
2. Add method "build_assign_node" in kclvm-ast/lib.rs in order to
construct an AssignStmt
3. Add method "filter_schema_stmt_from_module" in kclvm-ast/ast.rs
in order to select all "SchemaStmt" in "Module".
4. Add method "TryFrom<...>" in kclvm-ast/ast.rs for "StringLit" and
"NameConstant" in order to convert from rust string and bool to
kclvm ast.
Why:
1. Adjust the structure of the kclvm-ast and add some util methods to …

refactor: adjusted some macros in kclvm-parser and add some methods in kclvm-ast

---

internal/kclvm_py/program/exec/runner.py
kclvm/src/lib.rs

- catch compiler panic error in kclvm_cli_run
- add 'KCLVM_TARGET' env for target command line option

Fix rest api compiler err

---

kclvm/sema/src/pre_process/config.rs
kclvm/sema/src/ty/mod.rs

Purpose:
Why:
Compile-time configuration merging does not consider scenarios where identifier keys and string keys are the same, such as the following KCL code:
```kcl
schema Config:
labels?: {str:str}
config: Config {
labels.key1 = "value1"
"labels": {
"key2" = "value2"
}
}
```

fix: string key node unify in the config.

---

kclvm/error/src/emitter.rs
kclvm/error/src/lib.rs
kclvm/sema/src/resolver/mod.rs
kclvm/sema/src/resolver/scope.rs
kclvm/sema/src/ty/mod.rs
kclvm/src/lib.rs
kclvm/src/main.rs

Note:
1. kclvm-error.alert_if_any_errors will panic.
What:
1. added panic in kclvm-error.alert_if_any_errors.
How:
1. added method “format_diagnostic” in “kclvm-error.Handler” to get the msg for panic.
2. added method "format_diagnostic" in trait "kclvm-error.Emitter" to get the msg for panic.
Why:
1. The error in resolver that needs to be thrown through panic.
- With pull requests:
- Open your pull request against `main`
- Your pull request should have no more than two commits, if not you should squash them.
- It should pass all tests in the available continuous integration systems such as GitHub Actions.
- You should add/modify tests to cover your proposed code changes.
- If your pull request contains a new feature, please document it on the README.

refactor: modify error output.

---

kclvm/ast/src/ast.rs
kclvm/parser/src/parser/expr.rs
kclvm/parser/src/parser/stmt.rs
kclvm/parser/src/session/mod.rs
kclvm/parser/src/tests.rs

fix: the panic output information of "invalid binary operation" is formatted using PanicInfo.
1. call the method "struct_token_error" in "do_parse_simple_expr" to format the panic message.
2. add method "supported_xx()" in ast.BinOp, ast.CmpOp and ast.BinOrCmpOp for easy access to the supported operations list.
3. adjusted the parameter type of method "struct_token_error" to fit the return value of method "supported_xx()".
4. add test case.
- With pull requests:
- Open your pull request against `main`
- Your pull request should have no more than two commits, if not you should squash them.
- It should pass all tests in the available continuous integration systems such as GitHub Actions.
- You should add/modify tests to cover your proposed code changes.
- If your pull request contains a new …

fix: the panic output information of "invalid binary operation" is formatted using PanicInfo.

---

kclvm/parser/src/lexer/mod.rs
kclvm/parser/src/tests.rs

fix: fix an array out of bounds issue in parser/src/lexer/lex_token()
1. add method ”has_next_token()“ in parser/src/lexer/Lexer to to check 
if an array is out of bounds.

fix: fix an array out of bounds issue in parser/src/lexer/lex_token()

---

kclvm/sema/src/pre_process/mod.rs
kclvm/sema/src/pre_process/tests.rs

Purpose:
1. refactor main pkg import lookup rules

refactor: modify main pkg front import.

---

kclvm/parser/src/parser/expr.rs
kclvm/parser/src/tests.rs

1. kclvm/parser/src/test.rs, 
2. kclvm/parser/src/parser/expr.rs
1. call the method "struct_token_error" in "parse_num_expr" to format the panic message.
2. add and refactor the test case, merged "test_parse_expr_invalid_binary_expr" and "test_parse_expr_invalid_arr_out_of_bound_for_token_minus" into "test_parse_expr_invalid".
- N
- Y, https://github.com/KusionStack/KCLVM/issues/44

fix: the panic output information of "invalid number" is formatted using PanicInfo.

---

.github/workflows/github-actions.yaml
.gitignore
kclvm/Cargo.lock
kclvm/Cargo.toml
kclvm/makefile
scripts/build-windows/Makefile

#50 Enahcne the rust code ci test and output code coverage.
Since KCLVM rust completely changed the workspace mode compilation, the path of the runtime library compilation has changed, and the windows compilation script needs to be adjusted.
CI test integration
```release-note
None
```

feat: add rust code coverage in makefile and github actions.

---

kclvm/sema/src/resolver/mod.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/test_fail_data/config_expr.k
kclvm/sema/src/resolver/tests.rs

fix #90 
The test case in kclvm/sema/src/resolver/test_fail_data/config_expr.k is used to test config_expr type check error.
```release-note
None
```

fix: issue #90 on config_expr type infer.

---

kclvm/sema/src/resolver/global.rs
kclvm/sema/src/resolver/import.rs
kclvm/sema/src/resolver/test_fail_data/cannot_find_module.k
kclvm/sema/src/resolver/tests.rs

sema/resolver/global.rs
sema/resolver/import.rs
There is an incorrect position of ConnotFindModule Error. When a CannotFindModule error is triggered (e.g., importing a non-existent file), the error message is indicated at x:2(line: x and column: 2), but by convention it should be x:1 or just line x. Now fix it to just output the line number.
```
KCL Error [CannotFindModule]
---> File ./test.k:1
1 |import non_existent_file
```
```release-note
None
```

Fix(resolver): fix incorrect position info of CannotFindModule Error.

---

kclvm/runner/src/exec_data/complex.k
kclvm/sema/src/resolver/attr.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/test_fail_data/attr.k
kclvm/sema/src/resolver/tests.rs

[Enhancement] #99 
KCLVM Resolver Related Files:
* kclvm/sema/src/resolver/node.rs
* kclvm/sema/src/resolver/attr.rs
See #99, the error messages are improved
* `test_resolve_program_illegal_attr_fail` in `kclvm/sema/src/resolver/tests.rs`
```release-note
None
```

Refine illegal attr ty err msg

---

kclvm/compiler_base/3rdparty/rustc_errors/Cargo.toml
kclvm/compiler_base/3rdparty/rustc_errors/src/LICENSE
kclvm/compiler_base/3rdparty/rustc_errors/src/README.md
kclvm/compiler_base/3rdparty/rustc_errors/src/lib.rs
kclvm/compiler_base/3rdparty/rustc_errors/src/styled_buffer.rs
kclvm/compiler_base/Cargo.toml
kclvm/compiler_base/src/lib.rs

issue #115
compiler_base/3rdparty/rustc_errors
compiler_base/3rdparty/rustc_span
This is the first step for Compiler-Base-Error in issue https://github.com/KusionStack/KCLVM/issues/115.
Reuse 'styled_buffer.rs' in 'rustc_errors', and 'styled_buffer.rs' has been modified to fit the feature of 'Compiler-Base'.
- Add method 'appendl()' and 'putl()' to 'StyledBuffer',they can adjust the line and column in the 'StyleBuffer' according to the length of the input string.
- Replaced the 'enum Style' with 'trait Style' in 'StyledBuffer' to support extending more styles. And 'trait Style' is defined in compiler_base/3rdparty/rustc_errors/src/lib.rs.
- Add some test cases for 'StyledBuffer'.
- Add 'LICENSE' and 'README.md' in compiler_base/3rdparty/rustc_errors/src/ for reusing rustc source code.
The …

Feat(compiler-base-error): reuse rustc_error 'StyledBuffer' in compiler-base.

---

kclvm/compiler_base/3rdparty/rustc_data_structures/Cargo.toml
kclvm/compiler_base/3rdparty/rustc_data_structures/src/LICENSE
kclvm/compiler_base/3rdparty/rustc_data_structures/src/atomic_ref.rs
kclvm/compiler_base/3rdparty/rustc_data_structures/src/base_n.rs
kclvm/compiler_base/3rdparty/rustc_data_structures/src/captures.rs
kclvm/compiler_base/3rdparty/rustc_data_structures/src/flock.rs
kclvm/compiler_base/3rdparty/rustc_data_structures/src/frozen.rs
kclvm/compiler_base/3rdparty/rustc_data_structures/src/fx.rs
kclvm/compiler_base/3rdparty/rustc_data_structures/src/lib.rs
kclvm/compiler_base/3rdparty/rustc_data_structures/src/macros.rs
kclvm/compiler_base/3rdparty/rustc_data_structures/src/stable_map.rs
kclvm/compiler_base/3rdparty/rustc_data_structures/src/stable_set.rs
kclvm/compiler_base/3rdparty/rustc_data_structures/src/stack.rs
kclvm/compiler_base/3rdparty/rustc_data_structures/src/sync.rs
kclvm/compiler_base/3rdparty/rustc_data_structures/src/temp_dir.rs
kclvm/compiler_base/3rdparty/rustc_data_structures/src/unhash.rs
kclvm/compiler_base/3rdparty/rustc_span/Cargo.toml
kclvm/compiler_base/3rdparty/rustc_span/src/LICENSE
kclvm/compiler_base/3rdparty/rustc_span/src/README.md
kclvm/compiler_base/3rdparty/rustc_span/src/analyze_source_file.rs
kclvm/compiler_base/3rdparty/rustc_span/src/caching_source_map_view.rs
kclvm/compiler_base/3rdparty/rustc_span/src/fatal_error.rs
kclvm/compiler_base/3rdparty/rustc_span/src/lib.rs
kclvm/compiler_base/3rdparty/rustc_span/src/source_map.rs
kclvm/compiler_base/3rdparty/rustc_span/src/span_encoding.rs
kclvm/compiler_base/span/Cargo.toml
kclvm/compiler_base/span/src/lib.rs
kclvm/compiler_base/span/src/span.rs

issue #115
kclvm/compiler_base/3rdparty/rustc_span
kclvm/compiler_base/3rdparty/rustc_data_structures
kclvm/compiler_base/span
1. 'Compiler-Base' decides to reuse 'rustc_span' to describe code snippets and the location of code elements in the file.
2.  'rustc_span' depends on 'rustc_data_structure', so we need to copy the code of these two parts at the same time.
3. copy -r '3rdparty/rustc_span' and '3rdparty/rustc_data_structure' from 'kclvm' to 'kclvm/compiler_base'.
4. add 'span' in 'kclvm/compiler_base' to pub use some parts of '3rdparty/rustc_span'.
At present, the ''rustc_span'' and 'rustc_data_structure' are not used and tested separately. In the future, the methods will be individually provided according to the parts used, and tests will be provided together.
Please refer to …

Feat(compiler-base): reuse 'rustc_span' for code location.

---

kclvm/compiler_base/error/src/diagnostic/components.rs
kclvm/compiler_base/macros/Cargo.toml
kclvm/compiler_base/macros/src/bug.rs
kclvm/compiler_base/macros/src/lib.rs
kclvm/compiler_base/macros/src/tests.rs
kclvm/compiler_base/span/Cargo.toml

issue #115
compiler_base/macros/bug.rs
init crate 'macros' in compiler_base.
reuse bug macro 'bug!()' in compiler_base/macros/src/bug.rs.
add test cases for 'bug!()' in compiler_base/macros/src/tests.rs.
compiler_base/macros/tests.rs
```release-note
None
```

Feat(compiler-base): reuse kclvm bug macro.

---

kclvm/compiler_base/error/src/diagnostic/components.rs
kclvm/compiler_base/error/src/diagnostic/mod.rs

issue #115
compiler_base/error/diagnostic
Replaced `DiagnosticStyle` in `trait Component` with generic `T: Clone + PartialEq + Eq + Style`, So that `Components` can support more Styles.
compiler_base/error/diagnostic/tests.rs
```release-note
None
```

Refactor(compiler-base): Replaced `DiagnosticStyle` in `trait Component` with generic `T: Clone + PartialEq + Eq + Style`.

---

kclvm/error/src/diagnostic.rs
kclvm/error/src/error.rs
kclvm/error/src/lib.rs

Add warning kind diagnostics to build kclvm warning.
error/src/error.rs
error/src/diagnostic.rs
error/src/lib.rs
add doc test in error/src/lib.rs
```release-note
None
```

Feat: add warning kind diagnostic

---

kclvm/sema/src/resolver/test_data/record_used_module.k
kclvm/sema/src/resolver/var.rs

sema/resolver/var.rs
Fix bug in resolve_var(). When enter child scope,  e.g., in a schema scope, cant find module object.
It should be  recursively search whole scope to lookup module object, not the current scope.element.
```release-note
None
```

Fix: Record used module

---

internal/kclvm_py/kcl/types/checker.py
kclvm/sema/src/resolver/global.rs
test/grammar/unification/pkg_schema_0/main.k
test/grammar/unification/pkg_schema_0/pkg/pkg.k
test/grammar/unification/pkg_schema_0/stdout.golden
test/grammar/unification/pkg_schema_1/main.k
test/grammar/unification/pkg_schema_1/pkg/pkg.k
test/grammar/unification/pkg_schema_1/pkg/pkg/pkg.k
test/grammar/unification/pkg_schema_1/stdout.golden

fix: https://github.com/KusionStack/konfig/issues/28
test cases at
* test/grammar/unification/pkg_schema_0
* test/grammar/unification/pkg_schema_1
```release-note
None
```

fix: unification statement resolve with package schema.

---

kclvm/ast/src/walker.rs
kclvm/sema/src/lib.rs
kclvm/sema/src/lint/combinedlintpass.rs
kclvm/sema/src/lint/lint.rs
kclvm/sema/src/lint/lintpass.rs
kclvm/sema/src/lint/lints_def.rs
kclvm/sema/src/lint/mod.rs
kclvm/sema/src/resolver/mod.rs
kclvm/sema/src/resolver/test_data/lint.k
kclvm/sema/src/resolver/tests.rs

sema/lint
sema/resolver
ast/walker
Add Lint check in resolver. Main changes are:
1. mode.rs: Definition of `Linter`, the entry for lint check
2. combinedlintpass.rs: `CombinedLintPass` collects all the lints defined in the lints_def.rs
3. lints_def.rs: Defined the various lints and the corresponding lintpasses implementation
4. lintpass.rs: Definition of `Lintpass`
5. lint.rs: Definition of `Lint`
6. resolver/mode.rs: Call `lint_check_module` when recursively check the ast, and call `lint_check_scope` after check
```release-note
None
```

Refactor: KCL Lint(Rust ver.)

---

kclvm/compiler_base/3rdparty/rustc_errors/Cargo.toml
kclvm/compiler_base/3rdparty/rustc_errors/src/README.md
kclvm/compiler_base/3rdparty/rustc_errors/src/lib.rs
kclvm/compiler_base/3rdparty/rustc_errors/src/lock.rs
kclvm/compiler_base/error/Cargo.toml
kclvm/compiler_base/error/src/diagnostic/components.rs
kclvm/compiler_base/error/src/diagnostic/mod.rs
kclvm/compiler_base/error/src/emitter.rs
kclvm/compiler_base/error/src/lib.rs

issue #115
compiler_base/error/emitter.rs
deleted method `apply_style()`, `Style` provides method `render_style_to_color_spec()` to replace it.
Adapted trait `Emitter` for `Diagnostic` and `StyledBuffer`.
```release-note
None
```

Feat(Compiler-Base): Reuse kclvm emitter

---

kclvm/src/main.rs
kclvm/tools/src/lib.rs
kclvm/tools/src/lint/mod.rs
kclvm/tools/src/lint/test_data/lint.k
kclvm/tools/src/lint/tests.rs

main.rs
add `kclvm_cli lint` command to call resolver lint check and skip runtime
```release-note
None
```

Feat: add `kclvm_cli lint` command to kclvm_cli

---

internal/kclvm_py/program/rpc-server/__main__.py
kclvm/parser/src/lib.rs
kclvm/runner/src/assembler.rs
kclvm/runner/src/command.rs
kclvm/runner/src/lib.rs
kclvm/runner/src/runner.rs
kclvm/tools/src/query/override.rs
kclvm/tools/src/query/tests.rs

[internal/kclvm_py/program/rpc-server/__main__.py](https://github.com/KusionStack/KCLVM/compare/main...NeverRaR:kclvm-capi-call?expand=1#diff-d016e24205d8f09eb8adadb518be3e03f5d7aa1fd5ba603d4985ec62d93f2742)
[kclvm/parser/src/lib.rs](https://github.com/KusionStack/KCLVM/compare/main...NeverRaR:kclvm-capi-call?expand=1#diff-ba434fced40c597ac8bd41c95c419fab357d264146faa07df7c13705cb07b7a0)
[kclvm/runner/](https://github.com/KusionStack/KCLVM/compare/main...NeverRaR:kclvm-capi-call?expand=1#diff-acc0da0c19c5067b64957a333489d0861dc38db6e6043fb9434eb308e16c78c5)
[kclvm/tools/src/query/](https://github.com/KusionStack/KCLVM/compare/main...NeverRaR:kclvm-capi-call?expand=1#diff-acea289240767340d5c908ae46b3c58d6a75262c74e16bfb9895fb66bc31a92a)
[refactor: enhance kclvm runner error …

Kclvm capi call

---

internal/kclvm_py/scripts/build-cpython.sh
internal/kclvm_py/scripts/build-kclvm.sh
internal/kclvm_py/scripts/update-kclvm.sh
kclvm/capi/src/service/service.rs

internal/kclvm_py/scripts/
kclvm/capi/src/service/service.rs
chorm: build kclvm capi lib and cpython shared lib for kclvm
```release-note
None
```

feat: support call kclvm service by go rpc server

---

kclvm/compiler_base/error/src/diagnostic/diagnostic_handler.rs

issue #115 
compiler_base/error
fix some import mistake and remove useless part in diagnostic_builder.rs.
```release-note
None
```

Fix(compiler-base): fix doc string mistakes.

---

kclvm/src/lib.rs
kclvm/tools/src/query/override.rs

#54 Add print_ast parameter on `apply_overrides` function.
```release-note
None
```

feat: add override print args in the exec function.

---

README-zh.md
README.md

Enhance readme with simple how-to-choose
```release-note
None
```

Enhance readme: add how-to-choose

---

compiler_base/3rdparty/rustc_data_structures/Cargo.toml
compiler_base/3rdparty/rustc_data_structures/README.md
compiler_base/3rdparty/rustc_errors/Cargo.toml
compiler_base/3rdparty/rustc_errors/README.md
compiler_base/3rdparty/rustc_span/Cargo.toml
compiler_base/3rdparty/rustc_span/README.md
compiler_base/Cargo.toml
compiler_base/error/Cargo.toml
compiler_base/error/README.md
compiler_base/macros/Cargo.toml
compiler_base/macros/README.md
compiler_base/session/Cargo.toml
compiler_base/session/README.md
compiler_base/span/Cargo.toml
compiler_base/span/README.md

issue #115.
compiler_base
add configurations in Cargo.toml for all crates in compiler_base.
```release-note
None
```

feat(compiler_base): add config for crate.io.

---

compiler_base/error/src/diagnostic/diagnostic_handler.rs

issue #115
compiler_base
The relative path in method `DiagnosticHandler::default()` will cause file-not-found error. Fixed by replacing relative path with abs path.
```release-note
None
```

Fix(compiler_base): fix file path bug in `DiagnosticHandler::default()`.

---

compiler_base/error/Cargo.toml
compiler_base/session/Cargo.toml

issue #115.
compiler_base_session 
compiler_base_error
update versions of compiler_base_session and compiler_base_error in crate.io.
```release-note
None
```

refactor(compiler_base): new version for crate.io

---

kclvm/Cargo.lock
kclvm/runner/Cargo.toml
kclvm/runner/src/assembler.rs
kclvm/runner/src/lib.rs
kclvm/runner/src/tests.rs
kclvm/sema/src/ty/into.rs

fix issue https://github.com/KusionStack/KCLVM/issues/213.
kclvm-runner
The operations of the read and write cache are also wrapped in the file lock.
```release-note
None
```

Fix(kclvm-runner): Fixed file locks in kclvm-runner.

---

kclvm/Cargo.lock
kclvm/tools/Cargo.toml
kclvm/tools/src/util/loader.rs
kclvm/tools/src/util/mod.rs
kclvm/tools/src/util/test_datas/test.json
kclvm/tools/src/util/test_datas/test.yaml
kclvm/tools/src/util/test_datas/test_invalid.json
kclvm/tools/src/util/test_datas/test_invalid.yaml
kclvm/tools/src/util/tests.rs

issue #67.
kclvm-tools/util
add json/yaml file loader for KCL-Vet in kclvm/tools/util.
```release-note
None
```

Feat(kclvm-tools): add json/yaml file loader for KCL-Vet.

---

kclvm/sema/src/pre_process/config.rs
kclvm/sema/src/pre_process/test_data/config_override.k
kclvm/sema/src/pre_process/tests.rs

refactor: enhance config override at compile time when the attribute operator is the override operator `=`.
* kclvm/sema/src/pre_process/config.rs
* kclvm/sema/src/pre_process/tests.rs
```release-note
None
```

refactor: enhance config override at compile time.

---

README-zh.md
README.md

feat: add community link in readme.
* README-zh.md
* README.md
```release-note
None
```

feat: add community link in readme.

---

compiler_base/error/Cargo.toml
compiler_base/session/Cargo.toml
compiler_base/session/src/lib.rs
compiler_base/session/src/tests.rs

issue #115
compiler-base-session
add constructor `new_with_src_code()` to 'Session' for constructing by source code.
add method 'emit_err()' to 'Session' for displaying error diagnostic.
```release-note
None
```

Feat(compiler-base-session): Add some method for 'Session'.

---

compiler_base/3rdparty/rustc_errors/Cargo.toml
compiler_base/3rdparty/rustc_errors/src/styled_buffer.rs

issue #115.
rustc_error
add trait Debug, PartialEq, Eq for StyledBuffer, StyledString and StyledChar.
```release-note
None
```

Feat(rustc_error): add trait Debug, PartialEq, Eq for StyledBuffer, StyledString and StyledChar

---

compiler_base/error/src/diagnostic/diagnostic_handler.rs
compiler_base/error/src/diagnostic/tests.rs

issue #115
compiler-base-error.
impl trait Debug for DiagnosticHandler and DiagnosticHandlerInner.
```release-note
None
```

Feat(compiler-base-error): impl trait Debug for DiagnosticHandler and DiagnosticHandlerInner.

---

compiler_base/session/Cargo.toml
compiler_base/session/src/lib.rs
compiler_base/session/src/tests.rs

issue #115 
compiler-base-session
The old Session provide 'emit_err' which will panic when the diagnostic information is emitted. This situation is very rare in actual usage scenarios, so this PR provides some interfaces for adding errors/warnings, emitting diagnostics, and aborting the program.
'emit_stashed_diagnostics_and_abort' to emit all the diagnostics and abort.
'emit_stashed_diagnostics' to emit all the diagnostics but not abort.
'add_err' to add error to diagnostics.
'add-warn' to add warning to diagnostics.
'diagnostic_count' to get the count of diagnostics.
```release-note
None
```

Feat(compiler-base-session): Add some methods for Session.

---

kclvm/runtime/src/api/kclvm.rs
kclvm/runtime/src/stdlib/builtin.rs
kclvm/runtime/src/value/api.rs
kclvm/runtime/src/value/val.rs
kclvm/runtime/src/value/val_bin.rs
kclvm/runtime/src/value/val_clone.rs
kclvm/runtime/src/value/val_dict.rs
kclvm/runtime/src/value/val_from.rs
kclvm/runtime/src/value/val_list.rs
kclvm/runtime/src/value/val_plan.rs
kclvm/runtime/src/value/val_schema.rs
kclvm/runtime/src/value/val_union.rs

kclvm/runtime
use std::box to avoid unnecessary memory alloc
from
```rust
pub enum Value {
undefined,
none,
bool_value(bool),
int_value(i64),
float_value(f64),
str_value(String),
list_value(ListValue),
dict_value(DictValue),
schema_value(SchemaValue),
func_value(FuncValue),
unit_value(f64, i64, String), // (Real value, raw value, unit string)
}
```
to
```rust
pub enum Value {
undefined,
none,
bool_value(bool),
int_value(i64),
float_value(f64),
str_value(String),
list_value(Box<ListValue>),
dict_value(Box<DictValue>),
schema_value(Box<SchemaValue>),
func_value(Box<FuncValue>),
unit_value(f64, i64, String), // (Real value, raw value, unit string)
}
```
Please refer to [Release Notes Language Style Guide](https://kusionstack.io/docs/governance/release-policy/) to write a quality release …

refactor : use std::box to avoid unnecessary memory alloc

---

kclvm/capi/Cargo.toml
kclvm/runtime/Cargo.toml
kclvm/runtime/internal_macros/src/lib.rs
kclvm/runtime/src/api/utils.rs
kclvm/runtime/src/context/mod.rs
kclvm/runtime/src/stdlib/builtin.rs
kclvm/runtime/src/stdlib/builtin_api.rs
kclvm/runtime/src/value/api.rs
kclvm/runtime/src/value/iter.rs
kclvm/runtime/src/value/val_bin.rs
kclvm/runtime/src/value/val_bin_aug.rs
kclvm/runtime/src/value/val_clone.rs
kclvm/runtime/src/value/val_dict.rs
kclvm/runtime/src/value/val_fmt.rs
kclvm/runtime/src/value/val_from.rs
kclvm/runtime/src/value/val_get_set.rs
kclvm/runtime/src/value/val_is_in.rs
kclvm/runtime/src/value/val_json.rs
kclvm/runtime/src/value/val_len.rs
kclvm/runtime/src/value/val_list.rs
kclvm/runtime/src/value/val_overflow.rs
kclvm/runtime/src/value/val_panic.rs
kclvm/runtime/src/value/val_schema.rs
kclvm/runtime/src/value/val_str.rs
kclvm/runtime/src/value/val_type.rs
kclvm/runtime/src/value/val_union.rs
kclvm/tools/src/vet/test_datas/invalid_validate_cases/test.k.stderr.json

re #191 
/kclvm/runtime
```release-note
None
```

Refactor: remove cargo clippy errors & warnings  from runtime

---

compiler_base/error/Cargo.toml
compiler_base/error/src/diagnostic/diagnostic_handler.rs
compiler_base/error/src/diagnostic/diagnostic_message.rs
compiler_base/error/src/diagnostic/tests.rs
compiler_base/session/Cargo.toml

issue #115.
#115 
compiler_base_error 
The new default method does not need to load the template file, which solves the problem that the template file path may not be found.
```release-note
None
```

Feat(compiler-base-error): add default() to DiagnosticHandler.

---

kclvm/tools/src/vet/tests.rs

issue #277
KCL-Vet
Add test case 'test_validator' for KCL-Vet to turn the execution mode of KCL-Vet's test cases from parallel to serial.
```release-note
None
```

Fix(KCL-Vet): Turn the execution mode of KCL-Vet's test cases from parallel to serial.

---

kclvm/runner/src/tests.rs

issue #277
kclvm-runner
Add test case 'test_exec' for kclvm-runner to turn the execution mode of kclvm-runner test cases from parallel to serial.
```release-note
None
```

Fix(KCL-Vet): Turn the execution mode of kclvm-runner test cases from parallel to serial.

---

kclvm/runtime/src/api/kclvm.rs
kclvm/runtime/src/value/val_union.rs

[kclvm/runtime/src/value/val_union.rs](https://github.com/KusionStack/KCLVM/compare/main...NeverRaR:dev/boying/runtime/union?expand=1#diff-8ae99b27301ecf8eea5c108497fa1842e3b9e6ddb9172757bb685f0c190f99a3)
fix : avoid borrowing same ref in ValRef.union
The test cases in  /kclvm/src/runtime/value/value_union.rs.test_dict_union_same_ref() are used to test union the ValueRef
with itself.
```release-note
None
```

fix : avoid borrowing same ref in ValRef.union

---

scripts/docker/kclvm/Dockerfile

feat: add kclvm release dockerfile
```release-note
None
```

feat: add kclvm release dockerfile

---

kclvm/runtime/src/value/val_fmt.rs

fix #149 
kclvm/runtime/src/value/val_fmt.rs
```release-note
None
```

fix : support list/dict subscript format in KCL string

---

kclvm/runner/Cargo.toml
kclvm/runner/src/command.rs
kclvm/runner/src/linker.rs
kclvm/runner/src/tests.rs

Considering that the maintenance of some target linker parameters is difficult and the execution stability of the linked KCL dynamic library is poor, external cc is used, such as using `msvc` as the linker on Windows.
re #283.
All runner unit test cases and integration grammar test cases.
```release-note
None
```

Add Linker with external cc for windows release.

---

compiler_base/error/Cargo.toml
compiler_base/error/src/diagnostic/diagnostic_handler.rs
compiler_base/error/src/emitter.rs
compiler_base/error/src/lib.rs
compiler_base/error/src/tests.rs

issue #351 .
compiler_base_error.
Added `ColoredRaw` and `UnColoredRaw` in `compiler_base_error::emitter::Destination` to redirection.
Added a method `emit_diagnostic_to_uncolored_text` to redirect diagnostic emit information to uncolored string.
Rename `TerminalEmitter` to `EmitterWriter`.
```release-note
None
```

Feat(compiler_base_error): Added methods to support redirection of compiler_base_error::emitter.

---

kclvm/sema/src/resolver/global.rs
kclvm/sema/src/resolver/node.rs
test/grammar/types/var_type_annotation/type_fail_10/main.k
test/grammar/types/var_type_annotation/type_fail_10/stderr.golden.py
test/grammar/types/var_type_annotation/type_fail_11/main.k
test/grammar/types/var_type_annotation/type_fail_11/stderr.golden.py
test/grammar/types/var_type_annotation/type_fail_12/main.k
test/grammar/types/var_type_annotation/type_fail_12/stderr.golden.py

fix: #325
Refactor
* kclvm/sema/src/resolver/global.rs
* kclvm/sema/src/resolver/node.rs
Fix
* `must_assignable_to` call at kclvm/sema/src/resolver/node.rs
+ test/grammar/types/var_type_annotation/type_fail_10/main.k
+ test/grammar/types/var_type_annotation/type_fail_11/main.k
+ test/grammar/types/var_type_annotation/type_fail_12/main.k
```release-note
None
```

fix: resolver ty mismatch in the assign statement with the schema type annotation

---

kclvm/runner/src/command.rs
kclvm/runner/src/lib.rs
kclvm/sema/src/lint/mod.rs
kclvm/sema/src/pre_process/tests.rs
kclvm/sema/src/resolver/config.rs
kclvm/sema/src/resolver/mod.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/scope.rs
kclvm/sema/src/resolver/tests.rs
kclvm/sema/src/ty/context.rs
test/grammar/types/var_type_annotation/type_fail_13/main.k
test/grammar/types/var_type_annotation/type_fail_13/stderr.golden.py
test/grammar/types/var_type_annotation/type_fail_14/main.k
test/grammar/types/var_type_annotation/type_fail_14/stderr.golden.py

Fixes #389 
+ test/grammar/types/var_type_annotation/type_fail_13/main.k
+ test/grammar/types/var_type_annotation/type_fail_14/main.k
```release-note
None
```

Fix config if entry type unsoundness

---

.github/workflows/windows_test.yaml
internal/scripts/build-kclvm.sh
internal/scripts/cli/kcl
internal/scripts/cli/kcl-doc
internal/scripts/cli/kcl-fmt
internal/scripts/cli/kcl-lint
internal/scripts/cli/kcl-plugin
internal/scripts/cli/kcl-vet
internal/scripts/kcllib-install.sh
internal/scripts/test_grammar.sh
scripts/build-windows/kcl-doc.go
scripts/build-windows/kcl-fmt.go
scripts/build-windows/kcl-lint.go
scripts/build-windows/kcl-plugin.go
scripts/build-windows/kcl-vet.go
scripts/build-windows/kcl.go
scripts/docker/kclvm/Dockerfile

issue #379.
kclvm windows.
1. Removed the process of using the flag file to determine if kclvm is successfully installed, and instead using the command "python3 -m pip show kclvm" to determine if kclvm is successfully installed.
2.  Add the -U parameter in all "pip install" commands to ensure the latest version of kclvm is obtained.
```release-note
None
```

Feat(kclvm-win): remove the "kclvm.requirements.done.txt" on windows.

---

kclvm/runtime/src/datetime/datetime.rs
test/grammar/types/var_type_annotation/type_fail_13/stderr.golden.py
test/grammar/types/var_type_annotation/type_fail_14/stderr.golden.py

fix #398 
+ kclvm/runtime/src/datetime/datetime.rs
All test cases.
```release-note
None
```

refactor: refine code to fix cargo update break issues and warnings

---

README.md

docs: polish readme English.
```release-note
None
```

docs: polish readme English.

---

.github/workflows/windows_test.yaml
build_and_test_win.bat
build_win.bat
kclvm/runner/src/command.rs
kclvm/runner/src/tests.rs

issue #379 .
kclvm-action ci.
move unit tests and runtime test in bat.
Some cache removal methods are added to the test cases to avoid the accidences caused by running the test cases multiple times.
```release-note
None
```

Fix(kclvm-windows): Fix the CI for kclvm windows.

---

kclvm/compiler/src/codegen/llvm/context.rs
kclvm/compiler/src/codegen/llvm/node.rs
test/grammar/datatype/dict/mutual_ref_13/main.k
test/grammar/datatype/dict/mutual_ref_13/stdout.golden

feat: #368 
+ test/grammar/datatype/dict/mutual_ref_13/main.k
```release-note
None
```

feat: support config mutref except arguments.

---

kclvm/ast_pretty/src/lib.rs
kclvm/ast_pretty/src/node.rs
kclvm/ast_pretty/src/test_data/comment.output
kclvm/query/src/tests.rs
kclvm/runner/src/command.rs
kclvm/tools/src/format/test_data/format_data/codelayout.golden
kclvm/tools/src/format/test_data/format_data/codelayout.input
kclvm/tools/src/format/test_data/format_data/comment.golden
kclvm/tools/src/format/test_data/format_data/comment.input
kclvm/tools/src/format/test_data/format_data/comp_for.golden
kclvm/tools/src/format/test_data/format_data/comp_for.input
kclvm/tools/src/format/test_data/format_data/lambda.golden
kclvm/tools/src/format/test_data/format_data/lambda.input
kclvm/tools/src/format/tests.rs
kclvm/tools/src/vet/tests.rs

re: #372
test: add integration tests on the format tool and fix test suites.
+ Unit test: `test_format_source` at kclvm/tools/src/format/tests.rs
+ Konfig integration test: `test_format_integration_konfig` at kclvm/tools/src/format/tests.rs
```release-note
None
```

test: add konfig integration tests on the format tool, fix test suites and add more unit test suites.

---

kclvm/error/src/emitter.rs
kclvm/lexer/src/lib.rs
kclvm/parser/src/lexer/indent.rs
kclvm/parser/src/lexer/mod.rs
kclvm/parser/src/parser/expr.rs
kclvm/parser/src/parser/mod.rs
kclvm/parser/src/parser/stmt.rs
kclvm/parser/src/parser/ty.rs
kclvm/parser/src/session/mod.rs
kclvm/parser/src/tests.rs
kclvm/span/src/symbol.rs

re #57 and #420
refactor: unreasonable revealed parser error information to avoid parser throwing internal errors for parser error recovery.
+ `kclvm_parser` crate
refactor: unreasonable revealed parser error information to avoid parser throwing internal errors for parser error recovery.
+ kclvm/parser/src/tests.rs
```release-note
None
```

refactor: unreasonable revealed parser error information to avoid parser throwing internal errors for parser error recovery.

---

compiler_base/error/Cargo.toml
compiler_base/error/src/diagnostic/diagnostic_handler.rs
compiler_base/error/src/emitter.rs
compiler_base/error/src/tests.rs

compiler_base_error.
add method "emit_all_diags_into_string" for 'DiagnosticHandler' to emit all diagnostics into strings.
add method "emit_nth_diag_into_string" for 'DiagnosticHandler' to emit one diagnostics into string.
```release-note
None
```

Feat(compiler_base_error): Add methods to the `DiagnosticHandler` that emits `Diagnostic` as string.

---

internal/spec/gpyrpc/gpyrpc.proto
kclvm/Cargo.lock
kclvm/capi/Cargo.toml
kclvm/capi/src/api_test.rs
kclvm/capi/src/model/gpyrpc.rs
kclvm/capi/src/service/api.rs
kclvm/capi/src/service/mod.rs
kclvm/capi/src/service/service.rs
kclvm/capi/src/service/ty.rs
kclvm/query/Cargo.toml
kclvm/query/src/lib.rs
kclvm/query/src/override.rs
kclvm/query/src/query.rs
kclvm/query/src/tests.rs
kclvm/runner/Cargo.toml
kclvm/tools/Cargo.toml

feat: #418 
+ kclvm/capi/src/service/service.rs
```release-note
None
```

feat: impl schema query API.

---

scripts/build-llvm/build.ps1
scripts/build-llvm/build.sh

…lvm.
feat: add custom llvm build scripts without term info and zlib to reduce kclvm release size.
```release-note
None
```

feat: add custom llvm build scripts without term info and zlib to reduce kclvm release size.

---

kclvm/parser/src/parser/expr.rs
kclvm/parser/src/parser/tests.rs
kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__if_recovery_0.snap
kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__if_recovery_1.snap
kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__if_recovery_2.snap
kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__if_recovery_3.snap

Parser
Bugfix: If expr position error
```release-note
None
```

Bugfix(Parser): If expr position error

---

kclvm/driver/src/lib.rs
kclvm/tools/src/LSP/src/completion.rs
kclvm/tools/src/LSP/src/tests.rs

Fix CI failure cause by inconsistent order of walk files.
```release-note
None
```

bugfix: Fix CI failure cause by inconsistent order of walk files

---

kclvm/sema/src/resolver/node.rs
kclvm/tools/src/LSP/src/capabilities.rs
kclvm/tools/src/LSP/src/document_symbol.rs
kclvm/tools/src/LSP/src/lib.rs
kclvm/tools/src/LSP/src/main.rs
kclvm/tools/src/LSP/src/request.rs
kclvm/tools/src/LSP/src/test_data/document_symbol.k
kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/LSP/src/util.rs

LSP
Feat(LSP): Document Symbol Provider. Select variable and schema definition and shown with document symbol(Outline in vscode)
```release-note
None
```

Feat(LSP): Document symbol(Outline)

---

.github/workflows/cla.yml

chore: bump github cla action version to contributor-assistant/github-action@v2.3.0.
```release-note
None
```

chore: bump github cla action version to contributor-assistant/github-action@v2.3.0.

---

Makefile
kclvm/sema/src/pre_process/config.rs
test/grammar/unification/append_0/main.k
test/grammar/unification/append_1/main.k
test/grammar/unification/collection_if_0/main.k
test/grammar/unification/collection_if_1/main.k
test/grammar/unification/empty_0/main.k
test/grammar/unification/empty_1/main.k
test/grammar/unification/multi_file_compile_0/main.k
test/grammar/unification/multi_file_compile_0/stack.k
test/grammar/unification/multi_file_compile_1/main.k
test/grammar/unification/multi_file_compile_1/stack.k
test/grammar/unification/nest_var_0/main.k
test/grammar/unification/nest_var_1/main.k
test/grammar/unification/override_0/main.k
test/grammar/unification/override_1/main.k
test/grammar/unification/schema_simple_0/main.k
test/grammar/unification/schema_simple_1/main.k
test/grammar/unification/schema_simple_2/main.k
test/grammar/unification/schema_simple_3/main.k
test/grammar/unification/str_interpolation/main.k
test/grammar/unification/subscript_0/main.k
test/grammar/unification/subscript_1/main.k
test/grammar/unification/unpack_0/main.k
test/grammar/unification/unpack_1/main.k

feat: remove top-level unification using the override operator.
Language simplification: The schema with the same name as top level uses `=` to indicate override, uses `:` to indicate merging, and reports an error when overriding the immutable variable `=`.
Language simplification: The schema with the same name as top level uses `=` to indicate override, uses `:` to indicate merging, and reports an error when overriding the immutable variable `=`.
+ test/grammar/unification/**/*.k
```release-note
None
```

feat: remove top level unification using the override operator.

---

kclvm/cmd/src/tests.rs
kclvm/cmd/src/util.rs

kclvm_cli.
When the `-E/--external` arguments of the `kclvm_cli run` command is used, the parsed path format is incorrect. As a result, the package in the corresponding path cannot be found.
```release-note
None
```

fix: fix a bug in the path format of argument '-E/--external'.

---

kclvm/runner/src/lib.rs
kclvm/runner/src/runner.rs
test/grammar/misc/empty_plan/main.k

refactor: empty result plan.
+ test/grammar/misc/empty_plan/main.k
```release-note
None
```

refactor: empty result plan.

---

kclvm/runner/src/assembler.rs
kclvm/runner/src/tests.rs

refactor: remove dead code in the assembler.
All integraition grammar tests.
```release-note
None
```

refactor: remove dead code in the assembler.

---

kclvm/sema/src/resolver/node.rs
test/grammar/quant/filter/simple_list_2/main.k
test/grammar/quant/filter/simple_list_2/stdout.golden

fix: filter expression return type.
+ test/grammar/quant/filter/simple_list_2/main.k
```release-note
None
```

fix: filter expression return type.

---

internal/scripts/cli/kcl
kclvm/Cargo.lock
kclvm/cmd/src/lib.rs
kclvm/runner/src/assembler.rs
kclvm/version/Cargo.toml
kclvm/version/build.rs
kclvm/version/src/lib.rs
scripts/build-windows/kcl.go

refactor: enhance kcl version info message using the vergen crate and bump kcl version to v0.4.6.3
+ kclvm/version/build.rs
+ scripts/build-windows/kcl.go
+ internal/scripts/cli/kcl
+ Patch version info only for v0.4.x, all CLIs will be unified after v0.5.x.
+ Add git commit and platform showing in the version info
```release-note
None
```

refactor: enhance kcl version info message using the vergen crate and bump kcl version to v0.4.6.3

---

kclvm/sema/src/resolver/config.rs
test/grammar/types/interpolation/interpolation_0/main.k
test/grammar/types/interpolation/interpolation_0/stdout.golden
test/grammar/types/interpolation/interpolation_1/main.k
test/grammar/types/interpolation/interpolation_1/stdout.golden

refactor: joined string and missing key recovery for better error messages.
refactor: joined string and missing key recovery for better error messages.
+ test/grammar/types/interpolation/interpolation_0/main.k
+ test/grammar/types/interpolation/interpolation_1/main.k
```release-note
None
```

refactor: joined string and missing key recovery for better error messages.

---

internal/spec/gpyrpc/gpyrpc.proto
kclvm/api/src/service/into.rs
kclvm/cmd/src/lib.rs
kclvm/cmd/src/settings.rs
kclvm/config/src/settings.rs
kclvm/config/src/testdata/settings.yaml
kclvm/runner/src/runner.rs
test/grammar/sort_keys/hello/settings.yaml

feat: impl sort keys in setting files.
+ kclvm/config/src/settings.rs
+ test/grammar/sort_keys/hello/
```release-note
None
```

feat: impl sort keys in setting files.

---

kclvm/Cargo.lock
kclvm/cmd/Cargo.toml
kclvm/cmd/src/fmt.rs
kclvm/cmd/src/lib.rs
kclvm/cmd/src/lint.rs
kclvm/cmd/src/settings.rs
kclvm/cmd/src/util.rs
kclvm/cmd/src/vet.rs

fix #333
- kclvm/Cargo.lock
- kclvm/cmd/Cargo.toml
- kclvm/cmd/src/fmt.rs
- kclvm/cmd/src/lib.rs
- kclvm/cmd/src/lint.rs
- kclvm/cmd/src/settings.rs
- kclvm/cmd/src/util.rs
- kclvm/cmd/src/vet.rs
Summary of changes:
- Use `Arg.num_args`
- [Supersedes](https://github.com/clap-rs/clap/issues/2688) `multiple_values` and `takes_value`
- Use `ArgMatches.get_one` and `ArgMatches.get_many` in place of `ArgMatches.value_of*` and `ArgMatches.values_of*`
- Replace `occurrences_of` with `ArgAction::Count` and `get_count`  for flag counting
- Replace `occurrences_of`with `get_flag` for flags whether
This PR updates the dependency of clap from 3.x to 4.x in [kclvm/cmd](https://github.com/KusionStack/KCLVM/tree/main/kclvm), resulting in significant changes to the CLI interface style, such as [color …

refactor: Upgrade kclvm/cmd clap version to 4.x

---

kclvm/runtime/src/api/kclvm.rs
kclvm/runtime/src/stdlib/builtin_api.rs
kclvm/runtime/src/value/api.rs
kclvm/runtime/src/value/val_plan.rs
kclvm/version/src/lib.rs
test/grammar/types/runtime_ty/runtime_ty_0/main.k
test/grammar/types/runtime_ty/runtime_ty_0/stdout.golden
test/grammar/types/runtime_ty/runtime_ty_1/main.k
test/grammar/types/runtime_ty/runtime_ty_1/stdout.golden
test/grammar/types/runtime_ty/runtime_ty_err_0/main.k
test/grammar/types/runtime_ty/runtime_ty_err_0/stderr.golden.py
test/grammar/types/runtime_ty/runtime_ty_err_1/main.k
test/grammar/types/runtime_ty/runtime_ty_err_1/stderr.golden.py

refactor: runtime ty check and add more test cases.
+ kclvm/runtime/src/api/kclvm.rs
+ test/grammar/types/runtime_ty/**/*.k
```release-note
None
```

refactor: runtime ty check and add more test cases.

---

scripts/docker/kclvm-builder-centos8/Dockerfile
scripts/docker/kclvm-builder-centos8/Makefile
scripts/docker/kclvm-builder/Dockerfile

fix #565 
- scripts/docker/kclvm-builder-centos8/Dockerfile
- scripts/docker/kclvm-builder-centos8/Makefile
- scripts/docker/kclvm-builder/Dockerfile
```release-note
None
```

fix: update go version in Dockerfile and fix bugs

---

kclvm/driver/src/kpm_metadata.rs
kclvm/driver/src/tests.rs

fix: rm the 'Result::unwrap()' in lsp.

---

kclvm/compiler/src/codegen/llvm/node.rs
kclvm/runtime/src/value/api.rs
kclvm/version/src/lib.rs
test/grammar/schema/index_signature/key_alias_0/main.k
test/grammar/schema/index_signature/key_alias_0/stdout.golden
test/grammar/schema/index_signature/key_alias_1/main.k
test/grammar/schema/index_signature/key_alias_1/stdout.golden
test/grammar/schema/index_signature/normal_1/stdout.golden
test/grammar/schema/index_signature/normal_5/main.k
test/grammar/schema/index_signature/normal_5/stdout.golden

Closes #577 
feat: index sign alias ref in the schema body
```python
schema TeamSpec[id: str]:
fullName: str
name = id
shortName: str = name
schema TeamMap:
[n: str]: TeamSpec = TeamSpec(n)  # OK: `n` can be referenced from the index signature key name.
Team = TeamMap {
a.fullName = "alpha"
b.fullName = "bravo"
}
```
+ test/grammar/schema/index_signature/**/**
```release-note
None
```

feat: index sign key name reference in the schema body

---

kclvm/runtime/src/value/api.rs
kclvm/runtime/src/value/val_bin.rs
kclvm/runtime/src/value/val_bin_aug.rs
kclvm/runtime/src/value/val_dict.rs
kclvm/runtime/src/value/val_union.rs

refactor: value union with options.
+ the kcl runtime crate
+ all runtime unit test cases
+ all integration grammar test cases
```release-note
None
```

refactor: value union with options.

---

kclvm/config/src/settings.rs
kclvm/runtime/src/value/val_plan.rs
kclvm/tools/src/vet/expr_builder.rs
kclvm/tools/src/vet/tests.rs
kclvm/tools/src/vet/validator.rs

refactor: enhance cli error messages for run and vet commands.
+ kclvm/tools/src/vet/tests.rs
+ all grammar test cases
```release-note
None
```

refactor: enhance cli error messages for run and vet commands.

---

kclvm/query/src/override.rs
kclvm/query/src/tests.rs

Closes #588 
+ kclvm/query/src/override.rs
+ kclvm/query/src/tests.rs
```release-note
None
```

feat: enhance override with compact style.

---

kclvm/parser/src/parser/expr.rs
kclvm/tools/src/LSP/src/completion.rs
kclvm/tools/src/LSP/src/test_data/completion_test/dot/completion.k
kclvm/tools/src/LSP/src/tests.rs

fix empty identifier expr postion and completion for literal str in lsp
parser, lsp

fix: fix empty identifier expr position

---

kclvm/api/src/service/capi.rs
kclvm/api/src/service/service_impl.rs
kclvm/cmd/src/lib.rs
kclvm/cmd/src/lint.rs
kclvm/cmd/src/test_data/lint/test.k
kclvm/cmd/src/tests.rs
kclvm/driver/src/lib.rs
kclvm/runner/src/lib.rs
kclvm/runtime/src/_kcl_run.rs
kclvm/src/lib.rs
kclvm/tools/src/format/mod.rs
kclvm/tools/src/format/tests.rs

refactor: enhance kcl and its tool cli error message and add more tests.
+ kclvm/cmd/src/lib.rs
+ kclvm/cmd/src/lint.rs

refactor: enhance kcl and its tool cli error message and add more tests.

---

kclvm/Cargo.lock
kclvm/sema/Cargo.toml
kclvm/sema/src/resolver/doc.rs

Closes #576 
sema/resolver/doc.rs
Use pcre2 to replace std::Reegex
Manual test sema/resolver/tests::test_resolve_schema_doc and got 10-20 times enhance on method `strip_quotes`
Before
After:

fix: fix performance regression on resolver::parse_doc_string

---

kclvm/sema/src/resolver/doc.rs
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/test_data/hover_test/hover.k
kclvm/tools/src/LSP/src/tests.rs

lsp
feat: enhance lsp hover. Hover for schema varibale display schema pkg, schema name, doc and attrs

feat: enhance lsp hover

---

internal/spec/gpyrpc/gpyrpc.proto

chore: fix wrong KclType documents.

chore: fix wrong KclType documents.

---

kclvm/ast/src/ast.rs
kclvm/ast/src/pos.rs
kclvm/compiler/src/codegen/llvm/context.rs
kclvm/error/src/diagnostic.rs
kclvm/error/src/error.rs
kclvm/error/src/lib.rs
kclvm/parser/src/lib.rs
kclvm/sema/src/lint/lints_def.rs
kclvm/sema/src/resolver/arg.rs
kclvm/sema/src/resolver/attr.rs
kclvm/sema/src/resolver/calculation.rs
kclvm/sema/src/resolver/config.rs
kclvm/sema/src/resolver/global.rs
kclvm/sema/src/resolver/import.rs
kclvm/sema/src/resolver/loop.rs
kclvm/sema/src/resolver/mod.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/para.rs
kclvm/sema/src/resolver/schema.rs
kclvm/sema/src/resolver/scope.rs
kclvm/sema/src/resolver/tests.rs
kclvm/sema/src/resolver/ty.rs
kclvm/sema/src/resolver/var.rs
kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/LSP/src/to_lsp.rs
kclvm/tools/src/lint/mod.rs

errors
Change diagnostic position from pos(start) to range(start, end)

Feat: Change  diagnostic position from pos(start) to range(start, end)

---

kclvm/tools/src/LSP/src/test_data/diagnostics.k
kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/LSP/src/to_lsp.rs

lsp
Add diagnostic related information to display multiple position diagnostic, e.g. config conflict.
The first line is diagnostic message and the second line is related information(message and location)

feat: diagnostic related info

---

kclvm/sema/src/resolver/doc.rs
kclvm/sema/src/resolver/test_data/doc.txt

doc
bugfix: doc parser panic when empty line length less than min margin

bugfix: doc parser panic when empty line length less than min margin

---

kclvm/api/src/service/service_impl.rs
kclvm/ast/src/token.rs
kclvm/cmd/src/fmt.rs
kclvm/parser/src/lexer/indent.rs
kclvm/parser/src/lib.rs
kclvm/parser/src/parser/expr.rs
kclvm/tools/src/format/mod.rs
kclvm/tools/src/format/tests.rs

feat: support format tool error recovery and error indent/dedent code format.
+ By supporting the `omit_errors` option to impl the code formatting feature with syntax errors
+ Optimize KCL indentation error handling and recovery, so that configuration code with indentation errors can still be formatted correctly.
+ Fix unexpected `ConfigExpr` and `ListExpr` parser error handling.
+ kclvm/cmd/src/fmt.rs
+ kclvm/parser/src/lexer/indent.rs
+ kclvm/parser/src/lib.rs
+ kclvm/parser/src/parser/expr.rs
+ `test_format_with_omit_error_option` at `kclvm/tools/src/format/tests.rs`

feat: support format tool error recovery and error indent/dedent code format

---

kclvm/Cargo.lock
kclvm/ast/src/ast.rs
kclvm/sema/src/resolver/scope.rs
kclvm/tools/src/LSP/Cargo.toml
kclvm/tools/src/LSP/src/analysis.rs
kclvm/tools/src/LSP/src/db.rs
kclvm/tools/src/LSP/src/notification.rs
kclvm/tools/src/LSP/src/request.rs
kclvm/tools/src/LSP/src/state.rs

lsp
add lsp db to store compile state. query and analysis from db when handle request

feat: add lsp db to store compile state. 

---

kclvm/sema/src/resolver/config.rs
kclvm/sema/src/resolver/global.rs
kclvm/sema/src/ty/mod.rs

sema/type
fix schema attr position in sema type.

bugfix: fix schema attr position in sema type

---

kclvm/driver/src/lib.rs

feat #524 
driver
change compile unit for base.k in konfig. Only compile base.k instead of random stack

feat: change compile unit for base.k in konfig

---

kclvm/cmd/src/test_data/plugin/plugin_not_found/kcl.mod
kclvm/cmd/src/test_data/plugin/plugin_not_found/main.k
kclvm/cmd/src/tests.rs
kclvm/runner/src/lib.rs

fix https://github.com/kcl-lang/kcl/issues/676
kclvm/runner/src/lib.rs

fix: fix some missing diagnostics in parser.

---

kclvm/api/src/service/ty.rs
kclvm/sema/src/resolver/attr.rs
kclvm/sema/src/resolver/config.rs
kclvm/sema/src/resolver/loop.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/ty.rs
kclvm/sema/src/ty/constructor.rs
kclvm/sema/src/ty/context.rs
kclvm/sema/src/ty/into.rs
kclvm/sema/src/ty/mod.rs
kclvm/sema/src/ty/walker.rs
kclvm/tools/src/LSP/src/goto_def.rs
test/grammar/types/union_ty/union_ty_11/main.k
test/grammar/types/union_ty/union_ty_11/stdout.golden
test/grammar/types/union_ty/union_ty_12/main.k
test/grammar/types/union_ty/union_ty_12/stdout.golden

re #635 
feat: enhance config attribute type inference through the config attribute type map.
```python
metadata = {
name = "app"
labels.app = "app"
}
labels: {str:str} = metadata.labels
```
Before this PR, the type of `metadata.labels` will be inferred as a `{str:str}|str` type. In fact, we can derive more precise types, and this PR solves this problem. The more information is in #635 
The kcl sematic model crate
+ test/grammar/types/union_ty/union_ty_11/main.k
+ test/grammar/types/union_ty/union_ty_12/main.k

feat: enhance config attribute type inference through the config attribute type map.

---

kclvm/tools/src/LSP/src/capabilities.rs
kclvm/tools/src/LSP/src/formatting.rs
kclvm/tools/src/LSP/src/lib.rs
kclvm/tools/src/LSP/src/main.rs
kclvm/tools/src/LSP/src/request.rs
kclvm/tools/src/LSP/src/tests.rs

lsp
Integrate kcl fmt tools to lsp. Suport formmat single file

feat: integrate kcl fmt tools to lsp. Suport formmat single file

---

kclvm/query/src/query.rs
kclvm/sema/src/resolver/global.rs
kclvm/sema/src/resolver/mod.rs
kclvm/sema/src/resolver/schema.rs
kclvm/sema/src/resolver/tests.rs
kclvm/tools/src/LSP/src/request.rs

feat: add resolve print options for the resolver to speedup the normal compilation process
+ kclvm/sema/src/resolver/mod.rs

feat: add resolve print options for the resolver to speedup the normal compilation process

---

kclvm/sema/src/resolver/node.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/test_data/goto_def_test/goto_def.k
kclvm/tools/src/LSP/src/tests.rs

Close #635
+ lsp
+ sema
Enhance find_def in lsp for dict type, used for lsp goto def and hover

feat: lsp find_def for dict type

---

kclvm/sema/src/builtin/string.rs
kclvm/sema/src/resolver/arg.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/schema.rs
kclvm/sema/src/ty/constructor.rs
kclvm/sema/src/ty/mod.rs
kclvm/tools/src/LSP/src/completion.rs
test/grammar/types/args/schema_types_err_too_many_args_0/main.k
test/grammar/types/args/schema_types_err_too_many_args_0/stderr.golden.py
test/grammar/types/args/schema_types_err_too_many_args_1/main.k
test/grammar/types/args/schema_types_err_too_many_args_1/stderr.golden.py
test/grammar/types/args/schema_types_err_too_many_args_2/main.k
test/grammar/types/args/schema_types_err_too_many_args_2/stderr.golden.py

fix #667 
fix: argument type check on too many arguments for empty parameter list
+ kclvm/sema/src/resolver/arg.rs (remove `params empty check`)
+ test/grammar/types/args/schema_types_err_too_many_args_0/main.k
+ test/grammar/types/args/schema_types_err_too_many_args_1/main.k
+ test/grammar/types/args/schema_types_err_too_many_args_2/main.k

fix: argument type check on too many arguments for empty parameter list

---

kclvm/sema/src/builtin/string.rs
kclvm/sema/src/builtin/system_module.rs
kclvm/sema/src/resolver/attr.rs
kclvm/sema/src/resolver/test_data/system_package.k
kclvm/sema/src/resolver/tests.rs

re #694
feat: add base64 and net member function types
+ kclvm/sema/src/builtin/system_module.rs
+ kclvm/sema/src/resolver/attr.rs
+ kclvm/sema/src/resolver/tests.rs

feat: add base64 and net member function types

---

kclvm/tools/src/LSP/src/completion.rs
kclvm/tools/src/LSP/src/document_symbol.rs
kclvm/tools/src/LSP/src/find_ref/tests.rs
kclvm/tools/src/LSP/src/find_ref/word_map.rs
kclvm/tools/src/LSP/src/formatting.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/lib.rs
kclvm/tools/src/LSP/src/main.rs
kclvm/tools/src/LSP/src/main_loop.rs
kclvm/tools/src/LSP/src/quick_fix.rs
kclvm/tools/src/LSP/src/state.rs
kclvm/tools/src/LSP/src/test_data/diagnostics.k
kclvm/tools/src/LSP/src/test_data/hover_test/hover.k
kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/LSP/src/util.rs

tools/lsp
1. Move unit tests to implement file
2. add e2e test tools, and add tests for goto_def, completion, hover and fmt

feat: lsp e2e test.

---

kclvm/sema/src/resolver/config.rs
test/grammar/types/config/config_ty_0/main.k
test/grammar/types/config/config_ty_0/stdout.golden
test/grammar/types/config/config_ty_1/main.k
test/grammar/types/config/config_ty_1/stdout.golden
test/grammar/types/config/config_ty_2/main.k
test/grammar/types/config/config_ty_2/stdout.golden
test/grammar/types/config/config_ty_3/main.k
test/grammar/types/config/config_ty_3/stdout.golden

re #635 
feat: enhance config attribute type inference through the config attribute type map.
```python
config: {str:} = {
"key" = [
{
key = "value"
}
]
"values" = [
"foo"
"bar"
]
}
values: [str] = config.values
```
Before this PR, the type of `config.values` will be inferred as a `[{str:str}]|[str]` type. In fact, we can derive more precise types, and this PR solves this problem. The more information is in #635 
The kcl sematic model crate
+ test/grammar/types/config/config_ty_0/main.k
+ test/grammar/types/config/config_ty_1/main.k
+ test/grammar/types/config/config_ty_2/main.k
+ test/grammar/types/config/config_ty_3/main.k

feat: enhance config attr type checking

---

kclvm/sema/src/resolver/import.rs
kclvm/tools/src/LSP/src/completion.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/test_data/completion_test/dot/completion.k
kclvm/tools/src/LSP/src/test_data/completion_test/without_dot/completion.k
kclvm/tools/src/LSP/src/test_data/completion_test/without_dot/pkg/subpkg/file1.k

Sometimes lsp handle completion request before didChange notification and without trigger character dot in vfs. fix pkg completion in this case
lsp
Sometimes lsp handle completion request before didChange notification and without trigger character dot in vfs. fix pkg completion in this case

bugfix: pkg completion without dot

---

kclvm/runtime/src/value/api.rs
kclvm/sema/src/builtin/mod.rs
kclvm/sema/src/builtin/string.rs
kclvm/sema/src/resolver/arg.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/schema.rs
test/grammar/types/args/call_expr_err_too_few_args_0/main.k
test/grammar/types/args/call_expr_err_too_few_args_0/stderr.golden.py
test/grammar/types/args/call_expr_err_too_few_args_1/main.k
test/grammar/types/args/call_expr_err_too_few_args_1/stderr.golden.py

feat: impl positional argument count check for call expressions.
+ kclvm/sema/src/resolver/arg.rs
+ test/grammar/types/args/call_expr_err_too_few_args_0/main.k
+ test/grammar/types/args/call_expr_err_too_few_args_1/main.k

feat: impl positional argument count check for call expressions.

---

kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/format/tests.rs

test: add integration test of lsp and Konfig

---

kclvm/parser/src/lexer/mod.rs
kclvm/parser/src/lexer/tests.rs

fix #65 
kclvm/parser/src/lexer/mod.rs

fix: Added 'lookbehind' method in lexer

---

kclvm/sema/src/lint/lints_def.rs
kclvm/sema/src/resolver/config.rs
kclvm/sema/src/resolver/global.rs
kclvm/sema/src/resolver/import.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/schema.rs
kclvm/sema/src/resolver/scope.rs
kclvm/sema/src/resolver/tests.rs
kclvm/sema/src/resolver/var.rs
kclvm/tools/src/LSP/src/completion.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/lint/test_data/unused_check_for_each_file/a.k
kclvm/tools/src/lint/test_data/unused_check_for_each_file/b.k
kclvm/tools/src/lint/tests.rs

lint
scope
lint check unused import in each file instead of global modules, e.g.,
a.k
```
import math
```
b.k
```
import math
a = math.pow(1, 1)
```
In pre version, `kclvm_cli lint a.k b.k` will not emit unused warning because `math` has be used in b.k.
After this, it will emit unused import warning in a.k

feat: lint check unused import in each file instead of global modules

---

kclvm/sema/src/pre_process/mod.rs
kclvm/sema/src/pre_process/test_data/skip_merge/config1.k
kclvm/sema/src/pre_process/test_data/skip_merge/config2.k
kclvm/sema/src/pre_process/test_data/skip_merge/def.k
kclvm/sema/src/pre_process/tests.rs
kclvm/sema/src/resolver/mod.rs
kclvm/sema/src/resolver/tests.rs
kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/LSP/src/util.rs
kclvm/tools/src/lint/mod.rs

add a option arg to control pre process merge ast, disable it in lint and LSP
resolver
add a option arg to control pre process merge ast, disable it in lint and LSP

feat: add a option to control pre process merge AST for the resolver

---

kclvm/cmd/src/lib.rs
kclvm/cmd/src/lint.rs
kclvm/error/src/diagnostic.rs
kclvm/error/src/error.rs
kclvm/error/src/lib.rs
kclvm/parser/src/lib.rs
kclvm/sema/src/lint/lints_def.rs
kclvm/sema/src/resolver/attr.rs
kclvm/sema/src/resolver/config.rs
kclvm/sema/src/resolver/global.rs
kclvm/sema/src/resolver/import.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/para.rs
kclvm/sema/src/resolver/schema.rs
kclvm/sema/src/resolver/tests.rs
kclvm/sema/src/resolver/ty.rs
kclvm/sema/src/resolver/var.rs
kclvm/tools/src/fix/LICENSE
kclvm/tools/src/fix/mod.rs
kclvm/tools/src/fix/replace.rs
kclvm/tools/src/fix/test_data/fix_import.k
kclvm/tools/src/fix/test_data/unused_import.k
kclvm/tools/src/fix/tests.rs
kclvm/tools/src/lib.rs
kclvm/tools/src/lint/mod.rs

tools
Add '--fix' param for kclvm_cli lint and auto fix unused import and reimport warning

feat: auto fix tools

---

kclvm/sema/src/builtin/mod.rs
kclvm/sema/src/resolver/scope.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/test_data/hover_test/hover.k
kclvm/tools/src/LSP/src/tests.rs

lsp hover
sema
add lsp hover for builtin function

feat: add lsp hover for builtin function

---

kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/test_data/hover_test/fib.k
kclvm/tools/src/LSP/src/util.rs

tools/lsp/goto_def
bugfix: goto def (and hover) for complex select expr, e.g.,  Fib{ x = 8}.value

bugfix: goto def (and hover) for complex select expr

---

kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/test_data/hover_test/hover.k

tools/src
bugfix: str type var builtin function hover

bugfix: str type var builtin function hover

---

kclvm/sema/src/resolver/global.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/test_data/assign_in_lambda.k
kclvm/sema/src/resolver/tests.rs
kclvm/sema/src/resolver/ty.rs
kclvm/sema/src/ty/unify.rs
kclvm/tools/src/LSP/src/test_data/goto_def_test/goto_def.k
kclvm/tools/src/LSP/src/test_data/hover_test/assign_in_lambda.k
kclvm/tools/src/LSP/src/tests.rs

Signed-off-by: zongz <zongzhe1024@163.com>
Fixes #746 
add type annotation check during type checking in assignment.

fix: add type annotation check during type checking in assignment

---

kclvm/sema/src/resolver/global.rs
kclvm/tools/src/LSP/src/find_refs.rs
kclvm/tools/src/LSP/src/main.rs
kclvm/tools/src/LSP/src/notification.rs

**unused imports:**
- kclvm/sema/src/resolver/global.rs
- kclvm/tools/src/LSP/src/main.rs
**unused comments:**
- kclvm/tools/src/LSP/src/find_refs.rs
- kclvm/tools/src/LSP/src/notification.rs
This PR clean unused imports and comments.

chore: code clean-unused imports and comments

---

kclvm/tools/src/LSP/src/find_refs.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/util.rs

close #754
It turns out the the find refs failed from the schema attribute def, is caused because the goto-def ignored the case when goto-def from schema attr def. Thanks to @He1pa we fixed the bug and added more tests on it.
- the fix: 
- kclvm/tools/src/LSP/src/util.rs
- the tests:
- kclvm/tools/src/LSP/src/find_refs.rs
- kclvm/tools/src/LSP/src/goto_def.rs
Fix goto attr def from attr def itself, add test cases on goto-def and find-refs

Fix goto attr def from attr def itself, add test cases on goto-def and find-refs

---

kclvm/sema/src/pre_process/config.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/test_data/goto_def_test/goto_def.k

sema/config.rs
fix position error when desuger config expr, e.g., desuger
```
foo = Foo {
bar.baz : xxx   
}
```
to:
```
foo = Foo {
bar : Bar {
baz : xxx
}
}
```

fix: fix position error when desuger config expr

---

kclvm/cmd/src/test_data/failed/keyword_argument_error.k
kclvm/cmd/src/tests.rs
kclvm/runtime/src/value/val_fmt.rs
kclvm/sema/src/resolver/test_fail_data/unmatched_args.k

Fixed #775 
kclvm/runtime/src/value/val_fmt.rs

feat: add keyword argument name in error message

---

kclvm/ast_pretty/src/lib.rs
kclvm/tools/src/format/test_data/format_data/different_stmts_line_breaks.golden
kclvm/tools/src/format/test_data/format_data/different_stmts_line_breaks.input
kclvm/tools/src/format/test_data/format_data/list_dict_schema_expr.golden
kclvm/tools/src/format/test_data/format_data/list_dict_schema_expr.input
kclvm/tools/src/format/test_data/format_data/union_types.golden
kclvm/tools/src/format/test_data/format_data/union_types.input
kclvm/tools/src/format/tests.rs

re #627 
testdata:
- kclvm/tools/src/format/test_data/format_data/
- kclvm/tools/src/format/tests.rs
add more test cases on format tool behavior

test: add more test cases on format tool behavior

---

kclvm/runtime/src/value/val_type.rs

fix: runtime union type parse and checking
+ kclvm/runtime/src/value/val_type.rs
+ kclvm/runtime/src/value/val_type.rs

fix: runtime union type parse and checking

---

kclvm/ast_pretty/src/node.rs
kclvm/ast_pretty/src/test_data/codelayout.output
kclvm/tools/src/format/test_data/format_data/breakline.golden
kclvm/tools/src/format/test_data/format_data/codelayout.golden
kclvm/tools/src/format/test_data/format_data/different_stmts_line_breaks.golden
kclvm/tools/src/format/test_data/format_data/different_stmts_line_breaks.input
kclvm/tools/src/format/test_data/format_data/import.golden
kclvm/tools/src/format/test_data/format_data/import_only.golden
kclvm/tools/src/format/test_data/format_data/import_only.input
kclvm/tools/src/format/test_data/format_data/layout_import_stmt.golden
kclvm/tools/src/format/test_data/format_data/layout_import_stmt.input
kclvm/tools/src/format/test_data/format_data/schema.golden
kclvm/tools/src/format/tests.rs

re #627 
fix format behavior on line break between import stmt and other stmts

fix format behavior on line break between import stmt and other stmts

---

kclvm/tools/src/LSP/src/request.rs
kclvm/tools/src/LSP/src/tests.rs

When the client renames a file, if the file suffix is changed, some requests will also be sent. However, it is considered not a valid kcl file during compilation, which will cause lsp panic.
tools/lsp
When the client renames a file, if the file suffix is changed, some requests will also be sent. However, it is considered not a valid kcl file during compilation, which will cause lsp panic.

fix: Defend against  non-KCL files

---

kclvm/sema/src/resolver/node.rs
test/grammar/lambda/arg_type/main.k
test/grammar/lambda/arg_type/stdout.golden
test/grammar/lambda/arg_type/sub.k

Fixed #782
kclvm/sema/src/resolver/node.rs

fix: fix the lambda argument type, when it is schema type, into schema type instance

---

kclvm/tools/src/LSP/src/capabilities.rs
kclvm/tools/src/LSP/src/completion.rs
kclvm/tools/src/LSP/src/test_data/completion_test/assign/completion.k
kclvm/tools/src/LSP/src/test_data/completion_test/assign/pkg/subpkg/file1.k

Completion when input `=` or `:` in config schema attr, and completion item contains primitiver type, literal, schema, list, dict, union
lsp completion
Completion when input `=` or `:` in config schema attr, and completion item contains primitiver type, literal, schema, list, dict, union

feat: completion for schema attr value.

---

kclvm/compiler/src/codegen/llvm/node.rs
kclvm/sema/src/resolver/config.rs
kclvm/tools/src/LSP/src/notification.rs
test/grammar/datatype/dict/mutual_ref_14/main.k
test/grammar/datatype/dict/mutual_ref_14/stdout.golden

fix #816 
+ fix: mutual reference for config multiple keys
+ test/grammar/datatype/dict/mutual_ref_14/*

fix: mutual reference for config multiple keys

---

kclvm/sema/src/advanced_resolver/mod.rs
kclvm/sema/src/advanced_resolver/node.rs
kclvm/sema/src/core/global_state.rs
kclvm/sema/src/core/package.rs
kclvm/sema/src/core/scope.rs
kclvm/sema/src/core/semantic_information.rs
kclvm/sema/src/core/symbol.rs
kclvm/sema/src/namer/mod.rs
kclvm/sema/src/namer/node.rs
kclvm/sema/src/resolver/mod.rs
kclvm/sema/src/ty/mod.rs
kclvm/tools/src/LSP/src/completion.rs
kclvm/tools/src/LSP/src/db.rs
kclvm/tools/src/LSP/src/document_symbol.rs
kclvm/tools/src/LSP/src/find_refs.rs
kclvm/tools/src/LSP/src/formatting.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/quick_fix.rs
kclvm/tools/src/LSP/src/request.rs
kclvm/tools/src/LSP/src/state.rs
kclvm/tools/src/LSP/src/test_data/goto_def_test/goto_def.k
kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/LSP/src/util.rs

1. use `goto_definition_with_gs` replace `goto_definition` and deprecated some functions in goto_def
2. add a resolve option `type_alias` to skip type_alias pass in lsp
sema/resolvar/mod.rs
lsp/goto_def.rs
lsp/util.rs
1. use `goto_definition_with_gs` replace `goto_definition` and deprecated some functions in goto_def
2. add a resolve option `type_alias` to skip type_alias pass in lsp

feat: migrate lsp goto_def to new sema model.

---

kclvm/tools/src/LSP/src/state.rs
kclvm/tools/src/LSP/src/tests.rs

lsp/state.rs
async build word index map when init lsp state， Konfig startup time reduced to 1/3 (27s -> 9s). There may still be some read-write locks
Konfig startup time reduced to 1/3 (27s -> 9s).

feat: async build word index map when init lsp state

---

kclvm/runtime/src/_kcl_run.rs
kclvm/runtime/src/api/kclvm.rs
kclvm/runtime/src/context/mod.rs
kclvm/runtime/src/value/api.rs
kclvm/runtime/src/value/val_type.rs

refactor: avoid use global context in panic hook

---

kclvm/sema/benches/my_benchmark.rs

fix #836
fix benchmark for sema
```
......
test result: ok. 0 passed; 0 failed; 38 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running benches/my_benchmark.rs (/workspaces/kcl/kclvm/target/release/deps/my_benchmark-26942d85c4160f9c)
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.
Gnuplot not found, using plotters backend
sup                     time:   [1.3954 µs 1.3963 µs 1.3973 µs]                 
change: [-0.5804% -0.4520% -0.3373%] (p = 0.00 < 0.05)
Change within …
```

fix: use Arc in sema benchmark

---

kclvm/ast/src/token.rs
kclvm/ast_pretty/src/node.rs
kclvm/ast_pretty/src/test_data/codelayout.input
kclvm/ast_pretty/src/test_data/codelayout.output
kclvm/parser/src/parser/stmt.rs
kclvm/parser/src/tests/error_recovery.rs
kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__schema_stmt_recovery_32.snap
kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__schema_stmt_recovery_33.snap
kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__schema_stmt_recovery_34.snap
kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__schema_stmt_recovery_35.snap
kclvm/sema/src/resolver/node.rs
test/grammar/schema/str_attr/str_attr_0/main.k
test/grammar/schema/str_attr/str_attr_0/stdout.golden
test/grammar/schema/str_attr/str_attr_1/main.k
test/grammar/schema/str_attr/str_attr_1/stdout.golden

Closes #585
feat: impl string-like schema attribute parser and ast printer
+ kclvm/ast/src/token.rs
+ kclvm/ast_pretty/src/test_data/codelayout.input

feat: impl string-like schema attribute parser and ast printer

---

kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/test_data/function_with_default_values.k
kclvm/sema/src/resolver/tests.rs

fix: normal func param default value
+ kclvm/sema/src/resolver/test_data/function_with_default_values.k

fix: normal func param default value

---

kclvm/Cargo.lock
kclvm/compiler/src/codegen/llvm/context.rs
kclvm/compiler/src/codegen/llvm/node.rs
kclvm/compiler/src/codegen/llvm/schema.rs
kclvm/compiler/src/macros.rs
kclvm/runner/src/assembler.rs
kclvm/sema/src/lib.rs
kclvm/sema/src/macros.rs
kclvm/sema/src/resolver/global.rs
kclvm/tools/src/LSP/Cargo.toml
kclvm/tools/src/LSP/src/completion.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/notification.rs
kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/LSP/src/util.rs

chore: deprecated semantic schema settings attr in the v0.7.0 stable version.
+ kclvm/sema/src/resolver/global.rs
+ kclvm/tools/src/LSP/src/completion.rs
+ kclvm/tools/src/LSP/src/completion.rs
+ kclvm/tools/src/LSP/src/hover.rs
+ kclvm/tools/src/LSP/src/tests.rs

chore: deprecated semantic schema settings attr in the v0.7.0 stable version.

---

kclvm/parser/src/lib.rs
kclvm/parser/src/tests.rs
kclvm/query/src/override.rs
kclvm/query/src/query.rs
kclvm/runner/benches/bench_runner.rs
kclvm/runner/src/lib.rs
kclvm/runner/src/tests.rs
kclvm/sema/src/advanced_resolver/mod.rs
kclvm/sema/src/namer/mod.rs
kclvm/sema/src/pre_process/tests.rs
kclvm/sema/src/resolver/tests.rs
kclvm/tools/src/LSP/src/util.rs
kclvm/tools/src/lint/mod.rs

/kclvm/parser
feat: support increment parser

feat: support increment parser

---

README-zh.md
README.md

+ docs: add artifact hub module link and use the latest installation documents
+ README-zh.md
+ README.md

docs: add artifact hub module link and use the latest installation documents

---

kclvm/ast/src/ast.rs
kclvm/query/src/query.rs
kclvm/runner/src/lib.rs
kclvm/sema/src/advanced_resolver/mod.rs
kclvm/sema/src/advanced_resolver/node.rs
kclvm/sema/src/pre_process/identifier.rs
kclvm/sema/src/resolver/cache.rs
kclvm/sema/src/resolver/mod.rs
kclvm/sema/src/resolver/tests.rs
kclvm/tools/src/LSP/src/util.rs
kclvm/tools/src/lint/mod.rs

re #866 
kclvm/sema/
kclvm/ast
feat: support incremental resolver

feat: support incremental resolver

---

kclvm/Cargo.lock
kclvm/ast/src/ast.rs
kclvm/query/src/lib.rs
kclvm/query/src/selector.rs
kclvm/query/src/util.rs
kclvm/spec/gpyrpc/gpyrpc.proto
kclvm/tools/src/LSP/Cargo.toml
kclvm/tools/src/LSP/src/lib.rs
kclvm/tools/src/LSP/src/rename.rs
kclvm/tools/src/LSP/src/test_data/rename_test/base/person.k
kclvm/tools/src/LSP/src/test_data/rename_test/config.k
kclvm/tools/src/LSP/src/util.rs

re #880
feat: implement rename api with new sema model

feat: implement rename api with new sema model

---

kclvm/tools/src/LSP/src/find_refs.rs
kclvm/tools/src/LSP/src/request.rs

close #763 
enhance: find refs support include declarations

enhance: find refs support include declarations

---

kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/test_data/ty_in_lambda.k
kclvm/sema/src/resolver/tests.rs
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/test_data/hover_test/ty_in_lambda.k

Fixed #821 
kclvm/sema/src/resolver/node.rs

fix: fix ty error in assignment

---

kclvm/tools/src/LSP/src/find_refs.rs
kclvm/tools/src/LSP/src/request.rs

kclvm/tools/src/LSP/src/find_refs.rs

arch: migrate lsp find_refs to new sema model

---

kclvm/api/src/capi_test.rs
kclvm/api/src/service/capi.rs
kclvm/api/src/service/service_impl.rs
kclvm/api/src/testdata/test.json
kclvm/api/src/testdata/test.response.json
kclvm/api/src/testdata/testing/module/kcl.mod
kclvm/api/src/testdata/testing/module/pkg/func.k
kclvm/api/src/testdata/testing/module/pkg/func_test.k
kclvm/spec/gpyrpc/gpyrpc.proto
kclvm/tools/src/testing/mod.rs
kclvm/tools/src/testing/suite.rs

re #178 
feat: impl test tool APIs
+ kclvm/spec/gpyrpc/gpyrpc.proto
+ Unit test: kclvm/api/src/service/service_impl.rs
+ e2e test: kclvm/api/src/capi_test.rs

feat: impl testing APIs

---

kclvm/Cargo.lock
kclvm/macros/src/symbols.rs
kclvm/span/src/symbol.rs
kclvm/tools/src/LSP/Cargo.toml
kclvm/tools/src/LSP/src/find_refs.rs
kclvm/tools/src/LSP/src/notification.rs
kclvm/tools/src/LSP/src/rename.rs
kclvm/tools/src/LSP/src/state.rs
kclvm/tools/src/LSP/src/util.rs

fix #894 
enhance: build word index prune word in comments

enhance: build word index prune word in comments

---

kclvm/api/src/capi_test.rs
kclvm/api/src/service/service_impl.rs
kclvm/api/src/testdata/get-all-full-schema-types.json
kclvm/api/src/testdata/get-all-full-schema-types.response.json
kclvm/api/src/testdata/get_schema_ty/aaa/main.k
kclvm/api/src/testdata/get_schema_ty/ccc/kcl.mod
kclvm/api/src/testdata/get_schema_ty/ccc/main.k
kclvm/query/src/query.rs

get all full schema types when schema name is empty

fix: get all full schema types when schema name is empty

---

kclvm/tools/src/LSP/src/find_refs.rs
kclvm/tools/src/LSP/src/tests.rs

close #893 
enhance: add limitation on find refs target number
This PR simply limit find refs target to first 20 items. We could make it configurable in the future.

enhance: add limitation on find refs target number

---

kclvm/sema/src/core/symbol.rs
kclvm/tools/src/LSP/src/document_symbol.rs
kclvm/tools/src/LSP/src/request.rs

- [N] N
lsp/document_symbol.rs
migrate lsp document_symbol to new sema model

arch: migrate lsp document_symbol to new sema model

---

kclvm/sema/src/advanced_resolver/mod.rs
kclvm/sema/src/advanced_resolver/node.rs
kclvm/sema/src/advanced_resolver/test_data/schema_symbols.k
kclvm/sema/src/core/symbol.rs
kclvm/tools/src/LSP/src/goto_def.rs

fix: resolve assert_stmt and config_entry correctly

---

kclvm/tools/src/LSP/src/analysis.rs
kclvm/tools/src/LSP/src/completion.rs
kclvm/tools/src/LSP/src/db.rs
kclvm/tools/src/LSP/src/find_refs.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/request.rs
kclvm/tools/src/LSP/src/state.rs
kclvm/tools/src/LSP/src/tests.rs

feat: asymc compile in lsp 
1 support async compile when vfs changes(open file and ChangeTextDocument). 2. remove scope in lsp db
lsp

feat: async compile in lsp

---

kclvm/tools/src/LSP/src/completion.rs
kclvm/tools/src/LSP/src/test_data/completion_test/dot/schema_ty_attr/schema_ty_attr.k
kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/LSP/src/util.rs

1 .dot completion of schema attr with schema type 
2. newline completion of schema attr when cursor in schema_stmt
1 .dot completion of schema attr with schema type 
2. newline completion of schema attr when cursor in schema_stmt

fix: fix lsp completion for newline char

---

kclvm/tools/src/LSP/src/completion.rs

enhance lsp complete for function params. use insert_text(place holder) to replace params name in CompletionItem label

feat: enhance lsp complete for function params

---

kclvm/sema/src/resolver/doc.rs
kclvm/tools/src/LSP/src/completion.rs

+ fix: doc gen string format
+ kclvm/sema/src/resolver/doc.rs

fix: doc gen string format

---

kclvm/tools/src/LSP/src/completion.rs

enhance lsp complete for schema value and schema type.

feat: enhance lsp complete for schema value and schema type.

---

kclvm/driver/src/tests.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/tests.rs

fix: set the kpm related test cases to execute sequentially

---

kclvm/ast/src/ast.rs
kclvm/sema/src/advanced_resolver/mod.rs
kclvm/sema/src/advanced_resolver/node.rs
kclvm/sema/src/core/global_state.rs
kclvm/sema/src/core/symbol.rs
kclvm/sema/src/resolver/node.rs
kclvm/tools/src/LSP/src/document_symbol.rs
kclvm/tools/src/LSP/src/semantic_token.rs

fix #953 
kclvm/ast
kclvm/sema
add expression symbol to provide more semantic information to LSP

feat: support expr symbol

---

kclvm/compiler/src/codegen/llvm/emit.rs
scripts/docker/kcl-builder-arm64/Dockerfile
scripts/docker/kcl-builder/Dockerfile

fix: https://github.com/kcl-lang/cli/issues/31

feat: add linux aarch64 llvm target

---

kclvm/sema/src/advanced_resolver/node.rs
kclvm/sema/src/core/global_state.rs
kclvm/sema/src/core/symbol.rs
kclvm/tools/src/LSP/src/completion.rs
kclvm/tools/src/LSP/src/document_symbol.rs
kclvm/tools/src/LSP/src/semantic_token.rs
kclvm/tools/src/LSP/src/test_data/completion_test/assign/completion.k
kclvm/tools/src/LSP/src/test_data/completion_test/dot/lit_str/lit_str.k

fix issues about wrong complete after str ty.
```
a = "1"
```

fix: fix lsp complete in comment after str type var

---

kclvm/sema/src/advanced_resolver/mod.rs
kclvm/sema/src/advanced_resolver/node.rs
kclvm/tools/src/LSP/src/semantic_token.rs
kclvm/tools/src/LSP/src/test_data/sema_token.k

lsp/semantic_token.rs
fix lsp semantic token(sema hight) of import stmt and unresolved token

fix: fix lsp semantic token(sema hight) of import stmt and unresolved token

---

README-zh.md
README.md

+ docs: add more integration in readme documents
+ README-zh.md
+ README.md

docs: add more integration in readme documents

---

kclvm/Cargo.lock
kclvm/api/src/service/into.rs
kclvm/api/src/service/service_impl.rs
kclvm/ast/Cargo.toml
kclvm/ast/src/ast.rs
kclvm/loader/src/lib.rs
kclvm/sema/src/advanced_resolver/mod.rs
kclvm/sema/src/advanced_resolver/node.rs
kclvm/sema/src/core/global_state.rs
kclvm/sema/src/core/scope.rs
kclvm/spec/gpyrpc/gpyrpc.proto

Close #979
+ feat: scope api for multiple lang sdks
+ feat: impl AST index serializer
+ kclvm/api/src/service/into.rs
+ kclvm/ast/src/ast.rs
+ kclvm/loader/src/lib.rs
+ kclvm/spec/gpyrpc/gpyrpc.proto
+ kclvm/sema/core/**

feat: scope api for multiple lang sdks

---

kclvm/ast/src/token.rs
kclvm/loader/src/lib.rs
kclvm/runtime/src/types/mod.rs
kclvm/runtime/src/value/mod.rs

issue #191 
Refactor KCLVM/loader
Not sure about the warning, maybe its giving a warning to update the rust version in the code? @Peefy

refactor(loader): fix warnings by 'cargo clippy' for loader

---

kclvm/config/src/cache.rs
kclvm/config/src/modfile.rs
kclvm/config/src/path.rs
kclvm/config/src/settings.rs

issue #191 
KCLVM/config
Before:
```
abhi_ubuntu@MADHUSANJ:~/kcl1/kcl/kclvm/driver$ cargo clippy --fix --allow-dirty
Checking kclvm-driver v0.7.4 (/home/abhi_ubuntu/kcl1/kcl/kclvm/driver)
warning: unnecessary `if let` since only the `Ok` variant of the iterator element is used
--> driver/src/lib.rs:31:5
|
31 |       for path in paths {
|       ^           ----- help: try: `paths.flatten()`
|  _____|
| |
32 | |         if let Ok(path) = path {
33 | |             matched_files.push(path.to_string_lossy().to_string());
34 | |         }
35 | |     }
| |_____^
|
help: ...and remove the `if let` statement in the for loop
--> driver/src/lib.rs:32:9
|
32 | /         if let Ok(path) = path {
33 | |             matched_files.push(path.to_string_lossy().to_string());
34 | |         }
| |_________^
= …
```

refactor(config): fix warnings by 'cargo clippy' for config

---

kclvm/api/src/service/into.rs
kclvm/api/src/service/service_impl.rs
kclvm/loader/src/lib.rs
kclvm/sema/src/advanced_resolver/node.rs
kclvm/sema/src/core/symbol.rs
kclvm/spec/gpyrpc/gpyrpc.proto

re #964 
+ kclvm/api/src/service/into.rs
+ kclvm/loader/src/lib.rs
+ kclvm/sema/src/core/symbol.rs
+ kclvm/spec/gpyrpc/gpyrpc.proto

feat: add symbol to node and type symbol APIs

---

kclvm/runtime/src/value/api.rs
kclvm/runtime/src/value/mod.rs
kclvm/runtime/src/value/val_schema.rs
kclvm/runtime/src/value/walker.rs
test/grammar/schema/optional_attr/fail_15/main.k
test/grammar/schema/optional_attr/fail_15/stderr.golden.py
test/grammar/schema/optional_attr/fail_16/main.k
test/grammar/schema/optional_attr/fail_16/stderr.golden.py
test/grammar/schema/optional_attr/fail_17/main.k
test/grammar/schema/optional_attr/fail_17/stderr.golden.py
test/grammar/schema/optional_attr/fail_18/main.k
test/grammar/schema/optional_attr/fail_18/stderr.golden.py
test/grammar/schema/optional_attr/fail_19/main.k
test/grammar/schema/optional_attr/fail_19/stderr.golden.py
test/grammar/schema/optional_attr/fail_20/main.k
test/grammar/schema/optional_attr/fail_20/stderr.golden.py

+ fix: schema optional attribute validating recursively
+ kclvm/runtime/src/value/mod.rs
+ kclvm/runtime/src/value/val_schema.rs
+ kclvm/runtime/src/value/walker.rs
+ test/grammar/schema/optional_attr/fail_15/main.k
+ test/grammar/schema/optional_attr/fail_16/main.k
+ test/grammar/schema/optional_attr/fail_17/main.k
+ test/grammar/schema/optional_attr/fail_18/main.k
+ test/grammar/schema/optional_attr/fail_19/main.k
+ test/grammar/schema/optional_attr/fail_20/main.k

fix: schema optional attribute validating recursively

---

kclvm/cmd/src/test_data/fuzz_match/main.k
kclvm/cmd/src/test_data/fuzz_match/main_unmatched.k
kclvm/cmd/src/tests.rs
kclvm/sema/src/resolver/attr.rs

+ fix: schema resolver type value load attribute error messages
+ kclvm/sema/src/resolver/attr.rs
+ kclvm/sema/src/resolver/test_fail_data/schema_type_value_attr.k

fix: schema resolver type value load attribute error messages

---

kclvm/api/src/capi_test.rs
kclvm/api/src/service/into.rs
kclvm/ast/src/ast.rs
kclvm/ast/src/lib.rs
kclvm/ast_pretty/src/tests.rs
kclvm/compiler/src/codegen/error.rs
kclvm/compiler/src/codegen/llvm/context.rs
kclvm/compiler/src/codegen/llvm/node.rs
kclvm/compiler/src/codegen/llvm/schema.rs
kclvm/compiler/src/codegen/llvm/utils.rs
kclvm/compiler/src/lib.rs
kclvm/compiler/src/macros.rs
kclvm/compiler/src/value/lambda.rs
kclvm/compiler/src/value/mod.rs
kclvm/compiler/src/value/schema.rs
kclvm/config/src/cache.rs
kclvm/config/src/lib.rs
kclvm/config/src/modfile.rs
kclvm/config/src/settings.rs
kclvm/driver/src/kpm_metadata.rs
kclvm/driver/src/lib.rs
kclvm/driver/src/tests.rs
kclvm/parser/src/lib.rs
kclvm/sema/src/builtin/system_module.rs
kclvm/version/src/lib.rs

re #191 
+ refactor: cargo clippy for api, compiler, config and sema crates

refactor: cargo clippy for api, compiler, config and sema crates

---

kclvm/runner/src/linker.rs

+ refactor: simplify the linker code
+ kclvm/runner/src/linker.rs

refactor: simplify the linker code

---

kclvm/sema/src/advanced_resolver/node.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/test_data/goto_def_test/goto_def.k

fix advanced resolver walk_list_if_item_expr

---

.github/workflows/build-test-macos-arm64.yml
.github/workflows/macos_test.yaml

close #1015 
+ .github/workflows/macos_test.yaml

ci: macos 13 xlarge action

---

kclvm/parser/src/parser/expr.rs
kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__config_recovery_13.snap
kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__config_recovery_14.snap
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/test_data/hover_test/hover.k

kclvm/parser/src/parser/expr.rs

fix: fix config if expr pos

---

kclvm/ast_pretty/src/node.rs
kclvm/query/src/lib.rs
kclvm/query/src/override.rs
kclvm/query/src/path.rs
kclvm/query/src/tests.rs
kclvm/tools/src/LSP/src/rename.rs

Close #1022
feat: impl subscript in override spec
+ kclvm/query/src/path.rs
+ kclvm/tools/src/LSP/src/rename.rs
+ kclvm/query/src/override.rs
+ kclvm/query/src/tests.rs

feat: impl subscript in override spec

---

compiler_base/parallel/src/executor/tests.rs
compiler_base/parallel/src/executor/timeout.rs

fixed #948 
compiler-base-parallel
If the number of threads started by the test reaches a large number randomly, e.g. 100000, some tasks will time out, resulting in a test ci failure. Therefore, set the timeout period to 120s

feat: add field 'timeout' to TimeoutExecutor to specify the timeout and increase the timeout in the test case to 120 seconds

---

kclvm/ast_pretty/src/node.rs

fixes #1039 
```kclvm/ast_pretty/src/node.rs```
https://github.com/kcl-lang/kcl/assets/134289475/b70dd7d7-c932-4761-8857-81b2e25c0966
- Since `if_stmt.orelse` is `Vec<NodeRef<Stmt>>`, so to format the code correctly for multiple if statements inside an else block, had to iterate through all the elements of `if_stmt.orelse`.
- This approach ensures that all the if statements are formatted correctly.

fix: formatting support for multiple if statements

---

.github/workflows/test_compiler_base.yaml
kclvm/Cargo.lock
kclvm/config/Cargo.toml
kclvm/config/src/cache.rs

+ chore: deprecated rust-crypto crate and use md5
+ kclvm/config/Cargo.toml
+ kclvm/config/src/cache.rs

chore: deprecated rust-crypto crate and use md5

---

kclvm/api/src/testdata/exec-program-with-include-schema-type-path.response.json
kclvm/runtime/src/value/val_plan.rs

+ feat: enhance full schema type path in the exec result
+ kclvm/runtime/src/value/val_plan.rs
+ kclvm/api/src/testdata/exec-program-with-include-schema-type-path.response.json

feat: enhance full schema type path in the exec result

---

kclvm/sema/src/advanced_resolver/node.rs
kclvm/sema/src/core/global_state.rs
kclvm/sema/src/core/scope.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/test_data/goto_def_test/goto_def.k

Fix the definition of duplicate parameter 

---

kclvm/api/src/service/service_impl.rs
kclvm/api/src/service/util.rs

+ kclvm/api/src/service/util.rs

feat: enhance plugin agent flag in APIs

---

kclvm/runtime/src/file/mod.rs
kclvm/sema/src/builtin/system_module.rs
kclvm/sema/src/resolver/test_data/test_builtin/glob.k
kclvm/sema/src/resolver/test_data/test_builtin/read.k
kclvm/sema/src/resolver/tests.rs
test/grammar/builtins/file/load_file_invalid/main.k
test/grammar/builtins/file/load_file_invalid/stderr.golden.py

Fixed #1049 
add type check for builtin filesystem functions

fix: add type check for builtin filesystem function

---

kclvm/Cargo.lock
kclvm/loader/Cargo.toml
kclvm/loader/src/lib.rs
kclvm/loader/src/snapshots/kclvm_loader__tests__assign_stmt_0.snap
kclvm/loader/src/snapshots/kclvm_loader__tests__assign_stmt_1.snap
kclvm/loader/src/snapshots/kclvm_loader__tests__assign_stmt_2.snap
kclvm/loader/src/snapshots/kclvm_loader__tests__import_stmt_0.snap
kclvm/loader/src/snapshots/kclvm_loader__tests__import_stmt_1.snap
kclvm/loader/src/tests.rs
kclvm/sema/src/core/symbol.rs

re #989 
+ kclvm/loader/src/lib.rs
+ kclvm/sema/src/core/symbol.rs
+ kclvm/loader/src/tests.rs

feat: add load_builtin option for the loader API and add more unit test cases

---

kclvm/compiler/src/codegen/llvm/node.rs
test/grammar/comprehension/dict/local_var_as_key/main.k
test/grammar/comprehension/dict/local_var_as_key/stdout.golden

fix #1061 
+ fix: key value eval in the config iter
+ test/grammar/comprehension/dict/local_var_as_key/main.k

fix: key value eval in the config iter

---

kclvm/sema/src/resolver/tests.rs
kclvm/sema/src/ty/mod.rs
kclvm/tools/src/LSP/src/completion.rs

1. Complete builtin function in root scope and lambda scope. 
2. Modify the label of the function's completion item to avoid fuzzy matching of function parameters to commonly used characters, such as x,y,z, and migrate function parameter descriptions to completion item detail
3. Remove duplicate functions
kclvm/tools/src/LSP/src/completion.rs

feat: enhance builtin func complete

---

kclvm/sema/src/resolver/config.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/test_fail_data/cannot_find_member_0.k
kclvm/sema/src/resolver/test_fail_data/cannot_find_member_1.k
kclvm/sema/src/resolver/tests.rs
kclvm/tools/src/LSP/src/quick_fix.rs

Close #1087 
feat: add better error message and quick fix for the list schema member
+ kclvm/tools/src/LSP/src/quick_fix.rs
+ kclvm/sema/src/resolver/tests.rs

feat: add better error message and quick fix for the list schema member

---

kclvm/tools/src/LSP/src/completion.rs
kclvm/tools/src/LSP/src/test_data/completion_test/dot/lit_str/lit_str.k

Remove the special judgment for literal strings during completion, and change the search for the nearest symbol during completion to the symbol one or two characters before the trigger.
fix #1083  
kclvm/tools/src/LSP/src/completion.rs

fix: literal str and join str inner completion

---

kclvm/sema/src/advanced_resolver/node.rs
kclvm/sema/src/core/global_state.rs
kclvm/sema/src/core/symbol.rs
kclvm/tools/src/LSP/src/document_symbol.rs
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/semantic_token.rs
kclvm/tools/src/LSP/src/test_data/hover_test/decorator.k
kclvm/tools/src/LSP/src/test_data/hover_test/hover.k

add decorator symbol in advanced resolver, add sema highlight nd hover for decorator symbol
Close #1068 
kclvm/sema/src/advanced_resolver
kclvm/tools/src/LSP
add decorator symbol in advanced resolver, add sema highlight nd hover for decorator symbol

feat: add decorator symbol

---

kclvm/sema/src/builtin/decorator.rs
kclvm/tools/src/LSP/src/hover.rs

+ refactor: make decorator document more simple
+ kclvm/sema/src/builtin/decorator.rs
+ kclvm/tools/src/LSP/src/hover.rs

refactor: make decorator document more simple

---

kclvm/sema/src/resolver/config.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/test_fail_data/unmatched_nest_schema_attr_0.k
kclvm/sema/src/resolver/test_fail_data/unmatched_nest_schema_attr_1.k
kclvm/sema/src/resolver/test_fail_data/unmatched_nest_schema_attr_2.k
kclvm/sema/src/resolver/test_fail_data/unmatched_nest_schema_attr_3.k
kclvm/sema/src/resolver/test_fail_data/unmatched_schema_attr_0.k
kclvm/sema/src/resolver/test_fail_data/unmatched_schema_attr_1.k
kclvm/sema/src/resolver/test_fail_data/unmatched_schema_attr_2.k
kclvm/sema/src/resolver/test_fail_data/unmatched_schema_attr_3.k
kclvm/sema/src/resolver/tests.rs
kclvm/sema/src/resolver/var.rs
kclvm/tools/src/LSP/src/completion.rs

+ feat: enhance anoymous schema type checking in the expr context stack
+ kclvm/sema/src/resolver/var.rs
+ kclvm/tools/src/LSP/src/completion.rs
+ kclvm/sema/src/resolver/test_fail_data/unmatched_nest_schema_attr_0.k
+ kclvm/sema/src/resolver/test_fail_data/unmatched_nest_schema_attr_1.k
+ kclvm/sema/src/resolver/test_fail_data/unmatched_nest_schema_attr_2.k
+ kclvm/sema/src/resolver/test_fail_data/unmatched_nest_schema_attr_3.k
+ kclvm/sema/src/resolver/test_fail_data/unmatched_schema_attr_0.k
+ kclvm/sema/src/resolver/test_fail_data/unmatched_schema_attr_1.k
+ kclvm/sema/src/resolver/test_fail_data/unmatched_schema_attr_2.k
+ kclvm/sema/src/resolver/test_fail_data/unmatched_schema_attr_3.k

feat: enhance anoymous schema type checking in the expr context stack

---

docs/design/ide_kpm_workflow.md

fixes #1058 
I added some workflow design for KCL IDE and kpm, Need reviews @Peefy @zong-zhe

doc: workflow design of IDE and kpm

---

kclvm/parser/src/parser/stmt.rs
kclvm/parser/src/tests/error_recovery.rs
kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__if_stmt_recovery_8.snap
kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__if_stmt_recovery_9.snap
test/grammar/syntax/else_if_token/main.k
test/grammar/syntax/else_if_token/stderr.golden.py

+ feat: add better error message for else if token parse recovery
+ test/grammar/syntax/else_if_token/main.k

feat: add better error message for else if token parse recovery

---

kclvm/sema/src/resolver/scope.rs
kclvm/sema/src/resolver/var.rs
test/grammar/schema/index_signature/key_alias_1/main.k
test/grammar/schema/irrelevant_order/inherit_1/main.k
test/grammar/schema/irrelevant_order/inherit_1/stdout.golden
test/grammar/schema/irrelevant_order/inherit_6/main.k
test/grammar/schema/var_not_define_fail/var_not_define_fail_0/main.k
test/grammar/schema/var_not_define_fail/var_not_define_fail_0/stderr.golden.py
test/grammar/schema/var_not_define_fail/var_not_define_fail_1/main.k
test/grammar/schema/var_not_define_fail/var_not_define_fail_1/stderr.golden.py

Closes #527 
feat: enhance schema attribute not found error message
+ kclvm/sema/src/resolver/var.rs
+ kclvm/sema/src/resolver/scope.rs
+ test/grammar/schema/var_not_define_fail/var_not_define_fail_0/main.k
+ test/grammar/schema/var_not_define_fail/var_not_define_fail_1/main.k

feat: enhance schema attribute not found error message

---

.github/workflows/build-test-linux-arm64.yml
.github/workflows/build-test-macos-arm64.yml
.github/workflows/daily-release.yaml
.github/workflows/macos_test.yaml
.github/workflows/test_compiler_base.yaml
.github/workflows/ubuntu_test.yaml
docs/dev_guide/1.about_this_guide.md
docs/dev_guide/2.quick_start.md
kclvm/Cargo.lock
kclvm/api/Cargo.toml
kclvm/config/Cargo.toml
kclvm/runtime/Cargo.toml
kclvm/tools/Cargo.toml
kclvm/tools/src/LSP/Cargo.toml

security issues: https://github.com/kcl-lang/kcl/security/dependabot
chore: bump rust toolchain to 1.76 and bump dep package versions to fix security issues
+ .github/workflows/**.yml
+ docs/dev_guide/2.quick_start.md
+ kclvm/tools/src/LSP/Cargo.toml
+ kclvm/tools/Cargo.toml
+ kclvm/runtime/Cargo.toml
+ kclvm/api/Cargo.toml
+ kclvm/config/Cargo.toml
All unit and grammar test cases

chore: bump rust toolchain to 1.76 and bump dep package versions to fix security issues

---

kclvm/driver/src/test_data/test_vendor/helloworld
kclvm/error/src/diagnostic.rs
kclvm/error/src/error.rs
kclvm/error/src/lib.rs
kclvm/sema/src/lint/lints_def.rs
kclvm/sema/src/resolver/tests.rs
kclvm/tools/src/LSP/src/quick_fix.rs
kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/LSP/src/to_lsp.rs
kclvm/tools/src/fix/mod.rs

fix #1113 
changes to multiple files
https://github.com/kcl-lang/kcl/assets/134289475/44e37c51-a6d0-4741-a2c9-362b6bdca09e
- Modified the `Message` struct from `Option<String>` to `Option<Vec<String>>`.
- Due to this I had to replace arguments which were passed to `suggested_replacement` field of `Message` struct.
- In `to_lsp.rs`, now the `suggested_replacement` key of the `data` field of `Diagnostics` is mapped to a vector of strings. 
- `extract_suggested_replacements` function in `quick_fix.rs` now returns a vector of replacement texts.
- Code Action for CompileError is iterated for each element of `replacement_texts` vector.
- Now we get multiple quick fix options for variable modification.
- Handled all the failing tests.

Provided multiple quick fix options for variable modification

---

kclvm/Cargo.lock
kclvm/driver/Cargo.toml
kclvm/driver/src/kpm.rs

- Added a new function `watch_kcl_mod` to monitor changes to the `kcl.mod` file and trigger dependency updates accordingly.
- Added a separate `kcl_mod_file_track` function that can be called from the LSP implementation(yet to be explore)
I want to know what target folders can be used for the calling of this `kcl_mod_file_track` 
Related Issue #998 
cc @Peefy @zong-zhe @He1pa

feat: support for automatic update KCL dependencies on kcl.mod file save

---

kclvm/tools/src/LSP/src/completion.rs
kclvm/tools/src/LSP/src/document_symbol.rs
kclvm/tools/src/LSP/src/find_refs.rs
kclvm/tools/src/LSP/src/formatting.rs
kclvm/tools/src/LSP/src/goto_def.rs
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/quick_fix.rs
kclvm/tools/src/LSP/src/request.rs
kclvm/tools/src/LSP/src/semantic_token.rs
kclvm/tools/src/LSP/src/state.rs
kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/LSP/src/util.rs

+ refactor: lsp cached scope usage
+ kclvm/tools/src/LSP/src/**
+ All unit test cases

refactor: lsp cached scope usage

---

kclvm/api/src/capi_test.rs
kclvm/api/src/testdata/list-options.json
kclvm/api/src/testdata/list-options.response.json
kclvm/loader/src/option.rs
kclvm/loader/src/snapshots/kclvm_loader__tests__list_options_1.snap
kclvm/loader/src/snapshots/kclvm_loader__tests__list_options_2.snap
kclvm/loader/src/snapshots/kclvm_loader__tests__list_options_3.snap
kclvm/loader/src/tests.rs
kclvm/loader/src/util.rs

+ fix: list options required param
+ kclvm/loader/src/option.rs
+ kclvm/api/src/capi_test.rs
+ kclvm/loader/src/snapshots/kclvm_loader__tests__list_options_3.snap
+ kclvm/loader/src/snapshots/kclvm_loader__tests__list_options_2.snap

fix: list options required param

---

kclvm/sema/src/resolver/calculation.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/ty/context.rs
test/grammar/types/binary_expr/binary_expr_3/main.k
test/grammar/types/binary_expr/binary_expr_3/stdout.golden

+ refactor: binary expr type error message locations
+ kclvm/sema/src/resolver/calculation.rs
+ test/grammar/types/binary_expr/binary_expr_3/main.k

refactor: binary expr type error message locations

---

kclvm/api/src/capi_test.rs
kclvm/api/src/service/capi.rs
kclvm/api/src/testdata/parse-file.json
kclvm/api/src/testdata/parse-file.response.json

fix https://github.com/kcl-lang/kcl-go/issues/260
fix: capi protobuf cstring convension
+ kclvm/api/src/capi_test.rs

fix: capi protobuf cstring convension

---

kclvm/Cargo.lock
kclvm/Cargo.toml
kclvm/compiler/src/codegen/llvm/context.rs
kclvm/compiler/src/codegen/llvm/node.rs
kclvm/evaluator/Cargo.toml
kclvm/evaluator/src/error.rs
kclvm/evaluator/src/lib.rs
kclvm/evaluator/src/node.rs
kclvm/evaluator/src/snapshots/kclvm_evaluator__tests__assign_stmt_0.snap
kclvm/evaluator/src/snapshots/kclvm_evaluator__tests__assign_stmt_1.snap
kclvm/evaluator/src/snapshots/kclvm_evaluator__tests__assign_stmt_2.snap
kclvm/evaluator/src/snapshots/kclvm_evaluator__tests__assign_stmt_3.snap
kclvm/evaluator/src/tests.rs
kclvm/runner/Cargo.toml
kclvm/runner/src/lib.rs
kclvm/runner/src/runner.rs
kclvm/runtime/src/value/api.rs
kclvm/runtime/src/value/mod.rs
kclvm/runtime/src/value/val_attr.rs
kclvm/runtime/src/value/val_dict.rs

re #291
+ feat: add initial version of evaluator
+ kclvm/compiler/src/codegen/llvm/context.rs
+ kclvm/evaluator/Cargo.toml
+ kclvm/evaluator/src/error.rs
+ kclvm/evaluator/src/node.rs
+ kclvm/evaluator/src/tests.rs

feat: add initial version of evaluator

---

docs/design/ide_kpm_watcher.md

Here are my thoughts about the `KCL watcher` system.
Relate comments for context:
https://github.com/kcl-lang/kcl/pull/1118#issuecomment-1985079103
https://github.com/kcl-lang/kcl/pull/1118#issuecomment-1985098268
cc @Peefy @zong-zhe @He1pa 
Target Issue #1132

design doc for kcl watcher

---

kclvm/tools/src/LSP/src/request.rs
kclvm/tools/src/LSP/src/tests.rs

* kclvm/tools/src/LSP/src/request.rs
* kclvm/tools/src/LSP/src/tests.rs

fix formatting of unsaved changes in LSP

---

kclvm/tools/src/LSP/src/analysis.rs
kclvm/tools/src/LSP/src/request.rs
kclvm/tools/src/LSP/src/state.rs

Fix the performance loss caused by lsp AnalysisDatabase clone, use Arc::clone instead
kclvm/tools/src/LSP/src/*
lsp performance optimization
Fix the performance loss caused by lsp AnalysisDatabase clone, use Arc::clone instead

fix: lsp db clone. 

---

kclvm/Cargo.lock
kclvm/tools/src/LSP/Cargo.toml
kclvm/tools/src/LSP/src/error.rs
kclvm/tools/src/LSP/src/notification.rs
kclvm/tools/src/LSP/src/request.rs
kclvm/tools/src/LSP/src/state.rs
kclvm/tools/src/LSP/src/util.rs

Add checks for retry termination conditions and retry intervals

fix: fixed infinite retry. 

---

kclvm/evaluator/src/calculation.rs
kclvm/evaluator/src/context.rs
kclvm/evaluator/src/error.rs
kclvm/evaluator/src/func.rs
kclvm/evaluator/src/lib.rs
kclvm/evaluator/src/module.rs
kclvm/evaluator/src/node.rs
kclvm/evaluator/src/proxy.rs
kclvm/evaluator/src/rule.rs
kclvm/evaluator/src/schema.rs
kclvm/evaluator/src/scope.rs
kclvm/evaluator/src/snapshots/kclvm_evaluator__tests__loop_1.snap
kclvm/evaluator/src/value.rs
kclvm/runner/src/lib.rs
kclvm/runner/src/runner.rs
kclvm/runtime/src/value/val.rs
kclvm/runtime/src/value/val_dict.rs
test/grammar/quant/all/multi_cons_valid_0/main.k

+ feat: impl more evaluator features and pass more test cases
+ kclvm/evaluator

feat: impl more evaluator features and pass more test cases

---

kclvm/tools/src/LSP/src/notification.rs
kclvm/tools/src/LSP/src/request.rs
kclvm/tools/src/LSP/src/state.rs

kclvm/tools/src/LSP/src/state.rs
kclvm/tools/src/LSP/src/notification.rs

fix: fix lsp document version verify.

---

kclvm/tools/src/LSP/src/find_refs.rs
kclvm/tools/src/LSP/src/notification.rs
kclvm/tools/src/LSP/src/quick_fix.rs
kclvm/tools/src/LSP/src/request.rs
kclvm/tools/src/LSP/src/state.rs
kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/LSP/src/util.rs

kclvm/tools/src/LSP/src/*
feat: lsp compile unit cache.
Add watcher for config file(kcl.mod and kcl.yaml). clear cache when edit config files.

feat:Lsp compile unit cache watcher for config file(kcl.yaml and kcl.mod).

---

kclvm/tools/src/LSP/src/tests.rs

kclvm/tools/src/LSP/src/tests.rs
fix ut

test: fix compile_unit_cache ut

---

kclvm/evaluator/src/context.rs
kclvm/evaluator/src/func.rs
kclvm/evaluator/src/node.rs
kclvm/evaluator/src/proxy.rs
kclvm/evaluator/src/schema.rs
kclvm/evaluator/src/ty.rs

re #291
+ kclvm/evaluator/src/ty.rs
+ kclvm/evaluator/src/schema.rs
+ kclvm/evaluator/src/context.rs
+ kclvm/evaluator/src/func.rs
+ kclvm/evaluator/src/node.rs
+ kclvm/evaluator/src/proxy.rs
+ All unit test cases
+ All grammar test cases

feat: add backtrace context for the evaluator

---

.gitignore
kclvm/api/src/service/service_impl.rs

+ feat: add loader API with state
+ .gitignore

feat: add loader API with state

---

kclvm/tools/src/LSP/src/tests.rs
kclvm/tools/src/LSP/src/util.rs

update cache in fn `compile_unit_with_cache`
kclvm/tools/src/LSP/src/util.rs

fix: fix compile unit cache.

---

kclvm/runtime/src/value/api.rs

fix: runtime number singleton value cache

---

kclvm/Cargo.lock
kclvm/sema/Cargo.toml
kclvm/sema/src/resolver/doc.rs

+ refactor: doc string parse to prevent the regex calling
+ Removed the regex library prec2, as it requires c99 compilation in some old gcc environments (such as centos7)
+ Removed one clone deep copy and directly used the strip function to remove the first quotation mark
+ kclvm/sema/Cargo.toml
+ kclvm/sema/src/resolver/doc.rs
+ kclvm/sema/src/resolver/doc.rs

refactor: doc string parse to prevent the regex calling and remove the prec2 deps

---

kclvm/runner/Cargo.toml
kclvm/runner/src/lib.rs
kclvm/runner/src/tests.rs

fix #1222
+ kclvm/runner/src/lib.rs
+ kclvm/runner/src/tests.rs

feat: add build lock for common package cache path

---

kclvm/ast/src/ast.rs
kclvm/ast_pretty/src/node.rs
kclvm/ast_pretty/src/test_data/codelayout.output
kclvm/sema/src/pre_process/identifier.rs
kclvm/sema/src/resolver/node.rs
test/grammar/schema/string_attr/simple_0/main.k
test/grammar/schema/string_attr/simple_0/stdout.golden
test/grammar/schema/string_attr/simple_1/main.k
test/grammar/schema/string_attr/simple_1/stdout.golden

fix #1227 
fix: schema string attribute contains dot
+ kclvm/ast/src/ast.rs
+ kclvm/sema/src/pre_process/identifier.rs
+ test/grammar/schema/string_attr/simple_0/main.k
+ test/grammar/schema/string_attr/simple_1/main.k

fix: schema string attribute contains dot

---

.github/workflows/build-test-macos-arm64.yml
kclvm/evaluator/src/func.rs
kclvm/evaluator/src/lib.rs
kclvm/evaluator/src/node.rs
test/grammar/lambda/in_schema_10/main.k
test/grammar/lambda/in_schema_10/stdout.golden
test/grammar/lambda/in_schema_9/main.k
test/grammar/lambda/in_schema_9/stdout.golden

+ fix: lambda in schema function calling for the evaluator
+ kclvm/evaluator/src/func.rs
+ kclvm/evaluator/src/lib.rs
+ kclvm/evaluator/src/node.rs
+ .github/workflows/build-test-macos-arm64.yml
+ test/grammar/lambda/in_schema_10/main.k
+ test/grammar/lambda/in_schema_9/main.k

fix: lambda in schema function calling for the evaluator

---

kclvm/query/src/override.rs
kclvm/query/src/test_data/test_override_file/expect.k
kclvm/query/src/test_data/test_override_file/main.bk.k
kclvm/query/src/test_data/test_override_file/main.k
kclvm/query/src/tests.rs

feat: override_file will insert a new variable if the variable is not exist

---

kclvm/parser/src/lib.rs
kclvm/sema/src/resolver/scope.rs

kclvm/parser/src/lib
kclvm/sema/src/resolver/scope
1. resolver cache clear impl bug. Insert pkgpath in to invalidated_set while cause line 616  always be true and the rest of this function will never be executed. It will pop_front and continue until the queue is empty.
```
if invalidated_set.contains(&cur_node.pkgpath) {
continue;
}
```
2. fix: fix parse cache. First update all AST information. When constructing pkg recursively, it will try to get AST information from the cache(line 382  `self.load_import_package()`). In the previous implementation, the old version of AST was obtained in recursion, and then the new version of AST was added to the main package, resulting in inconsistent AST versions of the same file in the main package and other pkgs.

Fix: fix incremental compilation unwrap panic in AdvancerResolver

---

kclvm/evaluator/src/node.rs
test/grammar/quant/all/simple_valid_4/main.k
test/grammar/quant/all/simple_valid_4/stdout.golden

fix: evaluator quant expr

---

README-zh.md
README.md

docs: update tool integration link and multi SDKs description in readme

docs: update tool integration link and multi SDKs description in readme

---

kclvm/api/src/service/ty.rs
kclvm/query/src/query.rs
kclvm/spec/gpyrpc/gpyrpc.proto

- [ ✅] Y 
fix #1215 
`kclvm/query/src/query.rs`
`kclvm/spec/gpyrpc/gpyrpc.proto`
`kclvm/api/src/service/ty.rs`
the `get_schema_type` function will return `SchemaType` instances with base schema information included, while the `get_full_schema_type` function will return `SchemaType` instances with the complete inheritance hierarchy resolved
- [ ✅] N
N

`get_schema_type` function will now return `SchemaType` instances with base schema information included

---

kclvm/evaluator/src/calculation.rs
kclvm/evaluator/src/node.rs
kclvm/evaluator/src/schema.rs
kclvm/evaluator/src/ty.rs
kclvm/runtime/src/value/api.rs
kclvm/runtime/src/value/val_plan.rs
kclvm/runtime/src/value/val_type.rs
kclvm/sema/src/resolver/node.rs
kclvm/sema/src/resolver/tests.rs
kclvm/tools/src/LSP/src/test_data/completion_test/import/external/kcl.mod
test/grammar/schema/factory/test_0/main.k
test/grammar/schema/factory/test_0/stdout.golden
test/grammar/schema/factory/test_1/main.k
test/grammar/schema/factory/test_1/stdout.golden
test/grammar/schema/factory/test_2/main.k
test/grammar/schema/factory/test_2/stdout.golden
test/grammar/types/type_as/type_as_5/main.k
test/grammar/types/type_as/type_as_5/pkg/pkg.k
test/grammar/types/type_as/type_as_5/stdout.golden
test/grammar/types/type_as/type_as_6/main.k
test/grammar/types/type_as/type_as_6/stdout.golden
test/grammar/types/type_as/type_as_err_2/main.k
test/grammar/types/type_as/type_as_err_2/stderr.golden.py

fix #1265 
feat: enhance the schema expr type check and impl the schema factory using the runtime dynamic type string.
test cases are
+ test/grammar/schema/factory/test_0/main.k
+ test/grammar/schema/factory/test_1/main.k
+ test/grammar/schema/factory/test_2/main.k

feat: enhance the schema expr type check and impl the schema factory using the dynamic type

---

kclvm/runtime/src/file/mod.rs
kclvm/runtime/src/file/utils.rs
kclvm/sema/src/builtin/system_module.rs

+ feat: add file folder cp
+ kclvm/runtime/src/file/mod.rs
+ kclvm/runtime/src/file/utils.rs
+ kclvm/sema/src/builtin/system_module.rs

feat: add file folder cp

---

kclvm/api/src/service/service_impl.rs
kclvm/api/src/testdata/list-variables.response.json
kclvm/query/src/selector.rs
kclvm/query/src/tests.rs
kclvm/spec/gpyrpc/gpyrpc.proto

feat: add operation for variable in ListVariables

---

kclvm/Cargo.lock
kclvm/compiler/src/codegen/llvm/context.rs
kclvm/compiler/src/codegen/llvm/module.rs
kclvm/compiler/src/codegen/llvm/node.rs
kclvm/compiler/src/codegen/mod.rs
kclvm/compiler/src/codegen/traits/builder.rs
kclvm/compiler/src/codegen/traits/type.rs
kclvm/compiler/src/codegen/traits/value.rs
kclvm/compiler/src/value/schema.rs
kclvm/evaluator/src/node.rs
kclvm/runner/src/linker.rs
kclvm/runner/src/runner.rs
kclvm/runtime/Cargo.toml
kclvm/runtime/src/_kcl_run.rs
kclvm/runtime/src/stdlib/plugin.rs
kclvm/src/lib.rs
kclvm/tools/src/vet/tests.rs

feat: top level variable back reference infra

feat: top level variable back reference infra

---

kclvm/api/src/service/service_impl.rs
kclvm/loader/src/snapshots/kclvm_loader__tests__assign_stmt_0.snap
kclvm/loader/src/snapshots/kclvm_loader__tests__assign_stmt_1.snap
kclvm/loader/src/snapshots/kclvm_loader__tests__assign_stmt_2.snap
kclvm/loader/src/snapshots/kclvm_loader__tests__builtin_call_0.snap
kclvm/loader/src/snapshots/kclvm_loader__tests__builtin_call_1.snap
kclvm/loader/src/snapshots/kclvm_loader__tests__builtin_call_2.snap
kclvm/loader/src/snapshots/kclvm_loader__tests__import_stmt_0.snap
kclvm/loader/src/snapshots/kclvm_loader__tests__import_stmt_1.snap
kclvm/runtime/src/_kclvm.h
kclvm/runtime/src/_kclvm.ll
kclvm/runtime/src/_kclvm.rs
kclvm/runtime/src/_kclvm_addr.rs
kclvm/runtime/src/_kclvm_api_spec.rs
kclvm/runtime/src/file/mod.rs
kclvm/sema/src/builtin/system_module.rs
test/grammar/builtins/file/write/main.k

Fixes #1267 
kcl-lang/kcl/kclvm

feat: added file.write

---

kclvm/evaluator/src/ty.rs
kclvm/runtime/src/value/val_type.rs

+ fix: type cast when exists external package
+ kclvm/evaluator/src/ty.rs
+ kclvm/runtime/src/value/val_type.rs

fix: type cast when exists external package

---

kclvm/Cargo.lock
kclvm/api/Cargo.toml
kclvm/ast/Cargo.toml
kclvm/ast/src/ast.rs
kclvm/parser/src/parser/mod.rs
kclvm/utils/Cargo.toml
kclvm/utils/src/path.rs

fix the inconsistency in filename drive letters in Windows caused bycanonicalize() function
kclvm/parser/src/parser/mod.rs

fix: fix the inconsistency in filename drive letters

---

kclvm/Cargo.lock
kclvm/ast/src/ast.rs
kclvm/error/Cargo.toml
kclvm/error/src/diagnostic.rs
kclvm/parser/src/lib.rs
kclvm/parser/src/parser/mod.rs
kclvm/tools/src/LSP/src/from_lsp.rs
kclvm/tools/src/util/loader.rs
kclvm/utils/src/path.rs

kclvm/ast/src/ast.rs
kclvm/error/src/diagnostic.rs
kclvm/parser/src/lib.rs
kclvm/parser/src/parser/mod.rs
kclvm/tools/src/LSP/src/from_lsp.rs
kclvm/tools/src/util/loader.rs
kclvm/utils/src/path.rs

fix: fix ast and lsp filename in windows os

---

kclvm/tools/src/LSP/src/hover.rs

added a test case for hover docs

---

kclvm/sema/src/ty/mod.rs
kclvm/tools/src/LSP/src/completion.rs

fix #1303 
kcl/kclvm/sema/src/ty/mod.rs
"schema Data1\[n: str](Data)" was being misinterpreted as markdown "schema Data1[n: str](Data)".

fix: lsp hover docs

---

kclvm/query/src/selector.rs
kclvm/query/src/test_data/test_list_variables/unsupported.k
kclvm/query/src/tests.rs

fix: fix missing variables in api ListVariable() when list from KCL with unsupported expr

---

kclvm/loader/src/lib.rs
kclvm/sema/src/advanced_resolver/mod.rs
kclvm/sema/src/advanced_resolver/node.rs
kclvm/tools/src/LSP/src/rename.rs
kclvm/tools/src/LSP/src/util.rs

Change `AdvancedResolver::resolve_program()` return type from Option<Symbol> to Result<Option<Symbol>>
Remove unwrap() in `resolve_program()`
kclvm/sema/src/advanced_resolver
tools/src/LSP
remove unwrap() in advanced_resolver.

refactor: remove unwrap() in advanced_resolver. 

---

kclvm/sema/src/resolver/mod.rs
kclvm/sema/src/resolver/scope.rs

fix resolver cache caused falsely report errors. Add schema mapping to resolver cache
kclvm/sema/src/resolver/mod.rs
fix resolver cache caused falsely report errors. Add schema mapping to resolver cache

fix: fix resolver cache caused falsely report errors.

---

kclvm/sema/src/core/symbol.rs
kclvm/sema/src/namer/node.rs
kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/test_data/hover_test/inherit.k

kclvm/sema/src/core/symbol.rs
kclvm/tools/src/LSP/hover.rs

fix: fix inherit schema attrs hover

---

kclvm/sema/src/resolver/import.rs
test/grammar/import/empty_import_fail/stderr.golden.py

Closes #1327 
+ kclvm/sema/src/resolver/import.rs
+ test/grammar/import/empty_import_fail/

feat: enhance err msg when import empty local path

---

kclvm/sema/src/advanced_resolver/node.rs

fix advanced resolver get node type 
return Ok(None) instead of Err()

fix: fix advanced resolver get node type. 

---

kclvm/sema/src/advanced_resolver/node.rs
kclvm/sema/src/ty/mod.rs
kclvm/tools/src/LSP/src/inlay_hints.rs
kclvm/tools/src/LSP/src/snapshots/kcl_language_server__inlay_hints__tests__config_key_ty.snap
kclvm/tools/src/LSP/src/test_data/inlay_hints/config_key/config_key.k

feat: inlayhint for config key type

---

kclvm/api/src/service/service_impl.rs
kclvm/ast/src/ast.rs
kclvm/cmd/src/tests.rs
kclvm/config/src/modfile.rs
kclvm/config/src/tests.rs
kclvm/driver/src/lib.rs
kclvm/parser/src/lib.rs
kclvm/parser/src/tests.rs
kclvm/tools/src/LSP/src/from_lsp.rs
kclvm/tools/src/LSP/src/hover.rs

remove windows path prefix

---

kclvm/sema/src/advanced_resolver/node.rs
kclvm/sema/src/core/symbol.rs
kclvm/tools/src/LSP/src/inlay_hints.rs
kclvm/tools/src/LSP/src/snapshots/kcl_language_server__inlay_hints__tests__config_key_ty.snap
kclvm/tools/src/LSP/src/snapshots/kcl_language_server__inlay_hints__tests__config_key_ty_1.snap
kclvm/tools/src/LSP/src/test_data/inlay_hints/config_key1/config_key.k

https://github.com/orgs/kcl-lang/discussions/1657   
https://github.com/kcl-lang/kcl/pull/1659  
https://github.com/kcl-lang/kcl/pull/1692
kclvm/tools/src/LSP/src/inlay_hints.rs

feat: lsp hint for config entry key type

---

.github/workflows/macos_test.yaml
.github/workflows/ubuntu_test.yaml
.github/workflows/windows_test.yaml

fix: fix ci

---

kclvm/src/capi.rs

fix func kcl_alloc. 

---

kclvm/runtime/src/api/utils.rs

fix: fix #1776 use assert add no overhead on release version

---

kclvm/evaluator/src/snapshots/kclvm_evaluator__tests__list_comp1.snap
kclvm/evaluator/src/tests.rs
kclvm/runtime/src/value/iter.rs

fix: fix iter unicode string

---

kclvm/sema/src/resolver/config.rs
test/grammar/schema/index_signature/fail_12/main.k
test/grammar/schema/index_signature/fail_12/stderr.golden

fixes #1804 
+ test/grammar/schema/index_signature/fail_12/main.k

fix: index signature str union ty check

---

kclvm/driver/src/lib.rs

In a folder kind Workspace, it will recursively search upwards for kcl.mod to find dependencies

fix: fix lsp folder workspace options. 

---

kclvm/sema/src/core/global_state.rs
kclvm/sema/src/core/symbol.rs
kclvm/sema/src/namer/mod.rs
kclvm/sema/src/resolver/mod.rs
kclvm/sema/src/resolver/tests.rs

fix: fix lsp memory leak

---

kclvm/tools/src/LSP/src/hover.rs
kclvm/tools/src/LSP/src/test_data/hover_test/schema_with_examples.k
kclvm/tools/src/LSP/src/tests.rs

fix https://github.com/kcl-lang/kcl/issues/1469 
kcl/kclvm/tools/src/LSP/src/hover.rs
kcl/kclvm/tools/src/LSP/src/test_data/hover_test/schema_with_examples.k

Enhancement: Add example highlight hover content for the schema definition doc 

---

.github/workflows/ubuntu_arm_test.yaml

fix: the release of linux arm64 artifact is missing
